# College Fooball Data Exploratory Data Analysis

## Contents 
1. [Load Data](#Load-Data)
2. [Inspect Data](#Inspect-Data)
    - [Player Stats](#Player-Stats)
    - [Draft Data](#Inspect-Data)
3. [Prune Unnecessary Features](#Prune-Unnecessary-Columns)
    - [Prune Player Stats](#Prune-Player-Stats)
    - [Prune Player Draft Data](#Prune-Player-Draft-Data)
4. [Player Level Aggregation](#Player-Level-Aggregation)
    - [Pivot Player Stats](#Pivot-Player-Stats)
5. [nflverse Join Critera](#nflverse-Join-Critera)

## Dependencies

In [2]:
import pandas as pd 
import numpy as np 
import json
import os  
from pathlib import Path

## Load Data

In [3]:
# File Paths
from os import path


BASE_DIR = Path.cwd()
DATA_DIR = BASE_DIR / "src/data_ingestion/college_data"

# Hold DataFrames
dfs = {}

# Read in all JSON files in the data directory and normalize them into DataFrames
for item in DATA_DIR.iterdir():
    if item.is_file():
        with open(item, encoding="utf-8") as f:
            dfs[item.stem] = pd.json_normalize(json.load(f), sep="_")
        print(f"Loaded {item.stem} into DataFrame with shape {dfs[item.stem].shape}")

Loaded 2025_draft into DataFrame with shape (257, 24)
Loaded 2026_draft into DataFrame with shape (257, 24)
Loaded 2024_stats into DataFrame with shape (135294, 9)
Loaded 2025_stats into DataFrame with shape (141627, 9)

## Inspect Data

### Player Stats

In [4]:
stat_sample = dfs["2024_stats"]

display(stat_sample.info())
stat_sample.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 135294 entries, 0 to 135293
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   season      135294 non-null  int64
 1   playerId    135294 non-null  str
 2   player      135294 non-null  str
 3   position    135294 non-null  str
 4   team        135294 non-null  str
 5   conference  135294 non-null  str
 6   category    135294 non-null  str
 7   statType    135294 non-null  str
 8   stat        135294 non-null  str
dtypes: int64(1), str(8)
memory usage: 16.3 MB

None

,season,playerId,player,position,team,conference,category,statType,stat
0,2024,102597,Will Rogers,QB,Washington,Big Ten,defensive,PD,0
1,2024,102597,Will Rogers,QB,Washington,Big Ten,defensive,QB HUR,0
2,2024,102597,Will Rogers,QB,Washington,Big Ten,defensive,SACKS,0
3,2024,102597,Will Rogers,QB,Washington,Big Ten,defensive,SOLO,1
4,2024,102597,Will Rogers,QB,Washington,Big Ten,defensive,TD,0
5,2024,102597,Will Rogers,QB,Washington,Big Ten,defensive,TFL,0
6,2024,102597,Will Rogers,QB,Washington,Big Ten,defensive,TOT,1
7,2024,102597,Will Rogers,QB,Washington,Big Ten,fumbles,FUM,5
8,2024,102597,Will Rogers,QB,Washington,Big Ten,fumbles,LOST,2
9,2024,102597,Will Rogers,QB,Washington,Big Ten,fumbles,REC,1

### Draft Data

In [5]:
stat_sample = dfs["2025_draft"]

display(stat_sample.info())
stat_sample.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 257 entries, 0 to 256
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   collegeAthleteId         257 non-null    int64
 1   nflAthleteId             257 non-null    int64
 2   collegeId                257 non-null    int64
 3   collegeTeam              257 non-null    str
 4   collegeConference        257 non-null    str
 5   nflTeamId                257 non-null    int64
 6   nflTeam                  257 non-null    str
 7   year                     257 non-null    int64
 8   overall                  257 non-null    int64
 9   round                    257 non-null    int64
 10  pick                     257 non-null    int64
 11  name                     257 non-null    str
 12  position                 257 non-null    str
 13  height                   248 non-null    float64
 14  weight                   248 non-null    float64
 15  preDraftRanking          245 non-null    float64
 16  preDraftPositionRanking  245 non-null    float64
 17  preDraftGrade            245 non-null    float64
 18  hometownInfo_city        256 non-null    str
 19  hometownInfo_state       255 non-null    str
 20  hometownInfo_country     256 non-null    str
 21  hometownInfo_latitude    250 non-null    str
 22  hometownInfo_longitude   250 non-null    str
 23  hometownInfo_countyFips  250 non-null    str
dtypes: float64(5), int64(8), str(11)
memory usage: 70.7 KB

None

,collegeAthleteId,nflAthleteId,collegeId,collegeTeam,collegeConference,nflTeamId,nflTeam,year,overall,round,...,weight,preDraftRanking,preDraftPositionRanking,preDraftGrade,hometownInfo_city,hometownInfo_state,hometownInfo_country,hometownInfo_latitude,hometownInfo_longitude,hometownInfo_countyFips
0,4688380,107910,2390,Miami,ACC,10,Tennessee,2025,1,1,...,219.0,8.0,1.0,92.0,West Columbia,TX,USA,29.1438582,-95.6452249,48039
1,4685415,109188,38,Colorado,Big 12,30,Jacksonville,2025,2,1,...,188.0,2.0,1.0,94.0,Suwanee,GA,USA,34.0514898,-84.0712997,13135
2,4725996,109198,213,Penn State,Big Ten,19,New York,2025,3,1,...,250.0,1.0,1.0,94.0,Philadelphia,PA,USA,39.9527237,-75.1635262,42101
3,4685298,109195,99,LSU,SEC,17,New England,2025,4,1,...,319.0,14.0,2.0,91.0,Monroe,LA,USA,32.5093109,-92.1193012,22073
4,4873232,109186,130,Michigan,Big Ten,5,Cleveland,2025,5,1,...,296.0,5.0,1.0,93.0,Anaheim,CA,USA,33.8347516,-117.911732,06059
5,4890973,109201,68,Boise State,Mountain West,13,Las Vegas,2025,6,1,...,211.0,3.0,1.0,93.0,Jacksonville,FL,USA,30.3321838,-81.655651,12031
6,4789907,109329,142,Missouri,SEC,20,New York,2025,7,1,...,332.0,9.0,1.0,91.0,Lee's Summit,MO,USA,38.9107156,-94.3821295,29095
7,4685472,109190,12,Arizona,Big 12,29,Carolina,2025,8,1,...,219.0,13.0,1.0,91.0,Anaheim,CA,USA,33.8347516,-117.911732,06059
8,4685260,109191,251,Texas,SEC,18,New Orleans,2025,9,1,...,315.0,26.0,4.0,88.0,Humble,TX,USA,29.9988312,-95.2621553,48201
9,4723086,109216,130,Michigan,Big Ten,3,Chicago,2025,10,1,...,248.0,7.0,2.0,92.0,Gooding,ID,USA,42.9389067,-114.7131938,16047

## Prune Unnecessary Features

Fantasy Football is primarily focused on offensive statistics, the following code identifies irrelevant categories and drops them before creating a player level aggregate.

### Prune Player Stats

In [6]:

# Make sure all stat categories are the same between 2024 and 2025 stats
# Save the stat categories that are in both 2024 and 2025 stats to a variable for later use

stat_categories = set(dfs['2024_stats'].category.unique()) - set(dfs['2025_stats'].category.unique())
if len(stat_categories) > 0:
    print(f"Stat categories in 2024 but not in 2025: {stat_categories}")

else: 
    print("All stat categories are the same between 2024 and 2025 stats.")
    stat_categories = set(dfs['2025_stats'].category.unique()) & set(dfs['2024_stats'].category.unique())
    print(f"Stat categories in both 2024 and 2025: {stat_categories}")

all_stats =  pd.concat([dfs["2024_stats"], dfs["2025_stats"]], ignore_index=True)
display(all_stats.info())

All stat categories are the same between 2024 and 2025 stats.
Stat categories in both 2024 and 2025: {'kickReturns', 'defensive', 'punting', 'receiving', 'fumbles', 'puntReturns', 'interceptions', 'rushing', 'kicking', 'passing'}
<class 'pandas.DataFrame'>
RangeIndex: 276921 entries, 0 to 276920
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   season      276921 non-null  int64
 1   playerId    276921 non-null  str
 2   player      276921 non-null  str
 3   position    276921 non-null  str
 4   team        276921 non-null  str
 5   conference  276921 non-null  str
 6   category    276921 non-null  str
 7   statType    276921 non-null  str
 8   stat        276921 non-null  str
dtypes: int64(1), str(8)
memory usage: 33.4 MB

None

In [7]:
# Retained Features 
stats_retain_features = ['receiving', 'passing', 'rushing', 'fumbles', 'kicking']

# Filter DataFrame to only include rows with the retained features
all_stats_filtered = all_stats[all_stats['category'].isin(stats_retain_features)]
print(f"Features Removed: {set(all_stats['category'].unique()) - set(all_stats_filtered['category'].unique())}")

Features Removed: {'kickReturns', 'defensive', 'punting', 'puntReturns', 'interceptions'}

### Prune Player Draft Data

In [8]:
draft_features = set(dfs['2025_draft'].columns) - set(dfs['2026_draft'].columns)
if len(draft_features) > 0:
    print(f"Draft features in 2025 but not in 2026: {draft_features}")

else: 
    print("All draft features are the same between 2025 and 2026 stats.")
    draft_features = set(dfs['2025_draft'].columns) & set(dfs['2026_draft'].columns)
    print(f"Draft features in both 2025 and 2026: {draft_features}")

all_draft = pd.concat([dfs["2025_draft"], dfs["2026_draft"]], ignore_index=True)
display(all_draft.info())

# View Features in the all_draft DataFrame
print(all_draft.columns)

All draft features are the same between 2025 and 2026 stats.
Draft features in both 2025 and 2026: {'collegeConference', 'hometownInfo_latitude', 'height', 'nflAthleteId', 'collegeTeam', 'position', 'hometownInfo_state', 'preDraftGrade', 'collegeId', 'hometownInfo_countyFips', 'round', 'nflTeam', 'preDraftRanking', 'collegeAthleteId', 'pick', 'year', 'preDraftPositionRanking', 'weight', 'name', 'overall', 'hometownInfo_city', 'hometownInfo_country', 'hometownInfo_longitude', 'nflTeamId'}
<class 'pandas.DataFrame'>
RangeIndex: 514 entries, 0 to 513
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   collegeAthleteId         514 non-null    int64
 1   nflAthleteId             514 non-null    int64
 2   collegeId                514 non-null    int64
 3   collegeTeam              514 non-null    str
 4   collegeConference        513 non-null    str
 5   nflTeamId                514 non-null    int64
 6   nflTeam                  514 non-null    str
 7   year                     514 non-null    int64
 8   overall                  514 non-null    int64
 9   round                    514 non-null    int64
 10  pick                     514 non-null    int64
 11  name                     514 non-null    str
 12  position                 514 non-null    str
 13  height                   497 non-null    float64
 14  weight                   497 non-null    float64
 15  preDraftRanking          491 non-null    float64
 16  preDraftPositionRanking  491 non-null    float64
 17  preDraftGrade            491 non-null    float64
 18  hometownInfo_city        512 non-null    str
 19  hometownInfo_state       507 non-null    str
 20  hometownInfo_country     512 non-null    str
 21  hometownInfo_latitude    490 non-null    str
 22  hometownInfo_longitude   490 non-null    str
 23  hometownInfo_countyFips  490 non-null    str
dtypes: float64(5), int64(8), str(11)
memory usage: 140.7 KB

None

Index(['collegeAthleteId', 'nflAthleteId', 'collegeId', 'collegeTeam',
       'collegeConference', 'nflTeamId', 'nflTeam', 'year', 'overall', 'round',
       'pick', 'name', 'position', 'height', 'weight', 'preDraftRanking',
       'preDraftPositionRanking', 'preDraftGrade', 'hometownInfo_city',
       'hometownInfo_state', 'hometownInfo_country', 'hometownInfo_latitude',
       'hometownInfo_longitude', 'hometownInfo_countyFips'],
      dtype='str')

In [9]:
draft_retain_features = ['collegeAthleteId', 'nflAthleteId', 'collegeId', 'collegeTeam',
       'collegeConference', 'nflTeamId', 'nflTeam', 'year', 'overall', 'round',
       'pick', 'name', 'position', 'height', 'weight', 'preDraftRanking',
       'preDraftPositionRanking', 'preDraftGrade', 'hometownInfo_city',
       'hometownInfo_state']

# Filter DataFrame to only include rows with the retained features
all_draft_filtered = all_draft[draft_retain_features]
print(f"Features Removed: {set(all_draft.columns) - set(all_draft_filtered.columns)}")

Features Removed: {'hometownInfo_countyFips', 'hometownInfo_longitude', 'hometownInfo_latitude', 'hometownInfo_country'}

## Player Level Aggregation

### Pivot Player Stats

In [10]:
all_stats_filtered.info()

<class 'pandas.DataFrame'>
Index: 116555 entries, 7 to 276920
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   season      116555 non-null  int64
 1   playerId    116555 non-null  str
 2   player      116555 non-null  str
 3   position    116555 non-null  str
 4   team        116555 non-null  str
 5   conference  116555 non-null  str
 6   category    116555 non-null  str
 7   statType    116555 non-null  str
 8   stat        116555 non-null  str
dtypes: int64(1), str(8)
memory usage: 14.9 MB

In [11]:
all_stats_filtered_pivot = all_stats_filtered.pivot(index=['season','playerId','player','position','team','conference','category'], columns='statType', values='stat').reset_index()
all_stats_filtered_pivot.head()

statType,season,playerId,player,position,team,conference,category,ATT,CAR,COMPLETIONS,...,PCT,PTS,REC,TD,XPA,XPM,YDS,YPA,YPC,YPR
0,2024,102597,Will Rogers,QB,Washington,Big Ten,fumbles,NaN,NaN,NaN,...,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024,102597,Will Rogers,QB,Washington,Big Ten,passing,311,NaN,220,...,0.707,NaN,NaN,14,NaN,NaN,2458,7.9,NaN,NaN
2,2024,102597,Will Rogers,QB,Washington,Big Ten,rushing,NaN,34,NaN,...,NaN,NaN,NaN,0,NaN,NaN,-79,NaN,-2.3,NaN
3,2024,107494,Trey Sanders,RB,TCU,Big 12,fumbles,NaN,NaN,NaN,...,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024,107494,Trey Sanders,RB,TCU,Big 12,rushing,NaN,13,NaN,...,NaN,NaN,NaN,0,NaN,NaN,46,NaN,3.5,NaN