In [118]:
from dotenv import load_dotenv
import os
import requests
import json
import pandas as pd
import nflreadpy as nfl
import altair as alt

In [93]:
# adjust pandas display options to show all columns and rows
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)

In [94]:
def client_cxn():
    """
    Establish a client connection to API-Sports
    """
    load_dotenv()
    api_key = os.getenv('api_key')

    hostname = 'https://v1.american-football.api-sports.io'

    # create expected headers
    headers = {
        'x-apisports-key': api_key
    }

In [95]:
# load the api secret
load_dotenv()
api_key = os.getenv('api_key')

hostname = 'https://v1.american-football.api-sports.io'

# create expected headers
headers = {
    'x-apisports-key': api_key
}

# Explore the NFL API

### Explore players endpoint
/players <br>
docs: https://api-sports.io/documentation/nfl/v1#tag/Players/operation/get-players

In [96]:
def get_players_data():
    """
    """
    pass

In [97]:
players_url = f'{hostname}/players'
player_params = {
    'id': 1
}

resp = requests.get(
    url=players_url,
    headers=headers,
    params=player_params
)

In [98]:
resp.json()

{'get': 'players',
 'parameters': {'id': '1'},
 'errors': [],
 'results': 1,
 'response': [{'id': 1,
   'name': 'Derek Carr',
   'age': 33,
   'height': '6\' 3"',
   'weight': '215 lbs',
   'college': 'Fresno State',
   'group': 'Offense',
   'position': 'QB',
   'number': 4,
   'salary': None,
   'experience': 11,
   'image': 'https://media.api-sports.io/american-football/players/1.png'}]}

### Explore the statistics API
/players/statistics <br>
docs: https://api-sports.io/documentation/nfl/v1#tag/Players/operation/get-players

In [99]:
players_stats_url = f'{hostname}/players/statistics'
player_stats_params = {
    'id': 1,
    'season':'2024'
}

resp = requests.get(
    url=players_stats_url,
    headers=headers,
    params=player_stats_params
)

In [100]:
resp.json()

{'get': 'players/statistics',
 'parameters': {'id': '1', 'season': '2024'},
 'errors': [],
 'results': 1,
 'response': [{'player': {'id': 1,
    'name': 'Derek Carr',
    'image': 'https://media.api-sports.io/american-football/players/1.png'},
   'teams': [{'team': {'id': 1,
      'name': 'Las Vegas Raiders',
      'logo': 'https://media.api-sports.io/american-football/teams/1.png'},
     'groups': [{'name': 'Passing',
       'statistics': [{'name': 'passing attempts', 'value': '502'},
        {'name': 'completions', 'value': '305'},
        {'name': 'completion pct', 'value': '60.8'},
        {'name': 'yards', 'value': '3,522'},
        {'name': 'yards per pass avg', 'value': '7.0'},
        {'name': 'yards per game', 'value': '234.8'},
        {'name': 'longest pass', 'value': '60'},
        {'name': 'passing touchdowns', 'value': '24'},
        {'name': 'passing touchdowns pct', 'value': None},
        {'name': 'interceptions', 'value': '14'},
        {'name': 'interceptions pct', 'value': None},
        {'name': 'sacks', 'value': '27'},
        {'name': 'sacked yards lost', 'value': '191'},
        {'name': 'quaterback rating', 'value': '86.3'}]},
      {'name': 'Rushing',
       'statistics': [{'name': 'rushing attempts', 'value': '24'},
        {'name': 'yards', 'value': '102'},
        {'name': 'yards per rush avg', 'value': '4.3'},
        {'name': 'longest rush', 'value': '20'},
        {'name': 'over 20 yards', 'value': '1'},
        {'name': 'rushing touchdowns', 'value': '0'},
        {'name': 'yards per game', 'value': '6.8'},
        {'name': 'fumbles', 'value': '1'},
        {'name': 'fumbles lost', 'value': '0'},
        {'name': 'rushing first downs', 'value': '10'}]}]},
    {'team': {'id': 27,
      'name': 'New Orleans Saints',
      'logo': 'https://media.api-sports.io/american-football/teams/27.png'},
     'groups': [{'name': 'Passing',
       'statistics': [{'name': 'passing attempts', 'value': '279'},
        {'name': 'completions', 'value': '189'},
        {'name': 'completion pct', 'value': '67.7'},
        {'name': 'yards', 'value': '2,145'},
        {'name': 'yards per pass avg', 'value': '7.7'},
        {'name': 'yards per game', 'value': '214.5'},
        {'name': 'longest pass', 'value': '71'},
        {'name': 'passing touchdowns', 'value': '15'},
        {'name': 'passing touchdowns pct', 'value': None},
        {'name': 'interceptions', 'value': '5'},
        {'name': 'interceptions pct', 'value': None},
        {'name': 'sacks', 'value': '8'},
        {'name': 'sacked yards lost', 'value': '48'},
        {'name': 'quaterback rating', 'value': '101.0'}]},
      {'name': 'Rushing',
       'statistics': [{'name': 'rushing attempts', 'value': '17'},
        {'name': 'yards', 'value': '71'},
        {'name': 'yards per rush avg', 'value': '4.2'},
        {'name': 'longest rush', 'value': '13'},
        {'name': 'over 20 yards', 'value': '0'},
        {'name': 'rushing touchdowns', 'value': '1'},
        {'name': 'yards per game', 'value': '7.1'},
        {'name': 'fumbles', 'value': '1'},
        {'name': 'fumbles lost', 'value': '0'},
        {'name': 'rushing first downs', 'value': '4'}]},
      {'name': 'Scoring',
       'statistics': [{'name': 'rushing touchdowns', 'value': '1'},
        {'name': 'receiving touchdowns', 'value': '0'},
        {'name': 'return touchdowns', 'value': '0'},
        {'name': 'total touchdowns', 'value': '1'},
        {'name': 'field goals', 'value': '0'},
        {'name': 'extra points', 'value': '0'},
        {'name': 'two point conversions', 'value': '0'},
        {'name': 'total points', 'value': '6'},
        {'name': 'total points per game', 'value': '0.6'}]}]}]}]}

In [101]:
# get length of player statistics output for estimation
player_stats_data = resp.json()

groups = player_stats_data['response'][0]['teams'][0]['groups']

passing_stats = groups[0]['statistics']
rushing_stats = groups[1]['statistics']

len(passing_stats), len(rushing_stats)

(14, 10)

# Explore Sleeper API for Fantasy Football Points

### Fetch all Players
/players/nfl<br>
params: position <br>
docs: https://docs.sleeper.com/#fetch-all-players

In [102]:
sleeper_hostname = 'https://api.sleeper.app/v1/'
routes = 'players/nfl'

# players url
players_url = f'{sleeper_hostname}{routes}'

params = {
    'position': 'QB'
}

players_responses = requests.get(
    url=players_url,
    params=params
)

In [103]:
players_responses.json()

{'13175': {'birth_country': None,
  'news_updated': None,
  'high_school': 'Jackson Academy (MS)',
  'rotowire_id': None,
  'injury_notes': None,
  'active': True,
  'first_name': 'Kinkead',
  'age': 25,
  'practice_description': None,
  'weight': '215',
  'injury_body_part': None,
  'status': 'Inactive',
  'team': None,
  'player_id': '13175',
  'birth_city': None,
  'birth_date': '2000-07-27',
  'team_abbr': None,
  'years_exp': 0,
  'gsis_id': None,
  'number': None,
  'depth_chart_order': None,
  'injury_status': None,
  'fantasy_positions': ['QB'],
  'search_last_name': 'dent',
  'pandascore_id': None,
  'injury_start_date': None,
  'birth_state': None,
  'sportradar_id': 'b1b21920-2b81-11f0-a7dc-b36f60eb4d60',
  'kalshi_id': None,
  'practice_participation': None,
  'competitions': [],
  'college': 'Tennessee-Martin',
  'sport': 'nfl',
  'search_full_name': 'kinkeaddent',
  'opta_id': None,
  'position': 'QB',
  'espn_id': None,
  'team_changed_at': None,
  'metadata': {'channel_id': '1225943136610562048', 'rookie_year': '0'},
  'stats_id': None,
  'oddsjam_id': None,
  'hashtag': '#kinkeaddent-NFL-FA',
  'yahoo_id': None,
  'last_name': 'Dent',
  'swish_id': None,
  'height': '76',
  'rotoworld_id': None,
  'depth_chart_position': None,
  'full_name': 'Kinkead Dent',
  'player_shard': '1',
  'search_first_name': 'kinkead',
  'search_rank': 9999999,
  'fantasy_data_id': None},
 '13221': {'birth_country': None,
  'news_updated': 1754250907948,
  'high_school': 'Christian Brothers College (MO)',
  'rotowire_id': 19192,
  'injury_notes': None,
  'active': True,
  'first_name': 'Brett',
  'age': 25,
  'practice_description': None,
  'weight': '206',
  'injury_body_part': None,
  'status': 'Active',
  'team': None,
  'player_id': '13221',
  'birth_city': None,
  'birth_date': '2000-08-04',
  'team_abbr': None,
  'years_exp': 0,
  'gsis_id': None,
  'number': None,
  'depth_chart_order': None,
  'injury_status': None,
  'fantasy_positions': ['QB'],
  'search_last_name': 'gabbert',
  'pandascore_id': None,
  'injury_start_date': None,
  'birth_state': None,
  'sportradar_id': '08f0fef0-3748-11f0-9677-41d005293433',
  'kalshi_id': 'b78d326c-47b1-4197-bfba-8e3c393cbd39',
  'practice_participation': None,
  'competitions': [],
  'college': 'Miami (OH)',
  'sport': 'nfl',
  'search_full_name': 'brettgabbert',
  'opta_id': None,
  'position': 'QB',
  'espn_id': None,
  'team_changed_at': None,
  'metadata': {'channel_id': '1231394003711180800', 'rookie_year': '0'},
  'stats_id': None,
  'oddsjam_id': '0D57BED3D0B2DB99',
  'hashtag': '#brettgabbert-NFL-FA',
  'yahoo_id': None,
  'last_name': 'Gabbert',
  'swish_id': None,
  'height': '72',
  'rotoworld_id': None,
  'depth_chart_position': None,
  'full_name': 'Brett Gabbert',
  'player_shard': '5',
  'search_first_name': 'brett',
  'search_rank': 999,
  'fantasy_data_id': None},
 '1907': {'birth_country': None,
  'news_updated': 1552834853016,
  'high_school': 'Tivy (TX)',
  'rotowire_id': 9246,
  'injury_notes': None,
  'active': False,
  'first_name': 'Johnny',
  'age': 27,
  'practice_description': None,
  'weight': '210',
  'injury_body_part': None,
  'status': 'Inactive',
  'team': None,
  'player_id': '1907',
  'birth_city': None,
  'birth_date': '1992-12-06',
  'team_abbr': None,
  'years_exp': 6,
  'gsis_id': None,
  'number': 2,
  'depth_chart_order': None,
  'injury_status': None,
  'fantasy_positions': ['QB'],
  'search_last_name': 'manziel',
  'pandascore_id': None,
  'injury_start_date': None,
  'birth_state': None,
  'sportradar_id': '7ebbfdef-1185-4896-a323-e6d5669a8345',
  'kalshi_id': None,
  'practice_participation': None,
  'competitions': [],
  'college': 'Texas A&M',
  'sport': 'nfl',
  'search_full_name': 'johnnymanziel',
  'opta_id': None,
  'position': 'QB',
  'espn_id': 16736,
  'team_changed_at': None,
  'metadata': None,
  'stats_id': 593578,
  'oddsjam_id': None,
  'hashtag': '#johnnymanziel-NFL-FA-2',
  'yahoo_id': 27550,
  'last_name': 'Manziel',
  'swish_id': None,
  'height': '6\'0"',
  'rotoworld_id': 9271,
  'depth_chart_position': None,
  'full_name': 'Johnny Manziel',
  'player_shard': '6',
  'search_first_name': 'johnny',
  'search_rank': 9999999,
  'fantasy_data_id': 16135},
 '13295': {'birth_country': None,
  'news_updated': 1789922155923,
  'high_school': 'Eastland (TX)',
  'rotowire_id': 19293,
  'injury_notes': None,
  'active': True,
  'first_name': 'Behren',
  'age': 24,
  'practice_description': None,
  'weight': '218',
  'injury_body_part': None,
  'status': 'Active',
  'team': 'NE',
  'player_id': '13295',
  'birth_city': None,
  'birth_date': '2002-01-17',
  'team_abbr': None,
  'years_exp': 0,
  'gsis_id': None,
  'number': 15,
  'depth_chart_order': 3,
  'injury_status': None,
  'fantasy_positions': ['QB'],
  'search_last_name': 'morton',
  'pandascore_id': None,
  'injury_start_date': None,
  'birth_state': None,
  'sportradar_id': '0fe9c501-799c-45f7-a48f-2b4d9d6e9452',
  'kalshi_id': '009e8842-3fe1-41ad-8fb6-422de0463220',
  'practice_participation': None,
  'competitions': [],
  'college': 'Texas Tech',
  'sport': 'nfl',
  'search_full_name': 'behrenmorton',
  'opta_id': None,
  'position': 'QB',
  'espn_id': None,
  'team_changed_at': None,
  'metadata': {'channel_id': '1353911393161588736',
   'genius_id': '1505193',
   'rookie_year': '2026',
   'source_id': '85fd5db1-16a4-472a-b65e-3d0b51b41ae8'},
  'stats_id': None,
  'oddsjam_id': None,
  'hashtag': '#behrenmorton-NFL-NE-15',
  'yahoo_id': None,
  'last_name': 'Morton',
  'swish_id': None,
  'height': '74',
  'rotoworld_id': None,
  'depth_chart_position': 'QB',
  'full_name': 'Behren Morton',
  'player_shard': '6',
  'search_first_name': 'behren',
  'search_rank': 574,
  'fantasy_data_id': 28049},
 '1895': {'birth_country': None,
  'news_updated': 1707938117372,
  'high_school': "St. Paul's Episcopal (AL)",
  'rotowire_id': 9319,
  'injury_notes': None,
  'active': True,
  'first_name': 'AJ',
  'age': 33,
  'practice_description': None,
  'weight': '220',
  'injury_body_part': None,
  'status': 'Active',
  'team': None,
  'player_id': '1895',
  'birth_city': None,
  'birth_date': '1990-09-13',
  'team_abbr': None,
  'years_exp': 10,
  'gsis_id': '00-0031288',
  'number': 4,
  'depth_chart_order': None,
  'injury_status': None,
  'fantasy_positions': ['QB'],
  'search_last_name': 'mccarron',
  'pandascore_id': None,
  'injury_start_date': None,
  'birth_state': None,
  'sportradar_id': 'd4b30988-e8c5-4689-8037-f79a0d3c2774',
  'kalshi_id': None,
  'practice_participation': None,
  'competitions': [],
  'college': 'Alabama',
  'sport': 'nfl',
  'search_full_name': 'ajmccarron',
  'opta_id': None,
  'position': 'QB',
  'espn_id': 16810,
  'team_changed_at': None,
  'metadata': {'channel_id': '1116852767063801856', 'rookie_year': '2014'},
  'stats_id': 508649,
  'oddsjam_id': '2515F6F4347B',
  'hashtag': '#ajmccarron-NFL-FA-4',
  'yahoo_id': 27692,
  'last_name': 'McCarron',
  'swish_id': 508649,
  'height': '75',
  'rotoworld_id': 9290,
  'depth_chart_position': None,
  'full_name': 'AJ McCarron',
  'player_shard': '2',
  'search_first_name': 'aj',
  'search_rank': 311,
  'fantasy_data_id': 16116},
 '5845': {'birth_country': None,
  'news_updated': 1649518240714,
  'high_school': 'Bullis School (NJ)',
  'rotowire_id': 13558,
  'injury_notes': None,
  'active': False,
  'first_name': 'Dwayne',
  'age': 24,
  'practice_description': None,
  'weight': '230',
  'injury_body_part': None,
  'status': 'Active',
  'team': 'PIT',
  'player_id': '5845',
  'birth_city': None,
  'birth_date': '1997-05-03',
  'team_abbr': None,
  'years_exp': 3,
  'gsis_id': ' 00-0035232',
  'number': 3,
  'depth_chart_order': None,
  'injury_status': None,
  'fantasy_positions': ['QB'],
  'search_last_name': 'haskins',
  'pandascore_id': None,
  'injury_start_date': None,
  'birth_state': None,
  'sportradar_id': '6e4eda90-2656-434f-a262-4e5e9fde3946',
  'kalshi_id': None,
  'practice_participation': None,
  'competitions': [],
  'college': 'Ohio State',
  'sport': 'nfl',
  'search_full_name': 'dwaynehaskins',
  'opta_id': None,
  'position': 'QB',
  'espn_id': 4040616,
  'team_changed_at': None,
  'metadata': {'override_active': 'false'},
  'stats_id': 946582,
  'oddsjam_id': None,
  'hashtag': '#dwaynehaskins-NFL-PIT-3',
  'yahoo_id': 31847,
  'last_name': 'Haskins',
  'swish_id': 946582,
  'height': '76',
  'rotoworld_id': 13979,
  'depth_chart_position': None,
  'full_name': 'Dwayne Haskins',
  'player_shard': '5',
  'search_first_name': 'dwayne',
  'search_rank': 602,
  'fantasy_data_id': 20795},
 '19': {'birth_country': None,
  'news_updated': 1781961641331,
  'high_school': 'Audubon (NJ)',
  'rotowire_id': 5648,
  'injury_notes': None,
  'active': True,
  'first_name': 'Joe',
  'age': 41,
  'practice_description': None,
  'weight': '245',
  'injury_body_part': None,
  'status': 'Active',
  'team': 'CIN',
  'player_id': '19',
  'birth_city': None,
  'birth_date': '1985-01-16',
  'team_abbr': None,
  'years_exp': 18,
  'gsis_id': '00-0026158',
  'number': 16,
  'depth_chart_order': 2,
  'injury_status': None,
  'fantasy_positions': ['QB'],
  'search_last_name': 'flacco',
  'pandascore_id': None,
  'injury_start_date': None,
  'birth_state': None,
  'sportradar_id': '64797df2-efd3-4b27-86ee-1d48f7edb09f',
  'kalshi_id': 'ecebcfd1-89cf-4279-a328-55136cafef82',
  'practice_participation': None,
  'competitions': [],
  'college': 'Delaware',
  'sport': 'nfl',
  'search_full_name': 'joeflacco',
  'opta_id': None,
  'position': 'QB',
  'espn_id': 11252,
  'team_changed_at': None,
  'metadata': {'channel_id': '1113708777586061312',
   'genius_id': '444180',
   'rookie_year': '2008'},
  'stats_id': 216342,
  'oddsjam_id': '9BD13F1CF846',
  'hashtag': '#joeflacco-NFL-CIN-16',
  'yahoo_id': 8795,
  'last_name': 'Flacco',
  'swish_id': 216342,
  'height': '78',
  'rotoworld_id': 4677,
  'depth_chart_position': 'QB',
  'full_name': 'Joe Flacco',
  'player_shard': '5',
  'search_first_name': 'joe',
  'search_rank': 490,
  'fantasy_data_id': 611},
 '1550': {'birth_country': None,
  'news_updated': 1711038060009,
  'high_school': 'Chaminade College Prep (CA)',
  'rotowire_id': 8923,
  'injury_notes': None,
  'active': True,
  'first_name': 'Ryan',
  'age': 33,
  'practice_description': None,
  'weight': '218',
  'injury_body_part': None,
  'status': 'Active',
  'team': None,
  'player_id': '1550',
  'birth_city': None,
  'birth_date': '1989-11-17',
  'team_abbr': None,
  'years_exp': 10,
  'gsis_id': '00-0029857',
  'number': 4,
  'depth_chart_order': None,
  'injury_status': None,
  'fantasy_positions': ['QB'],
  'search_last_name': 'griffin',
  'pandascore_id': None,
  'injury_start_date': None,
  'birth_state': None,
  'sportradar_id': '949c34b9-150a-4a1b-b884-1fcf1ebaabdf',
  'kalshi_id': None,
  'practice_participation': None,
  'competitions': [],
  'college': 'Tulane',
  'sport': 'nfl',
  'search_full_name': 'ryangriffin',
  'opta_id': None,
  'position': 'QB',
  'espn_id': 16140,
  'team_changed_at': None,
  'metadata': {'channel_id': '1116852745207283712'},
  'stats_id': 466883,
  'oddsjam_id': None,
  'hashtag': '#ryangriffin-NFL-FA-4',
  'yahoo_id': 26949,
  'last_name': 'Griffin',
  'swish_id': 466883,
  'height': '76',
  'rotoworld_id': 8507,
  'depth_chart_position': None,
  'full_name': 'Ryan Griffin',
  'player_shard': '3',
  'search_first_name': 'ryan',
  'search_rank': 292,
  'fantasy_data_id': 15190},
 '1': {'birth_country': None,
  'news_updated': None,
  'high_school': None,
  'rotowire_id': 8833,
  'injury_notes': None,
  'active': False,
  'first_name': 'GJ',
  'age': 28,
  'practice_description': None,
  'weight': '234',
  'injury_body_part': None,
  'status': 'Inactive',
  'team': None,
  'player_id': '1',
  'birth_city': None,
  'birth_date': '1988-12-01',
  'team_abbr': None,
  'years_exp': 1,
  'gsis_id': None,
  'number': 2,
  'depth_chart_order': None,
  'injury_status': None,
  'fantasy_positions': ['QB'],
  'search_last_name': 'kinne',
  'pandascore_id': None,
  'injury_start_date': None,
  'birth_state': None,
  'sportradar_id': 'a668bd7d-56e5-45ff-a2c8-d618cd1fef95',
  'kalshi_id': None,
  'practice_participation': None,
  'competitions': [],
  'college': 'Tulsa',
  'sport': 'nfl',
  'search_full_name': 'gjkinne',
  'opta_id': None,
  'position': 'QB',
  'espn_id': 15299,
  'team_changed_at': None,
  'metadata': None,
  'stats_id': 399453,
  'oddsjam_id': None,
  'hashtag': '#gjkinne-NFL-FA-2',
  'yahoo_id': 26154,
  'last_name': 'Kinne',
  'swish_id': None,
  'height': '6\'2"',
  'rotoworld_id': None,
  'depth_chart_position': None,
  'full_name': 'GJ Kinne',
  'player_shard': '7',
  'search_first_name': 'gj',
  'search_rank': 9999999,
  'fantasy_data_id': 18},
 '3953': {'birth_country': None,
  'news_updated': None,
  'high_school': None,
  'rotowire_id': 11679,
  'injury_notes': None,
  'active': False,
  'first_name': 'Austin',
  'age': None,
  'practice_description': None,
  'weight': '212',
  'injury_body_part': None,
  'status': 'Inactive',
  'team': None,
  'player_id': '3953',
  'birth_city': None,
  'birth_date': None,
  'team_abbr': None,
  'years_exp': 0,
  'gsis_id': None,
  'number': 9,
  'depth_chart_order': None,
  'injury_status': None,
  'fantasy_positions': ['QB'],
  'search_last_name': 'trainor',
  'pandascore_id': None,
  'injury_start_date': None,
  'birth_state': None,
  'sportradar_id': '',
  'kalshi_id': None,
  'practice_participation': None,
  'competitions': [],
  'college': 'West Georgia',
  'sport': 'nfl',
  'search_full_name': 'austintrainor',
  'opta_id': None,
  'position': 'QB',
  'espn_id': None,
  'team_changed_at': None,
  'metadata': None,
  'stats_id': 515272,
  'oddsjam_id': None,
  'hashtag': '#austintrainor-NFL-FA-9',
  'yahoo_id': 30080,
  'last_name': 'Trainor',
  'swish_id': None,
  'height': '6\'2"',
  'rotoworld_id': None,
  'depth_chart_position': None,
  'full_name': 'Austin Trainor',
  'player_shard': '0',
  'search_first_name': 'austin',
  'search_rank': 9999999,
  'fantasy_data_id': 18786},
 '404': {'birth_country': None,
  'news_updated': None,
  'high_school': None,
  'rotowire_id': None,
  'injury_notes': None,
  'active': False,
  'first_name': 'Jon',
  'age': 47,
  'practice_description': None,
  'weight': '219',
  'injury_body_part': None,
  'status': 'Inactive',
  'team': None,
  'player_id': '404',
  'birth_city': None,
  'birth_date': '1972-09-21',
  'team_abbr': None,
  'years_exp': 24,
  'gsis_id': None,
  'number': 3,
  'depth_chart_order': None,
  'injury_status': None,
  'fantasy_positions': ['QB'],
  'search_last_name': 'kitna',
  'pandascore_id': None,
  'injury_start_date': None,
  'birth_state': None,
  'sportradar_id': '',
  'kalshi_id': None,
  'practice_participation': None,
  'competitions': [],
  'college': 'Central Washington',
  'sport': 'nfl',
  'search_full_name': 'jonkitna',
  'opta_id': None,
  'position': 'QB',
  'espn_id': None,
  'team_changed_at': None,
  'metadata': None,
  'stats_id': None,
  'oddsjam_id': None,
  'hashtag': '#jonkitna-NFL-FA-3',
  'yahoo_id': None,
  'last_name': 'Kitna',
  'swish_id': None,
  'height': '6\'2"',
  'rotoworld_id': 28,
  'depth_chart_position': None,
  'full_name': 'Jon Kitna',
  'player_shard': '8',
  'search_first_name': 'jon',
  'search_rank': 9999999,
  'fantasy_data_id': 8842},
 '698': {'birth_country': None,
  'news_updated': None,
  'high_school': 'Chattahoochee (GA)',
  'rotowire_id': 4825,
  'injury_notes': None,
  'active': False,
  'first_name': 'Charlie',
  'age': 38,
  'practice_description': None,
  'weight': '226',
  'injury_body_part': None,
  'status': 'Inactive',
  'team': None,
  'player_id': '698',
  'birth_city': None,
  'birth_date': '1982-08-06',
  'team_abbr': None,
  'years_exp': 14,
  'gsis_id': None,
  'number': 15,
  'depth_chart_order': None,
  'injury_status': None,
  'fantasy_positions': ['QB'],
  'search_last_name': 'whitehurst',
  'pandascore_id': None,
  'injury_start_date': None,
  'birth_state': None,
  'sportradar_id': '34cc7f47-9f14-4661-b9af-c9d3b2fc873a',
  'kalshi_id': None,
  'practice_participation': None,
  'competitions': [],
  'college': 'Clemson',
  'sport': 'nfl',
  'search_full_name': 'charliewhitehurst',
  'opta_id': None,
  'position': 'QB',
  'espn_id': 9667,
  'team_changed_at': None,
  'metadata': None,
  'stats_id': 156595,
  'oddsjam_id': None,
  'hashtag': '#charliewhitehurst-NFL-FA-15',
  'yahoo_id': 7830,
  'last_name': 'Whitehurst',
  'swish_id': None,
  'height': '6\'5"',
  'rotoworld_id': 3623,
  'depth_chart_position': None,
  'full_name': 'Charlie Whitehurst',
  'player_shard': '1',
  'search_first_name': 'charlie',
  'search_rank': 9999999,
  'fantasy_data_id': 12137},
 '7013': {'birth_country': None,
  'news_updated': 1671732612175,
  'high_school': 'Del Valle (TX)',
  'rotowire_id': 14393,
  'injury_notes': None,
  'active': True,
  'first_name': 'Steven',
  'age': 26,
  'practice_description': None,
  'weight': '230',
  'injury_body_part': None,
  'status': 'Active',
  'team': None,
  'player_id': '7013',
  'birth_city': None,
  'birth_date': '1997-01-14',
  'team_abbr': None,
  'years_exp': 3,
  'gsis_id': None,
  'number': 12,
  'depth_chart_order': None,
  'injury_status': None,
  'fantasy_positions': ['QB'],
  'search_last_name': 'montez',
  'pandascore_id': None,
  'injury_start_date': None,
  'birth_state': None,
  'sportradar_id': 'd446443f-130c-4bce-a300-a15cf66f27f1',
  'kalshi_id': None,
  'practice_participation': None,
  'competitions': [],
  'college': 'Colorado',
  'sport': 'nfl',
  'search_full_name': 'stevenmontez',
  'opta_id': None,
  'position': 'QB',
  'espn_id': 3915436,
  'team_changed_at': None,
  'metadata': {'channel_id': '1116853323299815424'},
  'stats_id': None,
  'oddsjam_id': None,
  'hashtag': '#stevenmontez-NFL-FA-12',
  'yahoo_id': 33207,
  'last_name': 'Montez',
  'swish_id': 882704,
  'height': '77',
  'rotoworld_id': None,
  'depth_chart_position': None,
  'full_name': 'Steven Montez',
  'player_shard': '9',
  'search_first_name': 'steven',
  'search_rank': 9999999,
  'fantasy_data_id': 21809},
 '10233': {'birth_country': None,
  'news_updated': 1724099748571,
  'high_school': 'Lewis Central (IA)',
  'rotowire_id': 16729,
  'injury_notes': None,
  'active': True,
  'first_name': 'Max',
  'age': 23,
  'practice_description': None,
  'weight': '207',
  'injury_body_part': None,
  'status': 'Active',
  'team': None,
  'player_id': '10233',
  'birth_city': None,
  'birth_date': '2001-03-12',
  'team_abbr': None,
  'years_exp': 1,
  'gsis_id': None,
  'number': 8,
  'depth_chart_order': None,
  'injury_status': None,
  'fantasy_positions': ['QB'],
  'search_last_name': 'duggan',
  'pandascore_id': None,
  'injury_start_date': None,
  'birth_state': None,
  'sportradar_id': 'a7ef9eec-dab5-4321-a836-af3d085b4ba4',
  'kalshi_id': None,
  'practice_participation': None,
  'competitions': [],
  'college': 'TCU',
  'sport': 'nfl',
  'search_full_name': 'maxduggan',
  'opta_id': None,
  'position': 'QB',
  'espn_id': None,
  'team_changed_at': None,
  'metadata': {'channel_id': '1113708692546547712', 'rookie_year': '2023'},
  'stats_id': None,
  'oddsjam_id': '8174F14224A5',
  'hashtag': '#maxduggan-NFL-FA-8',
  'yahoo_id': None,
  'last_name': 'Duggan',
  'swish_id': 1162793,
  'height': '73',
  'rotoworld_id': None,
  'depth_chart_position': None,
  'full_name': 'Max Duggan',
  'player_shard': '9',
  'search_first_name': 'max',
  'search_rank': 552,
  'fantasy_data_id': None},
 '881': {'birth_country': None,
  'news_updated': None,
  'high_school': None,
  'rotowire_id': None,
  'injury_notes': None,
  'active': False,
  'first_name': 'Ricky',
  'age': 30,
  'practice_description': None,
  'weight': '228',
  'injury_body_part': None,
  'status': 'Inactive',
  'team': None,
  'player_id': '881',
  'birth_city': None,
  'birth_date': '1987-09-03',
  'team_abbr': None,
  'years_exp': 5,
  'gsis_id': None,
  'number': 2,
  'depth_chart_order': None,

In [104]:
players = players_responses.json()

for player_id, player in players.items():
    # look for Derek Carr
    if player['first_name']=='Derek' and player['last_name']=='Carr':
        print(json.dumps(player, indent=4))

{
    "birth_country": null,
    "news_updated": 1786466440581,
    "high_school": "Bakersfield Christian (CA)",
    "rotowire_id": 9317,
    "injury_notes": null,
    "active": true,
    "first_name": "Derek",
    "age": 34,
    "practice_description": null,
    "weight": "215",
    "injury_body_part": "Personal",
    "status": "Active",
    "team": null,
    "player_id": "2028",
    "birth_city": null,
    "birth_date": "1991-03-28",
    "team_abbr": null,
    "years_exp": 11,
    "gsis_id": "00-0031280",
    "number": 4,
    "depth_chart_order": null,
    "injury_status": "NA",
    "fantasy_positions": [
        "QB"
    ],
    "search_last_name": "carr",
    "pandascore_id": null,
    "injury_start_date": null,
    "birth_state": null,
    "sportradar_id": "9f026fc0-4449-4dc5-a226-2e2830619381",
    "kalshi_id": null,
    "practice_participation": null,
    "competitions": [],
    "college": "Fresno State",
    "sport": "nfl",
    "search_full_name": "derekcarr",
    "opta_id": null,
    "position": "QB",
    "espn_id": 16757,
    "team_changed_at": null,
    "metadata": {
        "channel_id": "1113708686318006272",
        "injury_override_regular_2024_6": "Out",
        "rookie_year": "2014"
    },
    "stats_id": 496083,
    "oddsjam_id": "C12F49D17453",
    "hashtag": "#derekcarr-NFL-FA-4",
    "yahoo_id": 27564,
    "last_name": "Carr",
    "swish_id": 496083,
    "height": "75",
    "rotoworld_id": 9349,
    "depth_chart_position": null,
    "full_name": "Derek Carr",
    "player_shard": "4",
    "search_first_name": "derek",
    "search_rank": 201,
    "fantasy_data_id": 16311
}

In [105]:
### Derek Carr Output:
"""
{
    "opta_id": null,
    "rotoworld_id": 9349,
    "birth_country": null,
    "espn_id": 16757,
    "gsis_id": "00-0031280",
    "injury_body_part": "Personal",
    "search_rank": 201,
    "kalshi_id": null,
    "metadata": {
        "channel_id": "1113708686318006272",
        "injury_override_regular_2024_6": "Out",
        "rookie_year": "2014"
    },
    "fantasy_positions": [
        "QB"
    ],
    "active": true,
    "oddsjam_id": "C12F49D17453",
    "news_updated": 1786466440581,
    "hashtag": "#derekcarr-NFL-FA-4",
    "fantasy_data_id": 16311,
    "weight": "215",
    "sport": "nfl",
    "injury_notes": null,
    "competitions": [],
    "practice_participation": null,
    "last_name": "Carr",
    "injury_status": "NA",
    "status": "Active",
    "team": null,
    "first_name": "Derek",
    "college": "Fresno State",
    "years_exp": 11,
    "pandascore_id": null,
    "team_abbr": null,
    "injury_start_date": null,
    "search_full_name": "derekcarr",
    "age": 34,
    "depth_chart_position": null,
    "high_school": "Bakersfield Christian (CA)",
    "sportradar_id": "9f026fc0-4449-4dc5-a226-2e2830619381",
    "birth_city": null,
    "number": 4,
    "player_id": "2028",
    "team_changed_at": null,
    "rotowire_id": 9317,
    "search_last_name": "carr",
    "player_shard": "4",
    "birth_date": "1991-03-28",
    "stats_id": 496083,
    "depth_chart_order": null,
    "birth_state": null,
    "full_name": "Derek Carr",
    "search_first_name": "derek",
    "position": "QB",
    "practice_description": null,
    "height": "75",
    "swish_id": 496083,
    "yahoo_id": 27564
}

"""

'\n{\n    "opta_id": null,\n    "rotoworld_id": 9349,\n    "birth_country": null,\n    "espn_id": 16757,\n    "gsis_id": "00-0031280",\n    "injury_body_part": "Personal",\n    "search_rank": 201,\n    "kalshi_id": null,\n    "metadata": {\n        "channel_id": "1113708686318006272",\n        "injury_override_regular_2024_6": "Out",\n        "rookie_year": "2014"\n    },\n    "fantasy_positions": [\n        "QB"\n    ],\n    "active": true,\n    "oddsjam_id": "C12F49D17453",\n    "news_updated": 1786466440581,\n    "hashtag": "#derekcarr-NFL-FA-4",\n    "fantasy_data_id": 16311,\n    "weight": "215",\n    "sport": "nfl",\n    "injury_notes": null,\n    "competitions": [],\n    "practice_participation": null,\n    "last_name": "Carr",\n    "injury_status": "NA",\n    "status": "Active",\n    "team": null,\n    "first_name": "Derek",\n    "college": "Fresno State",\n    "years_exp": 11,\n    "pandascore_id": null,\n    "team_abbr": null,\n    "injury_start_date": null,\n    "search_full_name": "derekcarr",\n    "age": 34,\n    "depth_chart_position": null,\n    "high_school": "Bakersfield Christian (CA)",\n    "sportradar_id": "9f026fc0-4449-4dc5-a226-2e2830619381",\n    "birth_city": null,\n    "number": 4,\n    "player_id": "2028",\n    "team_changed_at": null,\n    "rotowire_id": 9317,\n    "search_last_name": "carr",\n    "player_shard": "4",\n    "birth_date": "1991-03-28",\n    "stats_id": 496083,\n    "depth_chart_order": null,\n    "birth_state": null,\n    "full_name": "Derek Carr",\n    "search_first_name": "derek",\n    "position": "QB",\n    "practice_description": null,\n    "height": "75",\n    "swish_id": 496083,\n    "yahoo_id": 27564\n}\n\n'

# nflreadpy
docs: https://github.com/nflverse/nflreadpy <br>

In [106]:
import nflreadpy as nfl

# Load current season play-by-play data
pbp = nfl.load_pbp()

# Load player game-level stats for multiple seasons
player_stats = nfl.load_player_stats([2023])

# Load all available team level stats
team_stats = nfl.load_team_stats(seasons=True)

# nflreadpy uses Polars instead of pandas. Convert to pandas if needed:
pbp_pandas = pbp.to_pandas(use_pyarrow_extension_array=True)

In [107]:
player_stats

shape: (18_643, 150)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ player_id ┆ player_na ┆ player_di ┆ position ┆ … ┆ pt_return ┆ pt_net_ya ┆ fantasy_p ┆ fantasy_p │
│ ---       ┆ me        ┆ splay_nam ┆ ---      ┆   ┆ _tds      ┆ rds       ┆ oints     ┆ oints_ppr │
│ str       ┆ ---       ┆ e         ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ str       ┆ ---       ┆          ┆   ┆ i32       ┆ i32       ┆ f64       ┆ f64       │
│           ┆           ┆ str       ┆          ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 00-002345 ┆ A.Rodgers ┆ Aaron     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 9         ┆           ┆ Rodgers   ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002385 ┆ M.Prater  ┆ Matt      ┆ K        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 3         ┆           ┆ Prater    ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002556 ┆ N.Folk    ┆ Nick Folk ┆ K        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 5         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002619 ┆ C.Campbel ┆ Calais    ┆ DE       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 0         ┆ l         ┆ Campbell  ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002649 ┆ M.Staffor ┆ Matthew   ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 14.46     ┆ 14.46     │
│ 8         ┆ d         ┆ Stafford  ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 00-003864 ┆ B.Willis  ┆ Brayden   ┆ TE       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 3         ┆           ┆ Willis    ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003898 ┆ C.Conner  ┆ Chamarri  ┆ DB       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 2         ┆           ┆ Conner    ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003900 ┆ F.Anudike ┆ Felix Anu ┆ DE       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 6         ┆ -Uzomah   ┆ dike-Uzom ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ ah        ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003906 ┆ R.Rice    ┆ Rashee    ┆ WR       ┆ … ┆ 0         ┆ 0         ┆ 4.4       ┆ 10.4      │
│ 7         ┆           ┆ Rice      ┆          ┆   ┆           ┆           ┆           ┆           │
│ null      ┆ null      ┆ null      ┆ null     ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [108]:
pbp_pandas

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,side_of_field,yardline_100,game_date,quarter_seconds_remaining,half_seconds_remaining,game_seconds_remaining,game_half,quarter_end,drive,sp,qtr,down,goal_to_go,time,yrdln,ydstogo,ydsnet,desc,play_type,yards_gained,shotgun,no_huddle,qb_dropback,qb_kneel,qb_spike,qb_scramble,pass_length,pass_location,air_yards,yards_after_catch,run_location,run_gap,field_goal_result,kick_distance,extra_point_result,two_point_conv_result,home_timeouts_remaining,away_timeouts_remaining,timeout,timeout_team,td_team,td_player_name,td_player_id,posteam_timeouts_remaining,defteam_timeouts_remaining,total_home_score,total_away_score,posteam_score,defteam_score,score_differential,posteam_score_post,defteam_score_post,score_differential_post,no_score_prob,opp_fg_prob,opp_safety_prob,opp_td_prob,fg_prob,safety_prob,td_prob,extra_point_prob,two_point_conversion_prob,ep,epa,total_home_epa,total_away_epa,total_home_rush_epa,total_away_rush_epa,total_home_pass_epa,total_away_pass_epa,air_epa,yac_epa,comp_air_epa,comp_yac_epa,total_home_comp_air_epa,total_away_comp_air_epa,total_home_comp_yac_epa,total_away_comp_yac_epa,total_home_raw_air_epa,total_away_raw_air_epa,total_home_raw_yac_epa,total_away_raw_yac_epa,wp,def_wp,home_wp,away_wp,wpa,vegas_wpa,vegas_home_wpa,home_wp_post,away_wp_post,vegas_wp,vegas_home_wp,total_home_rush_wpa,total_away_rush_wpa,total_home_pass_wpa,total_away_pass_wpa,air_wpa,yac_wpa,comp_air_wpa,comp_yac_wpa,total_home_comp_air_wpa,total_away_comp_air_wpa,total_home_comp_yac_wpa,total_away_comp_yac_wpa,total_home_raw_air_wpa,total_away_raw_air_wpa,total_home_raw_yac_wpa,total_away_raw_yac_wpa,punt_blocked,first_down_rush,first_down_pass,first_down_penalty,third_down_converted,third_down_failed,fourth_down_converted,fourth_down_failed,incomplete_pass,touchback,interception,punt_inside_twenty,punt_in_endzone,punt_out_of_bounds,punt_downed,punt_fair_catch,kickoff_inside_twenty,kickoff_in_endzone,kickoff_out_of_bounds,kickoff_downed,kickoff_fair_catch,fumble_forced,fumble_not_forced,fumble_out_of_bounds,solo_tackle,safety,penalty,tackled_for_loss,fumble_lost,own_kickoff_recovery,own_kickoff_recovery_td,qb_hit,rush_attempt,pass_attempt,sack,touchdown,pass_touchdown,rush_touchdown,return_touchdown,extra_point_attempt,two_point_attempt,field_goal_attempt,kickoff_attempt,punt_attempt,fumble,complete_pass,assist_tackle,lateral_reception,lateral_rush,lateral_return,lateral_recovery,passer_player_id,passer_player_name,passing_yards,receiver_player_id,receiver_player_name,receiving_yards,rusher_player_id,rusher_player_name,rushing_yards,lateral_receiver_player_id,lateral_receiver_player_name,lateral_receiving_yards,lateral_rusher_player_id,lateral_rusher_player_name,lateral_rushing_yards,lateral_sack_player_id,lateral_sack_player_name,interception_player_id,interception_player_name,lateral_interception_player_id,lateral_interception_player_name,punt_returner_player_id,punt_returner_player_name,lateral_punt_returner_player_id,lateral_punt_returner_player_name,kickoff_returner_player_name,kickoff_returner_player_id,lateral_kickoff_returner_player_id,lateral_kickoff_returner_player_name,punter_player_id,punter_player_name,kicker_player_name,kicker_player_id,own_kickoff_recovery_player_id,own_kickoff_recovery_player_name,blocked_player_id,blocked_player_name,tackle_for_loss_1_player_id,tackle_for_loss_1_player_name,tackle_for_loss_2_player_id,tackle_for_loss_2_player_name,qb_hit_1_player_id,qb_hit_1_player_name,qb_hit_2_player_id,qb_hit_2_player_name,forced_fumble_player_1_team,forced_fumble_player_1_player_id,forced_fumble_player_1_player_name,forced_fumble_player_2_team,forced_fumble_player_2_player_id,forced_fumble_player_2_player_name,solo_tackle_1_team,solo_tackle_2_team,solo_tackle_1_player_id,solo_tackle_2_player_id,solo_tackle_1_player_name,solo_tackle_2_player_name,assist_tackle_1_player_id,assist_tackle_1_player_name,assist_tackle_1_team,assist_tackle_2_player_id,assist_tackle_2_player_name,assist_tackle_2_team,assist_tackle_3_player_id,assist_tackle_3_player_name,assist_tackle_3_team,assist_tackle_4_player_id,assist_tackle_4_player_name,assist_tackle_4_team,tackle_with_assist,tackle_with_assist_1_player_id,tackle_with_assist_1_player_name,tackle_with_assist_1_team,tackle_with_assist_2_player_id,tackle_with_assist_2_player_name,tackle_with_assist_2_team,pass_defense_1_player_id,pass_defense_1_player_name,pass_defense_2_player_id,pass_defense_2_player_name,fumbled_1_team,fumbled_1_player_id,fumbled_1_player_name,fumbled_2_player_id,fumbled_2_player_name,fumbled_2_team,fumble_recovery_1_team,fumble_recovery_1_yards,fumble_recovery_1_player_id,fumble_recovery_1_player_name,fumble_recovery_2_team,fumble_recovery_2_yards,fumble_recovery_2_player_id,fumble_recovery_2_player_name,sack_player_id,sack_player_name,half_sack_1_player_id,half_sack_1_player_name,half_sack_2_player_id,half_sack_2_player_name,return_team,return_yards,penalty_team,penalty_player_id,penalty_player_name,penalty_yards,replay_or_challenge,replay_or_challenge_result,penalty_type,defensive_two_point_attempt,defensive_two_point_conv,defensive_extra_point_attempt,defensive_extra_point_conv,safety_player_name,safety_player_id,season,cp,cpoe,series,series_success,series_result,order_sequence,start_time,time_of_day,stadium,weather,nfl_api_id,play_clock,play_deleted,play_type_nfl,special_teams_play,st_play_type,end_clock_time,end_yard_line,fixed_drive,fixed_drive_result,drive_real_start_time,drive_play_count,drive_time_of_possession,drive_first_downs,drive_inside20,drive_ended_with_score,drive_quarter_start,drive_quarter_end,drive_yards_penalized,drive_start_transition,drive_end_transition,drive_game_clock_start,drive_game_clock_end,drive_start_yard_line,drive_end_yard_line,drive_play_id_started,drive_play_id_ended,away_score,home_score,location,result,total,spread_line,total_line,div_game,roof,surface,temp,wind,home_coach,away_coach,stadium_id,game_stadium,aborted_play,success,passer,passer_jersey_number,rusher,rusher_jersey_number,receiver,receiver_jersey_number,pass,rush,first_down,special,play,passer_id,rusher_id,receiver_id,name,jersey_number,id,fantasy_player_name,fantasy_player_id,fantasy,fantasy_id,out_of_bounds,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe
0,1.0,2026_01_ARI_LAC,2026091308,LAC,ARI,REG,1,<NA>,<NA>,<NA>,<NA>,<NA>,2026-09-13,900.0,1800.0,3600.0,Half1,0.0,<NA>,0.0,1.0,<NA>,0.0,15:00,LAC 35,0.0,<NA>,GAME,<NA>,<NA>,0.0,0.0,<NA>,0.0,0.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.0,3.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.008251,-0.0,0.0,0.0,0.0,0.0,0.0,0.0,<NA>,<NA>,<NA>,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.433208,0.566792,0.566792,0.433208,-0.0,-0.0,0.0,<NA>,<NA>,0.230197,0.769803,0.0,0.0,0.0,0.0,<NA>,<NA>,<NA>,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2026,<NA>,<NA>,1.0,1.0,First down,1.0,"9/13/26, 16:25:43",<NA>,SoFi Stadium,"Sunny Temp: 78° F, Humidity: 70%, Wind: SW 6 mph",a9a87603-4feb-11f1-abca-2c54536568a9,0,0.0,GAME_START,0.0,<NA>,<NA>,<NA>,1.0,Touchdown,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,26,14,Home,-12,40,8.5,47.5,0,dome,matrixturf,<NA>,<NA>,Jim Harbaugh,Jonathan Gannon,LAX01,SoFi Stadium,0.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,0.0,<NA>,0.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,0.0,-0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,39.0,2026_01_ARI_LAC,2026091308,LAC,ARI,REG,1,ARI,away,LAC,LAC,35.0,2026-09-13,900.0,1800.0,3600.0,Half1,0.0,1.0,0.0,1.0,<NA>,0.0,15:00,LAC 35,0.0,70.0,11-C.Dicker kicks 60 yards from LAC 35 to ARI ...,kickoff,0.0,0.0,0.0,0.0,0.0,0.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,60.0,<NA>,<NA>,3.0,3.0,0.0,<NA>,<NA>,<NA>,<NA>,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.003473,0.128879,0.00227,0.272088,0.208195,0.00324,0.381854,0.0,0.0,1.008251,0.291195,-0.291195,0.291195,0.0,0.0,0.0,0.0,<NA>,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.433208,0.566792,0.566792,0.433208,0.000338,-0.008101,0.008101,0.566454,0.433546,0.230197,0.769803,0.0,0.0,0.0,0.0,<NA>,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,D.Duvernay,00-0036331,<NA>,<NA>,<NA>,<NA>,C.Dicker,00-0037224,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,LAC,<NA>,00-0032146,<NA>,B.Dupree,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,ARI,25.0,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,0.0,0.0,0.0,0.0,<NA>,<NA>,2026,<NA>,<NA>,1.0,1.0,First down,39.0,"9/13/26, 16:25:43",2026-09-13T20:25:43.600Z,SoFi Stadium,"Sunny Temp: 78° F, Humidity: 70%, Wind: SW 6 mph",a9a87603-4feb-11f1-abca-2c54536568a9,0,0.0,KICK_OFF,1.0,<NA>,2026-09-13T20:25:51.047Z,<NA>,1.0,Touchdown,2026-09-13T20:25:43.600Z,11.0,6:11,5.0,1.0,1.0,1.0,1.0,0.0,KICKOFF,TOUCHDOWN,15:00,08:49,ARI 30,LAC 5,39.0,319.0,26,14,Home,-12,40,8.5,47.5,0,dome,matrixturf,<NA>,<NA>,Jim Harbaugh,Jonathan Gannon,LAX01,SoFi Stadium,0.0,1.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,0.0,0.0,1.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,0.0,0.291195,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,62.0,2026_01_ARI_LAC,2026091308,LAC,ARI,REG,1,ARI,away,LAC,ARI,70.0,2026-09-13,896.0,1796.0,3596.0,Half1,0.0,1.0,0.0,1.0,1.0,0.0,14:56,ARI 30,10.0,70.0,(14:56) 7-J.Brissett pass deep right to 85-T.M...,pass,27.0,0.0,0.0,1.0,0.0,0.0,0.0,deep,right,22.0,5.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.0,3.0,0.0,<NA>,<NA>,<NA>,<NA>,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00343,0.12719,0.002265,0.251641,0.211198,0.0033,0.400977,0.0,0.0,1.299446,1.730269,-2.021464,2.021464,0.0,0.0,-1.730269,1.730269,1.463163,0.267106,1.463163,0.267106,-1.463163,1.463163,-0.267106,0.267106,-1.463163,1.463163,-0.267106,0.267106,0.433546,0.566454,0.566454,0.433546,0.046572,0.01106,-0.01106,0.519882,0.480118,0.222096,0.777904,0.0,0.0,-0.046572,0.046572,0.0,0.046572,0.0,0.046572,0.0,0.0,-0.046572,0.046572,0.0,0.0,-0.046572,0.046572,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,00-0033119,J.Brissett,27.0,00-0037744,T.McBride,27.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,LAC,<NA>,00-0036992,<NA>,E.Molden,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,0.0,0.0,0.0,0.0,<NA>,<NA>,2026,0.521105,47.889549,1.0,1.0,First down,62.0,"9/13/26, 16:25:43",2026-09-13T20:26:27.237Z,SoFi Stadium,"Sunny Temp: 78° F, Humidity: 70%, Wind: SW 6 mph",a9a87603-4feb-11f1-abca-2c54536568a9,0,0.0,PASS,0.0,<NA>,2026-09-13T20:26:32.260Z,<NA>,1.0,Touchdown,2026-09-13T20:25:43.600Z,11.0,6:11,5.0,1.0,1.0,1.0,1.0,0.0,KICKOFF,TOUCHDOWN,15:00,08:49,ARI 30,LAC 5,39.0,319.0,26,14,Home,-12,40,8.5,47.5,0,dome,matrixturf,<NA>,<NA>,Jim Harbaugh,Jonathan Gannon,LAX01,SoFi Stadium,0.0,1.0,J.Brissett,7,<NA>,<NA>,T.McBride,85,1.0,0.0,1.0,0.0,1.0,00-0033119,<NA>,00-0037744,J.Brissett,7,00-0033119,T.McBride,00-0037744,T.McBride,00-0037744,0.0,0.0,1.730269,0.402115,5.429666,3,1.0,1.0,0.453482,54.651752
3,87.0,2026_01_ARI_LAC,2026091308,LAC,ARI,REG,1,ARI,away,LAC,LAC,43.0,2026-09-13,858.0,1758.0,3558.0,Half1,0.0,1.0,0.0,1.0,1.0,0.0,14:18,LAC 43,10.0,70.0,(14:18) (Shotgun) 22-T.Allgeier right guard to...,run,2.0,1.0,0.0,0.0,0.0,0.0,0.0,<NA>,<NA>,<NA>,<NA>,right,guard,<NA>,<NA>,<NA>,<NA>,3.0,3.0,0.0,<NA>,<NA>,<NA>,<NA>,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.003483,0.07119,0.001261,0.143111,0.299676,0.004079,0.4772,0.0,0.0,3.029715,-0.288451,-1.733012,1.733012,0.288451,-0.288451,-1.730269,1.730269,<NA>,<NA>,0.0,0.0,-1.463163,1.463163,-0.267106,0.267106,-1.463163,1.463163,-0.267106,0.267106,0.480118,0.519882,0.519882,0.480118,0.002435,0.018647,-0.018647,0.517447,0.482553,0.233157,0.766843,-0.002435,0.002435,-0.046572,0.046572,<NA>,<NA>,0.0,0.0,0.0,0.0,-0.046572,0.046572,0.0,0.0,-0.046572,0.046572,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,00-0037263,T.Allgeier,2.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,00-0033546,D.Tomlinson,LAC,00-0039111,T.Tuipulotu,LAC,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,0.0,0.0,0.0,0.0,<NA>,<NA>,2026,<NA>,<NA>,2.0,1.0,First down,87.0,"9/13/26, 16:25:43",2026-09-13T20:27:05.477Z,SoFi Stadium,"Sunny Temp: 78° F, Humidity: 70%, Wind: SW 6 mph",a9a87603-4feb-11f1-abca-2c54536568a9,0,0.0,RUSH,0.0,<NA>,2026-09-13T20:27:08.697Z,<NA>,1.0,Touchdown,2026-09-13T20:25:43.600Z,11.0,6:11,5.0,1.0,1.0,1.0,1.0,0.0,KICKOFF,TOUCHDOWN,15:00,08:49,ARI 30,LAC 5,39.0,319.0,26,14,Home,-12,40,8.5,47.5,0,dome,matrixturf,<NA>,<NA>,Jim Harbaugh,Jonathan Gannon,LAX01,SoFi Stadium,0.0,0.0,<NA>,<NA>,T.Allgeier,22,<NA>,<NA>,0.0,1.0,0.0,0.0,1.0,<NA>,00-0037263,<NA>,T.Allgeier,22,00-0037263,T.Allgeier,00-0037263,T.Allgeier,00-0037263,0.0,0.0,-0.288451,<NA>,<NA>,<NA>,<NA>,<NA>,0.4028,-40.280038
4,109.0,2026_01_ARI_LAC,2026091308,LAC,ARI,REG,1,ARI,away,LAC,LAC,41.0,2026-09-13,814.0,1714.0,3514.0,Half1,0.0,1.0,0.0,1.0,2.0,0.0,13:34,LAC 41,8.0,70.0,(13:34) (Shotgun) 7-J.Brissett pass incomplete...,pass,0.0,1.0,0.0,1.0,0.0,0.0,0.0,short,middle,11.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.0,3.0,0.0,<NA>,<NA>,<NA>,<NA>,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.003721,0.078867,0.001353,0.153728,0.314241,0.004537,0.443552,0.0,0.0,2.741264,-0.889568,-0.843445,0.843445,0.288451,-0.288451,-0.840701,0.840701,1.364321,-2.253888,0.0,0.0,-1.463163,1.463163,-0.267106,0.267106,-2.827483,2.827483,1.986783,-1.986783,0.482553,0.517447,0.517447,0.482553,-0.03252,-0.015568,0.015568,0.549967,0.450033,0.251804,0.748196,-0.002435,0.002435,-0.014052,0.014052,0.0,-0.03252,0.0,0.0,0.0,0.0,-0.046572,0.046572,0.0,0.0,-0.014052,0.014052,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,00-0033119,J.Brissett,<NA>,00-0039849,M.Harrison,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,0.0,0.0,0.0,0.0,<NA>,<NA>,2026,0.737044,-73.704445,2.0,1.0,First down,109.0,"9/13/26, 16:25:43",2026-09-13T20:27:49.310Z,SoFi Stadium,"Sunny Temp: 78° F, Humidity: 70%, Wind: SW 6 mph",a9a87603-4feb-11f1-abca-2c54536568a9,0,0.0,PASS,0.0,<NA>,2026-09-13T20:27:52.907Z,<NA>,1.0,Touchdown,2026-09-13T20:25:43.600Z,11.0,6:11,5.0,1.0,1.0,1.0,1.0,0.0,KICKOFF,TOUCHDOWN,15:00,08:49,ARI 30,LAC 5,39.0,319.0,26,14,Home,-12,40,8.5,47.5,0,dome,matrixturf,<NA>,<NA>,Jim Harbaugh,Jonathan Gannon,LAX01,SoFi Stadium,0.0,0.0,J.Brissett,7,<NA>,<NA>,M.Harrison,18,1.0,0.0,0.0,0.0,1.0,00-0033119,<NA>,00-0039849,J.Brissett,7,00-0033119,M.Harrison,00-0039849,M.Harrison,00-0039849,0.0,0.0,-0.889568,0.361333,4.490768,2,1.0,0.998909,0.61677,38.322973
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...

In [109]:
col_list = pbp_pandas.columns

for _ in col_list:
    print(_)

play_id
game_id
old_game_id
home_team
away_team
season_type
week
posteam
posteam_type
defteam
side_of_field
yardline_100
game_date
quarter_seconds_remaining
half_seconds_remaining
game_seconds_remaining
game_half
quarter_end
drive
sp
qtr
down
goal_to_go
time
yrdln
ydstogo
ydsnet
desc
play_type
yards_gained
shotgun
no_huddle
qb_dropback
qb_kneel
qb_spike
qb_scramble
pass_length
pass_location
air_yards
yards_after_catch
run_location
run_gap
field_goal_result
kick_distance
extra_point_result
two_point_conv_result
home_timeouts_remaining
away_timeouts_remaining
timeout
timeout_team
td_team
td_player_name
td_player_id
posteam_timeouts_remaining
defteam_timeouts_remaining
total_home_score
total_away_score
posteam_score
defteam_score
score_differential
posteam_score_post
defteam_score_post
score_differential_post
no_score_prob
opp_fg_prob
opp_safety_prob
opp_td_prob
fg_prob
safety_prob
td_prob
extra_point_prob
two_point_conversion_prob
ep
epa
total_home_epa
total_away_epa
total_home_rush_epa
total_away_rush_epa
total_home_pass_epa
total_away_pass_epa
air_epa
yac_epa
comp_air_epa
comp_yac_epa
total_home_comp_air_epa
total_away_comp_air_epa
total_home_comp_yac_epa
total_away_comp_yac_epa
total_home_raw_air_epa
total_away_raw_air_epa
total_home_raw_yac_epa
total_away_raw_yac_epa
wp
def_wp
home_wp
away_wp
wpa
vegas_wpa
vegas_home_wpa
home_wp_post
away_wp_post
vegas_wp
vegas_home_wp
total_home_rush_wpa
total_away_rush_wpa
total_home_pass_wpa
total_away_pass_wpa
air_wpa
yac_wpa
comp_air_wpa
comp_yac_wpa
total_home_comp_air_wpa
total_away_comp_air_wpa
total_home_comp_yac_wpa
total_away_comp_yac_wpa
total_home_raw_air_wpa
total_away_raw_air_wpa
total_home_raw_yac_wpa
total_away_raw_yac_wpa
punt_blocked
first_down_rush
first_down_pass
first_down_penalty
third_down_converted
third_down_failed
fourth_down_converted
fourth_down_failed
incomplete_pass
touchback
interception
punt_inside_twenty
punt_in_endzone
punt_out_of_bounds
punt_downed
punt_fair_catch
kickoff_inside_twenty
kickoff_in_endzone
kickoff_out_of_bounds
kickoff_downed
kickoff_fair_catch
fumble_forced
fumble_not_forced
fumble_out_of_bounds
solo_tackle
safety
penalty
tackled_for_loss
fumble_lost
own_kickoff_recovery
own_kickoff_recovery_td
qb_hit
rush_attempt
pass_attempt
sack
touchdown
pass_touchdown
rush_touchdown
return_touchdown
extra_point_attempt
two_point_attempt
field_goal_attempt
kickoff_attempt
punt_attempt
fumble
complete_pass
assist_tackle
lateral_reception
lateral_rush
lateral_return
lateral_recovery
passer_player_id
passer_player_name
passing_yards
receiver_player_id
receiver_player_name
receiving_yards
rusher_player_id
rusher_player_name
rushing_yards
lateral_receiver_player_id
lateral_receiver_player_name
lateral_receiving_yards
lateral_rusher_player_id
lateral_rusher_player_name
lateral_rushing_yards
lateral_sack_player_id
lateral_sack_player_name
interception_player_id
interception_player_name
lateral_interception_player_id
lateral_interception_player_name
punt_returner_player_id
punt_returner_player_name
lateral_punt_returner_player_id
lateral_punt_returner_player_name
kickoff_returner_player_name
kickoff_returner_player_id
lateral_kickoff_returner_player_id
lateral_kickoff_returner_player_name
punter_player_id
punter_player_name
kicker_player_name
kicker_player_id
own_kickoff_recovery_player_id
own_kickoff_recovery_player_name
blocked_player_id
blocked_player_name
tackle_for_loss_1_player_id
tackle_for_loss_1_player_name
tackle_for_loss_2_player_id
tackle_for_loss_2_player_name
qb_hit_1_player_id
qb_hit_1_player_name
qb_hit_2_player_id
qb_hit_2_player_name
forced_fumble_player_1_team
forced_fumble_player_1_player_id
forced_fumble_player_1_player_name
forced_fumble_player_2_team
forced_fumble_player_2_player_id
forced_fumble_player_2_player_name
solo_tackle_1_team
solo_tackle_2_team
solo_tackle_1_player_id
solo_tackle_2_player_id
solo_tackle_1_player_name
solo_tackle_2_player_name
assist_tackle_1_player_id
assist_tackle_1_player_name
assist_tackle_1_team
assist_tackle_2_player_id
assist_tackle_2_player_name
assist_tackle_2_team
assist_tackle_3_player_id
assist_tackle_3_player_name
assist_tackle_3_team
assist_tackle_4_player_id
assist_tackle_4_player_name
assist_tackle_4_team
tackle_with_assist
tackle_with_assist_1_player_id
tackle_with_assist_1_player_name
tackle_with_assist_1_team
tackle_with_assist_2_player_id
tackle_with_assist_2_player_name
tackle_with_assist_2_team
pass_defense_1_player_id
pass_defense_1_player_name
pass_defense_2_player_id
pass_defense_2_player_name
fumbled_1_team
fumbled_1_player_id
fumbled_1_player_name
fumbled_2_player_id
fumbled_2_player_name
fumbled_2_team
fumble_recovery_1_team
fumble_recovery_1_yards
fumble_recovery_1_player_id
fumble_recovery_1_player_name
fumble_recovery_2_team
fumble_recovery_2_yards
fumble_recovery_2_player_id
fumble_recovery_2_player_name
sack_player_id
sack_player_name
half_sack_1_player_id
half_sack_1_player_name
half_sack_2_player_id
half_sack_2_player_name
return_team
return_yards
penalty_team
penalty_player_id
penalty_player_name
penalty_yards
replay_or_challenge
replay_or_challenge_result
penalty_type
defensive_two_point_attempt
defensive_two_point_conv
defensive_extra_point_attempt
defensive_extra_point_conv
safety_player_name
safety_player_id
season
cp
cpoe
series
series_success
series_result
order_sequence
start_time
time_of_day
stadium
weather
nfl_api_id
play_clock
play_deleted
play_type_nfl
special_teams_play
st_play_type
end_clock_time
end_yard_line
fixed_drive
fixed_drive_result
drive_real_start_time
drive_play_count
drive_time_of_possession
drive_first_downs
drive_inside20
drive_ended_with_score
drive_quarter_start
drive_quarter_end
drive_yards_penalized
drive_start_transition
drive_end_transition
drive_game_clock_start
drive_game_clock_end
drive_start_yard_line
drive_end_yard_line
drive_play_id_started
drive_play_id_ended
away_score
home_score
location
result
total
spread_line
total_line
div_game
roof
surface
temp
wind
home_coach
away_coach
stadium_id
game_stadium
aborted_play
success
passer
passer_jersey_number
rusher
rusher_jersey_number
receiver
receiver_jersey_number
pass
rush
first_down
special
play
passer_id
rusher_id
receiver_id
name
jersey_number
id
fantasy_player_name
fantasy_player_id
fantasy
fantasy_id
out_of_bounds
home_opening_kickoff
qb_epa
xyac_epa
xyac_mean_yardage
xyac_median_yardage
xyac_success
xyac_fd
xpass
pass_oe

# Explore Player Stats from NFLVerse

In [110]:
# convert to pandas
player_stats_df = player_stats.to_pandas(use_pyarrow_extension_array=True)

player_stats_df

,player_id,player_name,player_display_name,position,position_group,headshot_url,season,week,season_type,game_id,team,opponent_team,completions,attempts,passing_yards,passing_tds,passing_interceptions,sacks_suffered,sack_yards_lost,sack_fumbles,sack_fumbles_lost,passing_air_yards,passing_yards_after_catch,passing_first_downs,passing_epa,passing_cpoe,passing_2pt_conversions,pacr,passing_10,passing_16,passing_20,passing_40,carries,rushing_yards,rushing_tds,rushing_fumbles,rushing_fumbles_lost,rushing_first_downs,rushing_epa,rushing_2pt_conversions,rushing_10,rushing_12,rushing_20,rushing_40,receptions,targets,receiving_yards,receiving_tds,receiving_fumbles,receiving_fumbles_lost,receiving_air_yards,receiving_yards_after_catch,receiving_first_downs,receiving_epa,receiving_2pt_conversions,receiving_10,receiving_16,receiving_20,receiving_40,racr,target_share,air_yards_share,wopr,special_teams_tds,def_tackles_solo,def_tackles_with_assist,def_tackle_assists,def_tackles_for_loss,def_tackles_for_loss_yards,def_fumbles_forced,def_sacks,def_sack_yards,def_qb_hits,def_interceptions,def_interception_yards,def_pass_defended,def_tds,def_fumbles,def_safeties,def_punt_blocks,def_pat_blocks,def_fg_blocks,def_2pt_atts,def_2pt_made,misc_yards,fumble_recovery_own,fumble_recovery_yards_own,fumble_recovery_opp,fumble_recovery_yards_opp,fumble_recovery_tds,penalties,penalty_yards,fumbles_forced_by_opp,fumbles_not_forced,fumbles_out_of_bounds,fumbles_total,fumbles_lost_total,punt_returns,punt_return_yards,kickoff_returns,kickoff_return_yards,fg_made,fg_att,fg_missed,fg_blocked,fg_long,fg_pct,fg_made_0_19,fg_made_20_29,fg_made_30_39,fg_made_40_49,fg_made_50_59,fg_made_60_,fg_missed_0_19,fg_missed_20_29,fg_missed_30_39,fg_missed_40_49,fg_missed_50_59,fg_missed_60_,fg_made_list,fg_missed_list,fg_blocked_list,fg_made_distance,fg_missed_distance,fg_blocked_distance,pat_made,pat_att,pat_missed,pat_blocked,pat_pct,gwfg_made,gwfg_att,gwfg_missed,gwfg_blocked,gwfg_distance,pt_att,pt_blocked,pt_long,pt_yards,pt_inside_20,pt_out_of_bounds,pt_downed,pt_touchback,pt_fair_caught,pt_returned,pt_return_yards,pt_return_tds,pt_net_yards,fantasy_points,fantasy_points_ppr
0,00-0023459,A.Rodgers,Aaron Rodgers,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_BUF_NYJ,NYJ,BUF,0,1,0,0,0,1,-10,0,0,17,0,0,-2.03196,<NA>,0,0.0,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,<NA>,0.0,0.0,0.0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0.0,0.0
1,00-0023853,M.Prater,Matt Prater,K,SPEC,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_ARI_WAS,ARI,WAS,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,<NA>,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,<NA>,0.0,0.0,0.0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,3,0,0,54,1.0,0,1,1,0,1,0,0,0,0,0,0,0,28;54;37,<NA>,<NA>,119,0,0,1,1,0,0,1.0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0.0,0.0
2,00-0025565,N.Folk,Nick Folk,K,SPEC,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_TEN_NO,TEN,NO,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,<NA>,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,<NA>,0.0,0.0,0.0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5,5,0,0,50,1.0,0,2,1,1,1,0,0,0,0,0,0,0,50;27;31;45;29,<NA>,<NA>,182,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0.0,0.0
3,00-0026190,C.Campbell,Calais Campbell,DE,DL,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_CAR_ATL,ATL,CAR,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,<NA>,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,<NA>,0.0,0.0,0.0,0,0,1,0,0,0,0,0.0,0.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0.0,0.0
4,00-0026498,M.Stafford,Matthew Stafford,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_LA_SEA,LA,SEA,24,38,334,0,0,0,0,0,0,409,106,17,20.679982,-0.425926,0,0.816626,18,7,6,1,3,11,0,0,0,1,0.868086,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,<NA>,0.0,0.0,0.0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,14.46,14.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18638,00-0038643,B.Willis,Brayden Willis,TE,TE,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,SF,KC,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,<NA>,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,<NA>,0.0,0.0,0.0,0,0,0,1,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,10,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0.0,0.0
18639,00-0038982,C.Conner,Chamarri Conner,DB,DB,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,KC,SF,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,<NA>,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,<NA>,0.0,0.0,0.0,0,0,0,2,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0.0,0.0
18640,00-0039006,F.Anudike-Uzomah,Felix Anudike-Uzomah,DE,DL,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,KC,SF,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,<NA>,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,<NA>,0.0,0.0,0.0,0,1,0,0,1,4,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0.0,0.0
18641,00-0039067,R.Rice,Rashee Rice,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,KC,SF,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,<NA>,0,0,0,0,2,5,0,1,0,1,0.311656,0,0,0,0,0,6,8,39,0,0,0,11,33,3,1.234109,0,2,0,0,0,3.545455,0.190476,0.039286,0.313214,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,4.4,10.4
18642,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2023,22,POST,2023_22_SF_KC,SF,KC,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,<NA>,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,<NA>,0.0,0.0,0.0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0.0,0.0

In [111]:
player_stats_list = player_stats_df.columns

for _ in player_stats_list:
    print(_)

player_id
player_name
player_display_name
position
position_group
headshot_url
season
week
season_type
game_id
team
opponent_team
completions
attempts
passing_yards
passing_tds
passing_interceptions
sacks_suffered
sack_yards_lost
sack_fumbles
sack_fumbles_lost
passing_air_yards
passing_yards_after_catch
passing_first_downs
passing_epa
passing_cpoe
passing_2pt_conversions
pacr
passing_10
passing_16
passing_20
passing_40
carries
rushing_yards
rushing_tds
rushing_fumbles
rushing_fumbles_lost
rushing_first_downs
rushing_epa
rushing_2pt_conversions
rushing_10
rushing_12
rushing_20
rushing_40
receptions
targets
receiving_yards
receiving_tds
receiving_fumbles
receiving_fumbles_lost
receiving_air_yards
receiving_yards_after_catch
receiving_first_downs
receiving_epa
receiving_2pt_conversions
receiving_10
receiving_16
receiving_20
receiving_40
racr
target_share
air_yards_share
wopr
special_teams_tds
def_tackles_solo
def_tackles_with_assist
def_tackle_assists
def_tackles_for_loss
def_tackles_for_loss_yards
def_fumbles_forced
def_sacks
def_sack_yards
def_qb_hits
def_interceptions
def_interception_yards
def_pass_defended
def_tds
def_fumbles
def_safeties
def_punt_blocks
def_pat_blocks
def_fg_blocks
def_2pt_atts
def_2pt_made
misc_yards
fumble_recovery_own
fumble_recovery_yards_own
fumble_recovery_opp
fumble_recovery_yards_opp
fumble_recovery_tds
penalties
penalty_yards
fumbles_forced_by_opp
fumbles_not_forced
fumbles_out_of_bounds
fumbles_total
fumbles_lost_total
punt_returns
punt_return_yards
kickoff_returns
kickoff_return_yards
fg_made
fg_att
fg_missed
fg_blocked
fg_long
fg_pct
fg_made_0_19
fg_made_20_29
fg_made_30_39
fg_made_40_49
fg_made_50_59
fg_made_60_
fg_missed_0_19
fg_missed_20_29
fg_missed_30_39
fg_missed_40_49
fg_missed_50_59
fg_missed_60_
fg_made_list
fg_missed_list
fg_blocked_list
fg_made_distance
fg_missed_distance
fg_blocked_distance
pat_made
pat_att
pat_missed
pat_blocked
pat_pct
gwfg_made
gwfg_att
gwfg_missed
gwfg_blocked
gwfg_distance
pt_att
pt_blocked
pt_long
pt_yards
pt_inside_20
pt_out_of_bounds
pt_downed
pt_touchback
pt_fair_caught
pt_returned
pt_return_yards
pt_return_tds
pt_net_yards
fantasy_points
fantasy_points_ppr

# Break into useful columns by position
QB <br>
RB <br>
WR/TE <br>
DEFENSE <br>
<br>
### Useful for all positions: <br>
player_id
player_name
player_display_name
position
position_group
headshot_url
season
week
season_type
game_id
team
opponent_team
<br>

### Useful for QB <br>
completions
attempts
passing_yards
passing_tds
passing_interceptions
sacks_suffered
sack_yards_lost
sack_fumbles
sack_fumbles_lost
passing_air_yards
passing_yards_after_catch
passing_first_downs
passing_epa
passing_cpoe
passing_2pt_conversions
pacr
passing_10
passing_16
passing_20
passing_40
carries
rushing_yards
rushing_tds
rushing_fumbles
rushing_fumbles_lost
rushing_first_downs
rushing_epa
rushing_2pt_conversions
rushing_10
rushing_12
rushing_20
rushing_40
<br>

### Useful for RB: <br>
carries
rushing_yards
rushing_tds
rushing_fumbles
rushing_fumbles_lost
rushing_first_downs
rushing_epa
rushing_2pt_conversions
rushing_10
rushing_12
rushing_20
rushing_40
receptions
targets
receiving_yards
receiving_tds
receiving_fumbles
receiving_fumbles_lost
receiving_air_yards
receiving_yards_after_catch
receiving_first_downs
receiving_epa
receiving_2pt_conversions
receiving_10
receiving_16
receiving_20
receiving_40
racr
target_share
air_yards_share
<br>

### Useful for WR: <br>
receptions
targets
receiving_yards
receiving_tds
receiving_fumbles
receiving_fumbles_lost
receiving_air_yards
receiving_yards_after_catch
receiving_first_downs
receiving_epa
receiving_2pt_conversions
receiving_10
receiving_16
receiving_20
receiving_40
racr
target_share
air_yards_share
<br>

### Useful for Defense: <br>
def_tackles_solo
def_tackles_with_assist
def_tackle_assists
def_tackles_for_loss
def_tackles_for_loss_yards
def_fumbles_forced
def_sacks
def_sack_yards
def_qb_hits
def_interceptions
def_interception_yards
def_pass_defended
def_tds
def_fumbles
def_safeties
def_punt_blocks
def_pat_blocks
def_fg_blocks
def_2pt_atts
def_2pt_made
misc_yards
fumble_recovery_own
fumble_recovery_yards_own
fumble_recovery_opp
fumble_recovery_yards_opp
fumble_recovery_tds

In [112]:
# columns lists
all_positions_cols = [
    'player_id',
    'player_name',
    'player_display_name',
    'position',
    'position_group',
    'headshot_url',
    'season',
    'week',
    'season_type',
    'game_id',
    'team',
    'opponent_team',
]

qb_cols = [
    'completions',
    'attempts',
    'passing_yards',
    'passing_tds',
    'passing_interceptions',
    'sacks_suffered',
    'sack_yards_lost',
    'sack_fumbles',
    'sack_fumbles_lost',
    'passing_air_yards',
    'passing_yards_after_catch',
    'passing_first_downs',
    'passing_epa',
    'passing_cpoe',
    'passing_2pt_conversions',
    'pacr',
    'passing_10',
    'passing_16',
    'passing_20',
    'passing_40',
    'carries',
    'rushing_yards',
    'rushing_tds',
    'rushing_fumbles',
    'rushing_fumbles_lost',
    'rushing_first_downs',
    'rushing_epa',
    'rushing_2pt_conversions',
    'rushing_10',
    'rushing_12',
    'rushing_20',
    'rushing_40'
]

rb_cols = [
    'carries',
    'rushing_yards',
    'rushing_tds',
    'rushing_fumbles',
    'rushing_fumbles_lost',
    'rushing_first_downs',
    'rushing_epa',
    'rushing_2pt_conversions',
    'rushing_10',
    'rushing_12',
    'rushing_20',
    'rushing_40',
    'receptions',
    'targets',
    'receiving_yards',
    'receiving_tds',
    'receiving_fumbles',
    'receiving_fumbles_lost',
    'receiving_air_yards',
    'receiving_yards_after_catch',
    'receiving_first_downs',
    'receiving_epa',
    'receiving_2pt_conversions',
    'receiving_10',
    'receiving_16',
    'receiving_20',
    'receiving_40',
    'racr',
    'target_share',
    'air_yards_share'
]

wr_cols = [
    'receptions',
    'targets',
    'receiving_yards',
    'receiving_tds',
    'receiving_fumbles',
    'receiving_fumbles_lost',
    'receiving_air_yards',
    'receiving_yards_after_catch',
    'receiving_first_downs',
    'receiving_epa',
    'receiving_2pt_conversions',
    'receiving_10',
    'receiving_16',
    'receiving_20',
    'receiving_40',
    'racr',
    'target_share',
    'air_yards_share'
]

def_cols = [
    'def_tackles_solo',
    'def_tackles_with_assist',
    'def_tackle_assists',
    'def_tackles_for_loss',
    'def_tackles_for_loss_yards',
    'def_fumbles_forced',
    'def_sacks',
    'def_sack_yards',
    'def_qb_hits',
    'def_interceptions',
    'def_interception_yards',
    'def_pass_defended',
    'def_tds',
    'def_fumbles',
    'def_safeties',
    'def_punt_blocks',
    'def_pat_blocks',
    'def_fg_blocks',
    'def_2pt_atts',
    'def_2pt_made',
    'misc_yards',
    'fumble_recovery_own',
    'fumble_recovery_yards_own',
    'fumble_recovery_opp',
    'fumble_recovery_yards_opp',
    'fumble_recovery_tds'
]

In [113]:
# explore all position cols
player_stats_df[all_positions_cols]

,player_id,player_name,player_display_name,position,position_group,headshot_url,season,week,season_type,game_id,team,opponent_team
0,00-0023459,A.Rodgers,Aaron Rodgers,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_BUF_NYJ,NYJ,BUF
1,00-0023853,M.Prater,Matt Prater,K,SPEC,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_ARI_WAS,ARI,WAS
2,00-0025565,N.Folk,Nick Folk,K,SPEC,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_TEN_NO,TEN,NO
3,00-0026190,C.Campbell,Calais Campbell,DE,DL,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_CAR_ATL,ATL,CAR
4,00-0026498,M.Stafford,Matthew Stafford,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_LA_SEA,LA,SEA
...,...,...,...,...,...,...,...,...,...,...,...,...
18638,00-0038643,B.Willis,Brayden Willis,TE,TE,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,SF,KC
18639,00-0038982,C.Conner,Chamarri Conner,DB,DB,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,KC,SF
18640,00-0039006,F.Anudike-Uzomah,Felix Anudike-Uzomah,DE,DL,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,KC,SF
18641,00-0039067,R.Rice,Rashee Rice,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,KC,SF
18642,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2023,22,POST,2023_22_SF_KC,SF,KC

# Break out into dataframes by position [QB, RB, WR/TW, DEFENSE]

In [114]:
# column lists for position mapping
wr_te_pos_list = ['WR', 'TE']
def_pos_list = ['DE', 'DT', 'LB', 'CB', 'S', 'FS', 'MLB', 'NT', 'ILB', 'DL', 'DB']
special_teams_pos_list = ['K', 'P', 'LS']

In [115]:
all_positions = player_stats_df[all_positions_cols]['position'].unique()

def_pos = [

]

qb_df = player_stats_df[player_stats_df['position']=='QB'][all_positions_cols + qb_cols]
rb_df = player_stats_df[player_stats_df['position']=='RB'][all_positions_cols + rb_cols]
wr_df = player_stats_df[(player_stats_df['position'].isin(wr_te_pos_list))][all_positions_cols + wr_cols]
def_df = player_stats_df[player_stats_df['position'].isin(def_pos_list)][all_positions_cols + def_cols]

all_positions

<ArrowExtensionArray>
[ 'QB',   'K',  'DE',   'P',  'DT',   'S',  'CB',  'LB',  'WR', 'OLB',  'FS',
  'RB', 'MLB',   'G',  'LS',  'NT',  'TE',  'FB', 'ILB',  'OT',  'DL',  'DB',
 'SAF',   'C',  <NA>,  'OL']
Length: 26, dtype: large_string[pyarrow]

# Explore QB DataFrame

In [116]:
qb_df

,player_id,player_name,player_display_name,position,position_group,headshot_url,season,week,season_type,game_id,team,opponent_team,completions,attempts,passing_yards,passing_tds,passing_interceptions,sacks_suffered,sack_yards_lost,sack_fumbles,sack_fumbles_lost,passing_air_yards,passing_yards_after_catch,passing_first_downs,passing_epa,passing_cpoe,passing_2pt_conversions,pacr,passing_10,passing_16,passing_20,passing_40,carries,rushing_yards,rushing_tds,rushing_fumbles,rushing_fumbles_lost,rushing_first_downs,rushing_epa,rushing_2pt_conversions,rushing_10,rushing_12,rushing_20,rushing_40
0,00-0023459,A.Rodgers,Aaron Rodgers,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_BUF_NYJ,NYJ,BUF,0,1,0,0,0,1,-10,0,0,17,0,0,-2.03196,<NA>,0,0.0,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0
4,00-0026498,M.Stafford,Matthew Stafford,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_LA_SEA,LA,SEA,24,38,334,0,0,0,0,0,0,409,106,17,20.679982,-0.425926,0,0.816626,18,7,6,1,3,11,0,0,0,1,0.868086,0,0,0,0,0
15,00-0028118,T.Taylor,Tyrod Taylor,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_DAL_NYG,NYG,DAL,2,2,6,0,0,0,0,0,0,-10,16,0,-0.544657,11.933872,0,0.0,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0
22,00-0029263,R.Wilson,Russell Wilson,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_LV_DEN,DEN,LV,27,34,177,2,0,2,-11,0,0,137,78,11,2.355538,14.956555,0,1.291971,7,2,2,0,1,1,0,0,0,0,-0.603321,0,0,0,0,0
29,00-0029604,K.Cousins,Kirk Cousins,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_TB_MIN,MIN,TB,33,44,344,2,1,2,-16,1,1,298,145,15,0.32369,4.992012,0,1.154362,12,8,5,1,3,7,0,1,1,1,-5.517632,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18478,00-0033873,P.Mahomes,Patrick Mahomes,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,21,POST,2023_21_KC_BAL,KC,BAL,30,39,241,1,0,2,-11,0,0,233,119,12,7.78335,13.588583,0,1.034335,10,4,2,0,6,15,0,0,0,1,-0.868874,0,1,0,0,0
18494,00-0034796,L.Jackson,Lamar Jackson,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,21,POST,2023_21_KC_BAL,BAL,KC,20,37,272,1,1,4,-17,1,1,344,133,11,-5.030444,-5.544073,0,0.790698,9,4,3,1,8,54,0,0,0,2,3.651432,0,2,1,1,0
18556,00-0037834,B.Purdy,Brock Purdy,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,21,POST,2023_21_DET_SF,SF,DET,20,31,267,1,1,2,-9,0,0,283,121,12,6.6246,2.537035,0,0.943463,9,6,5,1,5,48,0,0,0,3,5.131886,0,3,2,2,0
18589,00-0033873,P.Mahomes,Patrick Mahomes,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,KC,SF,34,46,333,2,1,3,-8,0,0,280,184,15,6.061147,7.730179,0,1.189286,12,6,4,1,9,66,0,1,0,5,3.037714,0,2,2,1,0
18631,00-0037834,B.Purdy,Brock Purdy,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,SF,KC,23,38,255,1,0,1,-4,0,0,324,140,14,6.197958,-3.190586,0,0.787037,14,8,3,0,3,12,0,0,0,0,0.532006,0,0,0,0,0

In [117]:

qb_season_agg = qb_df.groupby(['player_id', 'player_name', 'position', 'season']).agg({
    'completions': 'sum',
    'attempts': 'sum',
    'passing_yards': 'sum',
    'passing_tds': 'sum',
    'passing_interceptions': 'sum',
    'sacks_suffered': 'sum',
    'sack_yards_lost': 'sum',
    'sack_fumbles': 'sum',
    'sack_fumbles_lost': 'sum',
    'passing_air_yards': 'sum',
    'passing_yards_after_catch': 'sum',
    'passing_first_downs': 'sum',
    'passing_epa': 'sum',
    'passing_cpoe': 'mean'
})

# games played per season
qb_season_agg['total_games_played'] = qb_df.groupby(['player_id', 'player_name', 'position', 'season']).size()

# calculate completion percentage
qb_season_agg['completion_percentage'] = qb_season_agg['completions'] / qb_season_agg['attempts'] * 100

# calculate passing yards per game
qb_season_agg['passing_yards_per_game'] = qb_season_agg['passing_yards'] / qb_season_agg['total_games_played']

qb_season_agg = qb_season_agg.reset_index()

qb_season_agg

,player_id,player_name,position,season,completions,attempts,passing_yards,passing_tds,passing_interceptions,sacks_suffered,sack_yards_lost,sack_fumbles,sack_fumbles_lost,passing_air_yards,passing_yards_after_catch,passing_first_downs,passing_epa,passing_cpoe,total_games_played,completion_percentage,passing_yards_per_game
0,00-0023459,A.Rodgers,QB,2023,0,1,0,0,0,1,-10,0,0,17,0,0,-2.03196,<NA>,1,0.0,0.0
1,00-0026158,J.Flacco,QB,2023,157,250,1923,14,10,12,-96,3,1,2224,808,74,-18.313879,-1.316903,6,62.8,320.5
2,00-0026498,M.Stafford,QB,2023,351,557,4332,26,11,32,-215,0,0,4368,2097,202,72.767163,-1.969875,16,63.016158,270.75
3,00-0026625,B.Hoyer,QB,2023,23,42,231,0,2,1,-8,0,0,344,80,14,-8.780773,-7.965639,2,54.761905,115.5
4,00-0027948,B.Gabbert,QB,2023,18,35,185,0,3,1,-9,0,0,198,118,8,-16.143287,-9.541537,2,51.428571,92.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,00-0038598,J.Hall,QB,2023,13,20,168,0,1,4,-28,2,2,156,99,7,-12.676043,2.874488,3,65.0,56.0
77,00-0039150,B.Young,QB,2023,315,527,2877,11,10,62,-477,9,6,4009,1300,133,-159.273442,-1.251331,16,59.772296,179.8125
78,00-0039152,W.Levis,QB,2023,149,255,1808,8,4,28,-185,5,2,2688,746,81,-12.833491,-0.915297,9,58.431373,200.888889
79,00-0039163,C.Stroud,QB,2023,354,553,4557,26,5,38,-331,6,3,4908,2012,206,72.131642,-0.452308,17,64.014467,268.058824
80,00-0039164,A.Richardson,QB,2023,50,84,577,3,1,7,-29,1,0,676,297,31,6.693791,-5.170243,4,59.52381,144.25

# Visuals for QB Data

In [141]:
# create lists for filters
season_list = qb_season_agg['season'].unique().tolist()
player_list = qb_season_agg['player_name'].unique().tolist()

In [142]:
season_filter = alt.param(
    name = 'selected_season',
    value = 2023,
    bind = alt.binding_select(
        options = season_list,
        name = 'Season'
    )
)

bar_chart_passing_yards = (alt.Chart(qb_season_agg).mark_bar().encode(
    x=alt.X('player_name:N', title='Player Name'),
    y=alt.Y('passing_yards:Q', title='Passing Yards'),
    color=alt.Color('season:N', title='Season'),
    tooltip=['player_name', 
             'season', 
             'passing_yards', 
             'passing_tds', 
             'passing_interceptions', 
             'completion_percentage', 
             'passing_yards_per_game']
).add_params(season_filter)
.transform_filter(alt.datum.season == season_filter)
).properties(
    title='Passing Yards by Player and Season'
).interactive()

bar_chart_passing_yards

alt.Chart(...)

# Explore RB DataFrame

In [81]:
rb_df

,player_id,player_name,player_display_name,position,position_group,headshot_url,season,week,season_type,game_id,team,opponent_team,carries,rushing_yards,rushing_tds,rushing_fumbles,rushing_fumbles_lost,rushing_first_downs,rushing_epa,rushing_2pt_conversions,rushing_10,rushing_12,rushing_20,rushing_40,receptions,targets,receiving_yards,receiving_tds,receiving_fumbles,receiving_fumbles_lost,receiving_air_yards,receiving_yards_after_catch,receiving_first_downs,receiving_epa,receiving_2pt_conversions,receiving_10,receiving_16,receiving_20,receiving_40,racr,target_share,air_yards_share
20,00-0029239,B.Bolden,Brandon Bolden,RB,RB,https://static.www.nfl.com/image/private/f_aut...,2023,1,REG,2023_01_LV_DEN,LV,DEN,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,<NA>,0.0,0.0
55,00-0030513,L.Murray,Latavius Murray,RB,RB,https://static.www.nfl.com/image/private/f_aut...,2023,1,REG,2023_01_BUF_NYJ,BUF,NYJ,2,8,0,0,0,0,-0.030657,0,0,0,0,0,1,2,9,0,0,0,4,8,1,2.01752,0,0,0,0,0,2.25,0.051282,0.011834
77,00-0031376,J.McKinnon,Jerick McKinnon,RB,RB,https://static.www.nfl.com/image/private/f_aut...,2023,1,REG,2023_01_DET_KC,KC,DET,0,0,0,0,0,0,<NA>,0,0,0,0,0,1,2,10,0,0,0,5,4,1,-0.20584,0,1,0,0,0,2.0,0.054054,0.014124
101,00-0031687,R.Mostert,Raheem Mostert,RB,RB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_MIA_LAC,MIA,LAC,10,37,1,0,0,3,-0.358886,0,2,1,0,0,2,2,13,0,0,0,1,12,0,-0.167644,0,0,0,0,0,13.0,0.045455,0.00202
114,00-0032104,A.Abdullah,Ameer Abdullah,RB,RB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_LV_DEN,LV,DEN,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,1,0,0,0,0,6,0,0,-4.914183,0,0,0,0,0,0.0,0.038462,0.032787
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18580,00-0031376,J.McKinnon,Jerick McKinnon,RB,RB,https://static.www.nfl.com/image/private/f_aut...,2023,22,POST,2023_22_SF_KC,KC,SF,0,0,0,0,0,0,<NA>,0,0,0,0,0,2,2,15,0,0,0,1,14,1,0.313796,0,0,0,0,0,15.0,0.047619,0.003571
18586,00-0033280,C.McCaffrey,Christian McCaffrey,RB,RB,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,SF,KC,22,80,0,1,1,4,-10.19243,0,1,0,0,0,8,8,80,1,0,0,-2,82,3,4.32332,0,3,2,2,0,-40.0,0.216216,-0.00627
18615,00-0036360,C.Edwards-Helaire,Clyde Edwards-Helaire,RB,RB,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,KC,SF,1,0,0,0,0,0,-0.547586,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,<NA>,0.0,0.0
18622,00-0036567,E.Mitchell,Elijah Mitchell,RB,RB,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,SF,KC,2,8,0,0,0,0,1.333702,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,<NA>,0.0,0.0
18629,00-0037197,I.Pacheco,Isiah Pacheco,RB,RB,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,KC,SF,18,59,0,1,1,3,-10.328413,0,1,0,0,0,6,6,33,0,0,0,-13,46,0,0.389782,0,0,0,0,0,-2.538462,0.142857,-0.046429

# Explore WR/TE DataFrame

In [82]:
wr_df

,player_id,player_name,player_display_name,position,position_group,headshot_url,season,week,season_type,game_id,team,opponent_team,receptions,targets,receiving_yards,receiving_tds,receiving_fumbles,receiving_fumbles_lost,receiving_air_yards,receiving_yards_after_catch,receiving_first_downs,receiving_epa,receiving_2pt_conversions,receiving_10,receiving_16,receiving_20,receiving_40,racr,target_share,air_yards_share
13,00-0028002,R.Cobb,Randall Cobb,WR,WR,https://static.www.nfl.com/image/private/f_aut...,2023,1,REG,2023_01_BUF_NYJ,NYJ,BUF,0,1,0,0,0,0,10,0,0,-3.924131,0,0,0,0,0,0.0,0.055556,0.088496
23,00-0029293,M.Jones,Marvin Jones,WR,WR,https://static.www.nfl.com/image/private/f_aut...,2023,1,REG,2023_01_DET_KC,DET,KC,2,6,8,0,1,1,50,4,0,-6.195231,0,0,0,0,0,0.16,0.1875,0.210084
39,00-0030035,A.Thielen,Adam Thielen,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_CAR_ATL,CAR,ATL,2,2,12,0,0,0,9,3,1,0.757165,0,0,0,0,0,1.333333,0.064516,0.032028
40,00-0030061,Z.Ertz,Zach Ertz,TE,TE,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_ARI_WAS,ARI,WAS,6,10,21,0,0,0,56,6,1,-3.360603,0,0,0,0,0,0.375,0.333333,0.301075
43,00-0030068,M.Goodwin,Marquise Goodwin,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_CIN_CLE,CLE,CIN,0,2,0,0,0,0,86,0,0,-2.125956,0,0,0,0,0,0.0,0.068966,0.261398
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18613,00-0036261,B.Aiyuk,Brandon Aiyuk,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,SF,KC,3,6,49,0,0,0,88,14,3,2.416118,0,3,2,1,0,0.556818,0.162162,0.275862
18619,00-0036429,C.Woerner,Charlie Woerner,TE,TE,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,SF,KC,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,<NA>,0.0,0.0
18624,00-0036637,N.Gray,Noah Gray,TE,TE,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,KC,SF,2,2,22,0,0,0,8,14,1,0.624211,0,2,0,0,0,2.75,0.047619,0.028571
18638,00-0038643,B.Willis,Brayden Willis,TE,TE,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,SF,KC,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,<NA>,0.0,0.0
18641,00-0039067,R.Rice,Rashee Rice,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,KC,SF,6,8,39,0,0,0,11,33,3,1.234109,0,2,0,0,0,3.545455,0.190476,0.039286

# Explore Defense DataFrame

In [83]:
def_df

,player_id,player_name,player_display_name,position,position_group,headshot_url,season,week,season_type,game_id,team,opponent_team,def_tackles_solo,def_tackles_with_assist,def_tackle_assists,def_tackles_for_loss,def_tackles_for_loss_yards,def_fumbles_forced,def_sacks,def_sack_yards,def_qb_hits,def_interceptions,def_interception_yards,def_pass_defended,def_tds,def_fumbles,def_safeties,def_punt_blocks,def_pat_blocks,def_fg_blocks,def_2pt_atts,def_2pt_made,misc_yards,fumble_recovery_own,fumble_recovery_yards_own,fumble_recovery_opp,fumble_recovery_yards_opp,fumble_recovery_tds
3,00-0026190,C.Campbell,Calais Campbell,DE,DL,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_CAR_ATL,ATL,CAR,0,1,0,0,0,0,0.0,0.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,00-0027723,A.Woods,Al Woods,DT,DL,https://static.www.nfl.com/image/private/f_aut...,2023,1,REG,2023_01_BUF_NYJ,NYJ,BUF,1,0,0,1,2,0,1.0,2.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,00-0027865,B.Graham,Brandon Graham,DE,DL,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_PHI_NE,PHI,NE,1,0,0,1,2,0,0.0,0.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,00-0027872,K.Jackson,Kareem Jackson,S,DB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_LV_DEN,DEN,LV,4,0,0,0,0,0,0.0,0.0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,00-0027943,P.Peterson,Patrick Peterson,CB,DB,https://static.www.nfl.com/image/private/f_aut...,2023,1,REG,2023_01_SF_PIT,PIT,SF,0,0,2,0,0,0,0.0,0.0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18633,00-0038093,N.Farrell,Neil Farrell,DE,DL,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,KC,SF,0,0,1,0,0,0,0.0,0.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18636,00-0038594,D.Luter,Darrell Luter Jr.,CB,DB,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,SF,KC,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
18637,00-0038625,D.Winters,Dee Winters,LB,LB,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,SF,KC,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18639,00-0038982,C.Conner,Chamarri Conner,DB,DB,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,KC,SF,0,0,2,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
18640,00-0039006,F.Anudike-Uzomah,Felix Anudike-Uzomah,DE,DL,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,KC,SF,1,0,0,1,4,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0