In [1]:
from dotenv import load_dotenv
import os
import requests
import json
import pandas as pd

In [ ]:
def client_cxn():
    """
    Establish a client connection to API-Sports
    """
    load_dotenv()
    api_key = os.getenv('api_key')

    hostname = 'https://v1.american-football.api-sports.io'

    # create expected headers
    headers = {
        'x-apisports-key': api_key
    }

In [2]:
# load the api secret
load_dotenv()
api_key = os.getenv('api_key')

hostname = 'https://v1.american-football.api-sports.io'

# create expected headers
headers = {
    'x-apisports-key': api_key
}

# Explore the NFL API

### Explore players endpoint
/players <br>
docs: https://api-sports.io/documentation/nfl/v1#tag/Players/operation/get-players

In [ ]:
def get_players_data():
    """
    """
    pass

In [3]:
players_url = f'{hostname}/players'
player_params = {
    'id': 1
}

resp = requests.get(
    url=players_url,
    headers=headers,
    params=player_params
)

In [4]:
resp.json()

{'get': 'players',
 'parameters': {'id': '1'},
 'errors': [],
 'results': 1,
 'response': [{'id': 1,
   'name': 'Derek Carr',
   'age': 33,
   'height': '6\' 3"',
   'weight': '215 lbs',
   'college': 'Fresno State',
   'group': 'Offense',
   'position': 'QB',
   'number': 4,
   'salary': None,
   'experience': 11,
   'image': 'https://media.api-sports.io/american-football/players/1.png'}]}

### Explore the statistics API
/players/statistics <br>
docs: https://api-sports.io/documentation/nfl/v1#tag/Players/operation/get-players

In [5]:
players_stats_url = f'{hostname}/players/statistics'
player_stats_params = {
    'id': 1,
    'season':'2024'
}

resp = requests.get(
    url=players_stats_url,
    headers=headers,
    params=player_stats_params
)

In [6]:
resp.json()

{'get': 'players/statistics',
 'parameters': {'id': '1', 'season': '2024'},
 'errors': [],
 'results': 1,
 'response': [{'player': {'id': 1,
    'name': 'Derek Carr',
    'image': 'https://media.api-sports.io/american-football/players/1.png'},
   'teams': [{'team': {'id': 1,
      'name': 'Las Vegas Raiders',
      'logo': 'https://media.api-sports.io/american-football/teams/1.png'},
     'groups': [{'name': 'Passing',
       'statistics': [{'name': 'passing attempts', 'value': '502'},
        {'name': 'completions', 'value': '305'},
        {'name': 'completion pct', 'value': '60.8'},
        {'name': 'yards', 'value': '3,522'},
        {'name': 'yards per pass avg', 'value': '7.0'},
        {'name': 'yards per game', 'value': '234.8'},
        {'name': 'longest pass', 'value': '60'},
        {'name': 'passing touchdowns', 'value': '24'},
        {'name': 'passing touchdowns pct', 'value': None},
        {'name': 'interceptions', 'value': '14'},
        {'name': 'interceptions pct', 'value': None},
        {'name': 'sacks', 'value': '27'},
        {'name': 'sacked yards lost', 'value': '191'},
        {'name': 'quaterback rating', 'value': '86.3'}]},
      {'name': 'Rushing',
       'statistics': [{'name': 'rushing attempts', 'value': '24'},
        {'name': 'yards', 'value': '102'},
        {'name': 'yards per rush avg', 'value': '4.3'},
        {'name': 'longest rush', 'value': '20'},
        {'name': 'over 20 yards', 'value': '1'},
        {'name': 'rushing touchdowns', 'value': '0'},
        {'name': 'yards per game', 'value': '6.8'},
        {'name': 'fumbles', 'value': '1'},
        {'name': 'fumbles lost', 'value': '0'},
        {'name': 'rushing first downs', 'value': '10'}]}]},
    {'team': {'id': 27,
      'name': 'New Orleans Saints',
      'logo': 'https://media.api-sports.io/american-football/teams/27.png'},
     'groups': [{'name': 'Passing',
       'statistics': [{'name': 'passing attempts', 'value': '279'},
        {'name': 'completions', 'value': '189'},
        {'name': 'completion pct', 'value': '67.7'},
        {'name': 'yards', 'value': '2,145'},
        {'name': 'yards per pass avg', 'value': '7.7'},
        {'name': 'yards per game', 'value': '214.5'},
        {'name': 'longest pass', 'value': '71'},
        {'name': 'passing touchdowns', 'value': '15'},
        {'name': 'passing touchdowns pct', 'value': None},
        {'name': 'interceptions', 'value': '5'},
        {'name': 'interceptions pct', 'value': None},
        {'name': 'sacks', 'value': '8'},
        {'name': 'sacked yards lost', 'value': '48'},
        {'name': 'quaterback rating', 'value': '101.0'}]},
      {'name': 'Rushing',
       'statistics': [{'name': 'rushing attempts', 'value': '17'},
        {'name': 'yards', 'value': '71'},
        {'name': 'yards per rush avg', 'value': '4.2'},
        {'name': 'longest rush', 'value': '13'},
        {'name': 'over 20 yards', 'value': '0'},
        {'name': 'rushing touchdowns', 'value': '1'},
        {'name': 'yards per game', 'value': '7.1'},
        {'name': 'fumbles', 'value': '1'},
        {'name': 'fumbles lost', 'value': '0'},
        {'name': 'rushing first downs', 'value': '4'}]},
      {'name': 'Scoring',
       'statistics': [{'name': 'rushing touchdowns', 'value': '1'},
        {'name': 'receiving touchdowns', 'value': '0'},
        {'name': 'return touchdowns', 'value': '0'},
        {'name': 'total touchdowns', 'value': '1'},
        {'name': 'field goals', 'value': '0'},
        {'name': 'extra points', 'value': '0'},
        {'name': 'two point conversions', 'value': '0'},
        {'name': 'total points', 'value': '6'},
        {'name': 'total points per game', 'value': '0.6'}]}]}]}]}

In [7]:
# get length of player statistics output for estimation
player_stats_data = resp.json()

groups = player_stats_data['response'][0]['teams'][0]['groups']

passing_stats = groups[0]['statistics']
rushing_stats = groups[1]['statistics']

len(passing_stats), len(rushing_stats)

(14, 10)

# Explore Sleeper API for Fantasy Football Points

### Fetch all Players
/players/nfl<br>
params: position <br>
docs: https://docs.sleeper.com/#fetch-all-players

In [8]:
sleeper_hostname = 'https://api.sleeper.app/v1/'
routes = 'players/nfl'

# players url
players_url = f'{sleeper_hostname}{routes}'

params = {
    'position': 'QB'
}

players_responses = requests.get(
    url=players_url,
    params=params
)

In [9]:
players_responses.json()

{'13175': {'birth_date': '2000-07-27',
  'player_id': '13175',
  'yahoo_id': None,
  'sportradar_id': 'b1b21920-2b81-11f0-a7dc-b36f60eb4d60',
  'practice_description': None,
  'full_name': 'Kinkead Dent',
  'active': True,
  'injury_status': None,
  'birth_country': None,
  'oddsjam_id': None,
  'swish_id': None,
  'first_name': 'Kinkead',
  'depth_chart_order': None,
  'status': 'Inactive',
  'injury_notes': None,
  'competitions': [],
  'years_exp': 0,
  'number': None,
  'news_updated': None,
  'team_abbr': None,
  'high_school': 'Jackson Academy (MS)',
  'last_name': 'Dent',
  'search_last_name': 'dent',
  'espn_id': None,
  'injury_body_part': None,
  'practice_participation': None,
  'birth_state': None,
  'rotoworld_id': None,
  'injury_start_date': None,
  'team_changed_at': None,
  'team': None,
  'search_rank': 9999999,
  'birth_city': None,
  'rotowire_id': None,
  'search_full_name': 'kinkeaddent',
  'college': 'Tennessee-Martin',
  'position': 'QB',
  'gsis_id': None,
  'metadata': {'channel_id': '1225943136610562048', 'rookie_year': '0'},
  'weight': '215',
  'stats_id': None,
  'height': '76',
  'hashtag': '#kinkeaddent-NFL-FA',
  'fantasy_positions': ['QB'],
  'opta_id': None,
  'fantasy_data_id': None,
  'pandascore_id': None,
  'depth_chart_position': None,
  'kalshi_id': None,
  'search_first_name': 'kinkead',
  'sport': 'nfl',
  'age': 25,
  'player_shard': '1'},
 '13221': {'birth_date': '2000-08-04',
  'player_id': '13221',
  'yahoo_id': None,
  'sportradar_id': '08f0fef0-3748-11f0-9677-41d005293433',
  'practice_description': None,
  'full_name': 'Brett Gabbert',
  'active': True,
  'injury_status': None,
  'birth_country': None,
  'oddsjam_id': '0D57BED3D0B2DB99',
  'swish_id': None,
  'first_name': 'Brett',
  'depth_chart_order': None,
  'status': 'Active',
  'injury_notes': None,
  'competitions': [],
  'years_exp': 0,
  'number': None,
  'news_updated': 1754250907948,
  'team_abbr': None,
  'high_school': 'Christian Brothers College (MO)',
  'last_name': 'Gabbert',
  'search_last_name': 'gabbert',
  'espn_id': None,
  'injury_body_part': None,
  'practice_participation': None,
  'birth_state': None,
  'rotoworld_id': None,
  'injury_start_date': None,
  'team_changed_at': None,
  'team': None,
  'search_rank': 999,
  'birth_city': None,
  'rotowire_id': 19192,
  'search_full_name': 'brettgabbert',
  'college': 'Miami (OH)',
  'position': 'QB',
  'gsis_id': None,
  'metadata': {'channel_id': '1231394003711180800', 'rookie_year': '0'},
  'weight': '206',
  'stats_id': None,
  'height': '72',
  'hashtag': '#brettgabbert-NFL-FA',
  'fantasy_positions': ['QB'],
  'opta_id': None,
  'fantasy_data_id': None,
  'pandascore_id': None,
  'depth_chart_position': None,
  'kalshi_id': 'b78d326c-47b1-4197-bfba-8e3c393cbd39',
  'search_first_name': 'brett',
  'sport': 'nfl',
  'age': 25,
  'player_shard': '5'},
 '1907': {'birth_date': '1992-12-06',
  'player_id': '1907',
  'yahoo_id': 27550,
  'sportradar_id': '7ebbfdef-1185-4896-a323-e6d5669a8345',
  'practice_description': None,
  'full_name': 'Johnny Manziel',
  'active': False,
  'injury_status': None,
  'birth_country': None,
  'oddsjam_id': None,
  'swish_id': None,
  'first_name': 'Johnny',
  'depth_chart_order': None,
  'status': 'Inactive',
  'injury_notes': None,
  'competitions': [],
  'years_exp': 6,
  'number': 2,
  'news_updated': 1552834853016,
  'team_abbr': None,
  'high_school': 'Tivy (TX)',
  'last_name': 'Manziel',
  'search_last_name': 'manziel',
  'espn_id': 16736,
  'injury_body_part': None,
  'practice_participation': None,
  'birth_state': None,
  'rotoworld_id': 9271,
  'injury_start_date': None,
  'team_changed_at': None,
  'team': None,
  'search_rank': 9999999,
  'birth_city': None,
  'rotowire_id': 9246,
  'search_full_name': 'johnnymanziel',
  'college': 'Texas A&M',
  'position': 'QB',
  'gsis_id': None,
  'metadata': None,
  'weight': '210',
  'stats_id': 593578,
  'height': '6\'0"',
  'hashtag': '#johnnymanziel-NFL-FA-2',
  'fantasy_positions': ['QB'],
  'opta_id': None,
  'fantasy_data_id': 16135,
  'pandascore_id': None,
  'depth_chart_position': None,
  'kalshi_id': None,
  'search_first_name': 'johnny',
  'sport': 'nfl',
  'age': 27,
  'player_shard': '6'},
 '13295': {'birth_date': '2002-01-17',
  'player_id': '13295',
  'yahoo_id': None,
  'sportradar_id': '0fe9c501-799c-45f7-a48f-2b4d9d6e9452',
  'practice_description': None,
  'full_name': 'Behren Morton',
  'active': True,
  'injury_status': None,
  'birth_country': None,
  'oddsjam_id': None,
  'swish_id': None,
  'first_name': 'Behren',
  'depth_chart_order': 3,
  'status': 'Active',
  'injury_notes': None,
  'competitions': [],
  'years_exp': 0,
  'number': 15,
  'news_updated': 1789922155923,
  'team_abbr': None,
  'high_school': 'Eastland (TX)',
  'last_name': 'Morton',
  'search_last_name': 'morton',
  'espn_id': None,
  'injury_body_part': None,
  'practice_participation': None,
  'birth_state': None,
  'rotoworld_id': None,
  'injury_start_date': None,
  'team_changed_at': None,
  'team': 'NE',
  'search_rank': 574,
  'birth_city': None,
  'rotowire_id': 19293,
  'search_full_name': 'behrenmorton',
  'college': 'Texas Tech',
  'position': 'QB',
  'gsis_id': None,
  'metadata': {'channel_id': '1353911393161588736',
   'genius_id': '1505193',
   'rookie_year': '2026',
   'source_id': '85fd5db1-16a4-472a-b65e-3d0b51b41ae8'},
  'weight': '218',
  'stats_id': None,
  'height': '74',
  'hashtag': '#behrenmorton-NFL-NE-15',
  'fantasy_positions': ['QB'],
  'opta_id': None,
  'fantasy_data_id': 28049,
  'pandascore_id': None,
  'depth_chart_position': 'QB',
  'kalshi_id': '009e8842-3fe1-41ad-8fb6-422de0463220',
  'search_first_name': 'behren',
  'sport': 'nfl',
  'age': 24,
  'player_shard': '6'},
 '1895': {'birth_date': '1990-09-13',
  'player_id': '1895',
  'yahoo_id': 27692,
  'sportradar_id': 'd4b30988-e8c5-4689-8037-f79a0d3c2774',
  'practice_description': None,
  'full_name': 'AJ McCarron',
  'active': True,
  'injury_status': None,
  'birth_country': None,
  'oddsjam_id': '2515F6F4347B',
  'swish_id': 508649,
  'first_name': 'AJ',
  'depth_chart_order': None,
  'status': 'Active',
  'injury_notes': None,
  'competitions': [],
  'years_exp': 10,
  'number': 4,
  'news_updated': 1707938117372,
  'team_abbr': None,
  'high_school': "St. Paul's Episcopal (AL)",
  'last_name': 'McCarron',
  'search_last_name': 'mccarron',
  'espn_id': 16810,
  'injury_body_part': None,
  'practice_participation': None,
  'birth_state': None,
  'rotoworld_id': 9290,
  'injury_start_date': None,
  'team_changed_at': None,
  'team': None,
  'search_rank': 311,
  'birth_city': None,
  'rotowire_id': 9319,
  'search_full_name': 'ajmccarron',
  'college': 'Alabama',
  'position': 'QB',
  'gsis_id': '00-0031288',
  'metadata': {'channel_id': '1116852767063801856', 'rookie_year': '2014'},
  'weight': '220',
  'stats_id': 508649,
  'height': '75',
  'hashtag': '#ajmccarron-NFL-FA-4',
  'fantasy_positions': ['QB'],
  'opta_id': None,
  'fantasy_data_id': 16116,
  'pandascore_id': None,
  'depth_chart_position': None,
  'kalshi_id': None,
  'search_first_name': 'aj',
  'sport': 'nfl',
  'age': 33,
  'player_shard': '2'},
 '5845': {'birth_date': '1997-05-03',
  'player_id': '5845',
  'yahoo_id': 31847,
  'sportradar_id': '6e4eda90-2656-434f-a262-4e5e9fde3946',
  'practice_description': None,
  'full_name': 'Dwayne Haskins',
  'active': False,
  'injury_status': None,
  'birth_country': None,
  'oddsjam_id': None,
  'swish_id': 946582,
  'first_name': 'Dwayne',
  'depth_chart_order': None,
  'status': 'Active',
  'injury_notes': None,
  'competitions': [],
  'years_exp': 3,
  'number': 3,
  'news_updated': 1649518240714,
  'team_abbr': None,
  'high_school': 'Bullis School (NJ)',
  'last_name': 'Haskins',
  'search_last_name': 'haskins',
  'espn_id': 4040616,
  'injury_body_part': None,
  'practice_participation': None,
  'birth_state': None,
  'rotoworld_id': 13979,
  'injury_start_date': None,
  'team_changed_at': None,
  'team': 'PIT',
  'search_rank': 602,
  'birth_city': None,
  'rotowire_id': 13558,
  'search_full_name': 'dwaynehaskins',
  'college': 'Ohio State',
  'position': 'QB',
  'gsis_id': ' 00-0035232',
  'metadata': {'override_active': 'false'},
  'weight': '230',
  'stats_id': 946582,
  'height': '76',
  'hashtag': '#dwaynehaskins-NFL-PIT-3',
  'fantasy_positions': ['QB'],
  'opta_id': None,
  'fantasy_data_id': 20795,
  'pandascore_id': None,
  'depth_chart_position': None,
  'kalshi_id': None,
  'search_first_name': 'dwayne',
  'sport': 'nfl',
  'age': 24,
  'player_shard': '5'},
 '19': {'birth_date': '1985-01-16',
  'player_id': '19',
  'yahoo_id': 8795,
  'sportradar_id': '64797df2-efd3-4b27-86ee-1d48f7edb09f',
  'practice_description': None,
  'full_name': 'Joe Flacco',
  'active': True,
  'injury_status': None,
  'birth_country': None,
  'oddsjam_id': '9BD13F1CF846',
  'swish_id': 216342,
  'first_name': 'Joe',
  'depth_chart_order': 2,
  'status': 'Active',
  'injury_notes': None,
  'competitions': [],
  'years_exp': 18,
  'number': 16,
  'news_updated': 1781961641331,
  'team_abbr': None,
  'high_school': 'Audubon (NJ)',
  'last_name': 'Flacco',
  'search_last_name': 'flacco',
  'espn_id': 11252,
  'injury_body_part': None,
  'practice_participation': None,
  'birth_state': None,
  'rotoworld_id': 4677,
  'injury_start_date': None,
  'team_changed_at': None,
  'team': 'CIN',
  'search_rank': 490,
  'birth_city': None,
  'rotowire_id': 5648,
  'search_full_name': 'joeflacco',
  'college': 'Delaware',
  'position': 'QB',
  'gsis_id': '00-0026158',
  'metadata': {'channel_id': '1113708777586061312',
   'genius_id': '444180',
   'rookie_year': '2008'},
  'weight': '245',
  'stats_id': 216342,
  'height': '78',
  'hashtag': '#joeflacco-NFL-CIN-16',
  'fantasy_positions': ['QB'],
  'opta_id': None,
  'fantasy_data_id': 611,
  'pandascore_id': None,
  'depth_chart_position': 'QB',
  'kalshi_id': 'ecebcfd1-89cf-4279-a328-55136cafef82',
  'search_first_name': 'joe',
  'sport': 'nfl',
  'age': 41,
  'player_shard': '5'},
 '1550': {'birth_date': '1989-11-17',
  'player_id': '1550',
  'yahoo_id': 26949,
  'sportradar_id': '949c34b9-150a-4a1b-b884-1fcf1ebaabdf',
  'practice_description': None,
  'full_name': 'Ryan Griffin',
  'active': True,
  'injury_status': None,
  'birth_country': None,
  'oddsjam_id': None,
  'swish_id': 466883,
  'first_name': 'Ryan',
  'depth_chart_order': None,
  'status': 'Active',
  'injury_notes': None,
  'competitions': [],
  'years_exp': 10,
  'number': 4,
  'news_updated': 1711038060009,
  'team_abbr': None,
  'high_school': 'Chaminade College Prep (CA)',
  'last_name': 'Griffin',
  'search_last_name': 'griffin',
  'espn_id': 16140,
  'injury_body_part': None,
  'practice_participation': None,
  'birth_state': None,
  'rotoworld_id': 8507,
  'injury_start_date': None,
  'team_changed_at': None,
  'team': None,
  'search_rank': 292,
  'birth_city': None,
  'rotowire_id': 8923,
  'search_full_name': 'ryangriffin',
  'college': 'Tulane',
  'position': 'QB',
  'gsis_id': '00-0029857',
  'metadata': {'channel_id': '1116852745207283712'},
  'weight': '218',
  'stats_id': 466883,
  'height': '76',
  'hashtag': '#ryangriffin-NFL-FA-4',
  'fantasy_positions': ['QB'],
  'opta_id': None,
  'fantasy_data_id': 15190,
  'pandascore_id': None,
  'depth_chart_position': None,
  'kalshi_id': None,
  'search_first_name': 'ryan',
  'sport': 'nfl',
  'age': 33,
  'player_shard': '3'},
 '1': {'birth_date': '1988-12-01',
  'player_id': '1',
  'yahoo_id': 26154,
  'sportradar_id': 'a668bd7d-56e5-45ff-a2c8-d618cd1fef95',
  'practice_description': None,
  'full_name': 'GJ Kinne',
  'active': False,
  'injury_status': None,
  'birth_country': None,
  'oddsjam_id': None,
  'swish_id': None,
  'first_name': 'GJ',
  'depth_chart_order': None,
  'status': 'Inactive',
  'injury_notes': None,
  'competitions': [],
  'years_exp': 1,
  'number': 2,
  'news_updated': None,
  'team_abbr': None,
  'high_school': None,
  'last_name': 'Kinne',
  'search_last_name': 'kinne',
  'espn_id': 15299,
  'injury_body_part': None,
  'practice_participation': None,
  'birth_state': None,
  'rotoworld_id': None,
  'injury_start_date': None,
  'team_changed_at': None,
  'team': None,
  'search_rank': 9999999,
  'birth_city': None,
  'rotowire_id': 8833,
  'search_full_name': 'gjkinne',
  'college': 'Tulsa',
  'position': 'QB',
  'gsis_id': None,
  'metadata': None,
  'weight': '234',
  'stats_id': 399453,
  'height': '6\'2"',
  'hashtag': '#gjkinne-NFL-FA-2',
  'fantasy_positions': ['QB'],
  'opta_id': None,
  'fantasy_data_id': 18,
  'pandascore_id': None,
  'depth_chart_position': None,
  'kalshi_id': None,
  'search_first_name': 'gj',
  'sport': 'nfl',
  'age': 28,
  'player_shard': '7'},
 '3953': {'birth_date': None,
  'player_id': '3953',
  'yahoo_id': 30080,
  'sportradar_id': '',
  'practice_description': None,
  'full_name': 'Austin Trainor',
  'active': False,
  'injury_status': None,
  'birth_country': None,
  'oddsjam_id': None,
  'swish_id': None,
  'first_name': 'Austin',
  'depth_chart_order': None,
  'status': 'Inactive',
  'injury_notes': None,
  'competitions': [],
  'years_exp': 0,
  'number': 9,
  'news_updated': None,
  'team_abbr': None,
  'high_school': None,
  'last_name': 'Trainor',
  'search_last_name': 'trainor',
  'espn_id': None,
  'injury_body_part': None,
  'practice_participation': None,
  'birth_state': None,
  'rotoworld_id': None,
  'injury_start_date': None,
  'team_changed_at': None,
  'team': None,
  'search_rank': 9999999,
  'birth_city': None,
  'rotowire_id': 11679,
  'search_full_name': 'austintrainor',
  'college': 'West Georgia',
  'position': 'QB',
  'gsis_id': None,
  'metadata': None,
  'weight': '212',
  'stats_id': 515272,
  'height': '6\'2"',
  'hashtag': '#austintrainor-NFL-FA-9',
  'fantasy_positions': ['QB'],
  'opta_id': None,
  'fantasy_data_id': 18786,
  'pandascore_id': None,
  'depth_chart_position': None,
  'kalshi_id': None,
  'search_first_name': 'austin',
  'sport': 'nfl',
  'age': None,
  'player_shard': '0'},
 '404': {'birth_date': '1972-09-21',
  'player_id': '404',
  'yahoo_id': None,
  'sportradar_id': '',
  'practice_description': None,
  'full_name': 'Jon Kitna',
  'active': False,
  'injury_status': None,
  'birth_country': None,
  'oddsjam_id': None,
  'swish_id': None,
  'first_name': 'Jon',
  'depth_chart_order': None,
  'status': 'Inactive',
  'injury_notes': None,
  'competitions': [],
  'years_exp': 24,
  'number': 3,
  'news_updated': None,
  'team_abbr': None,
  'high_school': None,
  'last_name': 'Kitna',
  'search_last_name': 'kitna',
  'espn_id': None,
  'injury_body_part': None,
  'practice_participation': None,
  'birth_state': None,
  'rotoworld_id': 28,
  'injury_start_date': None,
  'team_changed_at': None,
  'team': None,
  'search_rank': 9999999,
  'birth_city': None,
  'rotowire_id': None,
  'search_full_name': 'jonkitna',
  'college': 'Central Washington',
  'position': 'QB',
  'gsis_id': None,
  'metadata': None,
  'weight': '219',
  'stats_id': None,
  'height': '6\'2"',
  'hashtag': '#jonkitna-NFL-FA-3',
  'fantasy_positions': ['QB'],
  'opta_id': None,
  'fantasy_data_id': 8842,
  'pandascore_id': None,
  'depth_chart_position': None,
  'kalshi_id': None,
  'search_first_name': 'jon',
  'sport': 'nfl',
  'age': 47,
  'player_shard': '8'},
 '698': {'birth_date': '1982-08-06',
  'player_id': '698',
  'yahoo_id': 7830,
  'sportradar_id': '34cc7f47-9f14-4661-b9af-c9d3b2fc873a',
  'practice_description': None,
  'full_name': 'Charlie Whitehurst',
  'active': False,
  'injury_status': None,
  'birth_country': None,
  'oddsjam_id': None,
  'swish_id': None,
  'first_name': 'Charlie',
  'depth_chart_order': None,
  'status': 'Inactive',
  'injury_notes': None,
  'competitions': [],
  'years_exp': 14,
  'number': 15,
  'news_updated': None,
  'team_abbr': None,
  'high_school': 'Chattahoochee (GA)',
  'last_name': 'Whitehurst',
  'search_last_name': 'whitehurst',
  'espn_id': 9667,
  'injury_body_part': None,
  'practice_participation': None,
  'birth_state': None,
  'rotoworld_id': 3623,
  'injury_start_date': None,
  'team_changed_at': None,
  'team': None,
  'search_rank': 9999999,
  'birth_city': None,
  'rotowire_id': 4825,
  'search_full_name': 'charliewhitehurst',
  'college': 'Clemson',
  'position': 'QB',
  'gsis_id': None,
  'metadata': None,
  'weight': '226',
  'stats_id': 156595,
  'height': '6\'5"',
  'hashtag': '#charliewhitehurst-NFL-FA-15',
  'fantasy_positions': ['QB'],
  'opta_id': None,
  'fantasy_data_id': 12137,
  'pandascore_id': None,
  'depth_chart_position': None,
  'kalshi_id': None,
  'search_first_name': 'charlie',
  'sport': 'nfl',
  'age': 38,
  'player_shard': '1'},
 '7013': {'birth_date': '1997-01-14',
  'player_id': '7013',
  'yahoo_id': 33207,
  'sportradar_id': 'd446443f-130c-4bce-a300-a15cf66f27f1',
  'practice_description': None,
  'full_name': 'Steven Montez',
  'active': True,
  'injury_status': None,
  'birth_country': None,
  'oddsjam_id': None,
  'swish_id': 882704,
  'first_name': 'Steven',
  'depth_chart_order': None,
  'status': 'Active',
  'injury_notes': None,
  'competitions': [],
  'years_exp': 3,
  'number': 12,
  'news_updated': 1671732612175,
  'team_abbr': None,
  'high_school': 'Del Valle (TX)',
  'last_name': 'Montez',
  'search_last_name': 'montez',
  'espn_id': 3915436,
  'injury_body_part': None,
  'practice_participation': None,
  'birth_state': None,
  'rotoworld_id': None,
  'injury_start_date': None,
  'team_changed_at': None,
  'team': None,
  'search_rank': 9999999,
  'birth_city': None,
  'rotowire_id': 14393,
  'search_full_name': 'stevenmontez',
  'college': 'Colorado',
  'position': 'QB',
  'gsis_id': None,
  'metadata': {'channel_id': '1116853323299815424'},
  'weight': '230',
  'stats_id': None,
  'height': '77',
  'hashtag': '#stevenmontez-NFL-FA-12',
  'fantasy_positions': ['QB'],
  'opta_id': None,
  'fantasy_data_id': 21809,
  'pandascore_id': None,
  'depth_chart_position': None,
  'kalshi_id': None,
  'search_first_name': 'steven',
  'sport': 'nfl',
  'age': 26,
  'player_shard': '9'},
 '10233': {'birth_date': '2001-03-12',
  'player_id': '10233',
  'yahoo_id': None,
  'sportradar_id': 'a7ef9eec-dab5-4321-a836-af3d085b4ba4',
  'practice_description': None,
  'full_name': 'Max Duggan',
  'active': True,
  'injury_status': None,
  'birth_country': None,
  'oddsjam_id': '8174F14224A5',
  'swish_id': 1162793,
  'first_name': 'Max',
  'depth_chart_order': None,
  'status': 'Active',
  'injury_notes': None,
  'competitions': [],
  'years_exp': 1,
  'number': 8,
  'news_updated': 1724099748571,
  'team_abbr': None,
  'high_school': 'Lewis Central (IA)',
  'last_name': 'Duggan',
  'search_last_name': 'duggan',
  'espn_id': None,
  'injury_body_part': None,
  'practice_participation': None,
  'birth_state': None,
  'rotoworld_id': None,
  'injury_start_date': None,
  'team_changed_at': None,
  'team': None,
  'search_rank': 552,
  'birth_city': None,
  'rotowire_id': 16729,
  'search_full_name': 'maxduggan',
  'college': 'TCU',
  'position': 'QB',
  'gsis_id': None,
  'metadata': {'channel_id': '1113708692546547712', 'rookie_year': '2023'},
  'weight': '207',
  'stats_id': None,
  'height': '73',
  'hashtag': '#maxduggan-NFL-FA-8',
  'fantasy_positions': ['QB'],
  'opta_id': None,
  'fantasy_data_id': None,
  'pandascore_id': None,
  'depth_chart_position': None,
  'kalshi_id': None,
  'search_first_name': 'max',
  'sport': 'nfl',
  'age': 23,
  'player_shard': '9'},
 '881': {'birth_date': '1987-09-03',
  'player_id': '881',
  'yahoo_id': 24922,
  'sportradar_id': '1c32d032-ed97-4c70-8655-eecdb0fe9ccf',
  'practice_description': None,
  'full_name': 'Ricky Stanzi',
  'active': False,
  'injury_status': None,
  'birth_country': None,
  'oddsjam_id': None,
  'swish_id': None,
  'first_name': 'Ricky',
  'depth_chart_order': None,
  'status': 'Inactive',
  'injury_notes': None,
  'competitions': [],
  'years_exp': 5,
  'number': 2,

In [10]:
players = players_responses.json()

for player_id, player in players.items():
    # look for Derek Carr
    if player['first_name']=='Derek' and player['last_name']=='Carr':
        print(json.dumps(player, indent=4))

{
    "birth_date": "1991-03-28",
    "player_id": "2028",
    "yahoo_id": 27564,
    "sportradar_id": "9f026fc0-4449-4dc5-a226-2e2830619381",
    "practice_description": null,
    "full_name": "Derek Carr",
    "active": true,
    "injury_status": "NA",
    "birth_country": null,
    "oddsjam_id": "C12F49D17453",
    "swish_id": 496083,
    "first_name": "Derek",
    "depth_chart_order": null,
    "status": "Active",
    "injury_notes": null,
    "competitions": [],
    "years_exp": 11,
    "number": 4,
    "news_updated": 1786466440581,
    "team_abbr": null,
    "high_school": "Bakersfield Christian (CA)",
    "last_name": "Carr",
    "search_last_name": "carr",
    "espn_id": 16757,
    "injury_body_part": "Personal",
    "practice_participation": null,
    "birth_state": null,
    "rotoworld_id": 9349,
    "injury_start_date": null,
    "team_changed_at": null,
    "team": null,
    "search_rank": 201,
    "birth_city": null,
    "rotowire_id": 9317,
    "search_full_name": "derekcarr",
    "college": "Fresno State",
    "position": "QB",
    "gsis_id": "00-0031280",
    "metadata": {
        "channel_id": "1113708686318006272",
        "injury_override_regular_2024_6": "Out",
        "rookie_year": "2014"
    },
    "weight": "215",
    "stats_id": 496083,
    "height": "75",
    "hashtag": "#derekcarr-NFL-FA-4",
    "fantasy_positions": [
        "QB"
    ],
    "opta_id": null,
    "fantasy_data_id": 16311,
    "pandascore_id": null,
    "depth_chart_position": null,
    "kalshi_id": null,
    "search_first_name": "derek",
    "sport": "nfl",
    "age": 34,
    "player_shard": "4"
}

In [11]:
### Derek Carr Output:
"""
{
    "opta_id": null,
    "rotoworld_id": 9349,
    "birth_country": null,
    "espn_id": 16757,
    "gsis_id": "00-0031280",
    "injury_body_part": "Personal",
    "search_rank": 201,
    "kalshi_id": null,
    "metadata": {
        "channel_id": "1113708686318006272",
        "injury_override_regular_2024_6": "Out",
        "rookie_year": "2014"
    },
    "fantasy_positions": [
        "QB"
    ],
    "active": true,
    "oddsjam_id": "C12F49D17453",
    "news_updated": 1786466440581,
    "hashtag": "#derekcarr-NFL-FA-4",
    "fantasy_data_id": 16311,
    "weight": "215",
    "sport": "nfl",
    "injury_notes": null,
    "competitions": [],
    "practice_participation": null,
    "last_name": "Carr",
    "injury_status": "NA",
    "status": "Active",
    "team": null,
    "first_name": "Derek",
    "college": "Fresno State",
    "years_exp": 11,
    "pandascore_id": null,
    "team_abbr": null,
    "injury_start_date": null,
    "search_full_name": "derekcarr",
    "age": 34,
    "depth_chart_position": null,
    "high_school": "Bakersfield Christian (CA)",
    "sportradar_id": "9f026fc0-4449-4dc5-a226-2e2830619381",
    "birth_city": null,
    "number": 4,
    "player_id": "2028",
    "team_changed_at": null,
    "rotowire_id": 9317,
    "search_last_name": "carr",
    "player_shard": "4",
    "birth_date": "1991-03-28",
    "stats_id": 496083,
    "depth_chart_order": null,
    "birth_state": null,
    "full_name": "Derek Carr",
    "search_first_name": "derek",
    "position": "QB",
    "practice_description": null,
    "height": "75",
    "swish_id": 496083,
    "yahoo_id": 27564
}

"""

'\n{\n    "opta_id": null,\n    "rotoworld_id": 9349,\n    "birth_country": null,\n    "espn_id": 16757,\n    "gsis_id": "00-0031280",\n    "injury_body_part": "Personal",\n    "search_rank": 201,\n    "kalshi_id": null,\n    "metadata": {\n        "channel_id": "1113708686318006272",\n        "injury_override_regular_2024_6": "Out",\n        "rookie_year": "2014"\n    },\n    "fantasy_positions": [\n        "QB"\n    ],\n    "active": true,\n    "oddsjam_id": "C12F49D17453",\n    "news_updated": 1786466440581,\n    "hashtag": "#derekcarr-NFL-FA-4",\n    "fantasy_data_id": 16311,\n    "weight": "215",\n    "sport": "nfl",\n    "injury_notes": null,\n    "competitions": [],\n    "practice_participation": null,\n    "last_name": "Carr",\n    "injury_status": "NA",\n    "status": "Active",\n    "team": null,\n    "first_name": "Derek",\n    "college": "Fresno State",\n    "years_exp": 11,\n    "pandascore_id": null,\n    "team_abbr": null,\n    "injury_start_date": null,\n    "search_full_name": "derekcarr",\n    "age": 34,\n    "depth_chart_position": null,\n    "high_school": "Bakersfield Christian (CA)",\n    "sportradar_id": "9f026fc0-4449-4dc5-a226-2e2830619381",\n    "birth_city": null,\n    "number": 4,\n    "player_id": "2028",\n    "team_changed_at": null,\n    "rotowire_id": 9317,\n    "search_last_name": "carr",\n    "player_shard": "4",\n    "birth_date": "1991-03-28",\n    "stats_id": 496083,\n    "depth_chart_order": null,\n    "birth_state": null,\n    "full_name": "Derek Carr",\n    "search_first_name": "derek",\n    "position": "QB",\n    "practice_description": null,\n    "height": "75",\n    "swish_id": 496083,\n    "yahoo_id": 27564\n}\n\n'

# nflreadpy
docs: https://github.com/nflverse/nflreadpy <br>

In [12]:
import nflreadpy as nfl

# Load current season play-by-play data
pbp = nfl.load_pbp()

# Load player game-level stats for multiple seasons
player_stats = nfl.load_player_stats([2023])

# Load all available team level stats
team_stats = nfl.load_team_stats(seasons=True)

# nflreadpy uses Polars instead of pandas. Convert to pandas if needed:
pbp_pandas = pbp.to_pandas(use_pyarrow_extension_array=True)

In [13]:
player_stats

shape: (18_643, 150)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ player_id ┆ player_na ┆ player_di ┆ position ┆ … ┆ pt_return ┆ pt_net_ya ┆ fantasy_p ┆ fantasy_p │
│ ---       ┆ me        ┆ splay_nam ┆ ---      ┆   ┆ _tds      ┆ rds       ┆ oints     ┆ oints_ppr │
│ str       ┆ ---       ┆ e         ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ str       ┆ ---       ┆          ┆   ┆ i32       ┆ i32       ┆ f64       ┆ f64       │
│           ┆           ┆ str       ┆          ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 00-002345 ┆ A.Rodgers ┆ Aaron     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 9         ┆           ┆ Rodgers   ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002385 ┆ M.Prater  ┆ Matt      ┆ K        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 3         ┆           ┆ Prater    ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002556 ┆ N.Folk    ┆ Nick Folk ┆ K        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 5         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002619 ┆ C.Campbel ┆ Calais    ┆ DE       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 0         ┆ l         ┆ Campbell  ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002649 ┆ M.Staffor ┆ Matthew   ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 14.46     ┆ 14.46     │
│ 8         ┆ d         ┆ Stafford  ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 00-003864 ┆ B.Willis  ┆ Brayden   ┆ TE       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 3         ┆           ┆ Willis    ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003898 ┆ C.Conner  ┆ Chamarri  ┆ DB       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 2         ┆           ┆ Conner    ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003900 ┆ F.Anudike ┆ Felix Anu ┆ DE       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 6         ┆ -Uzomah   ┆ dike-Uzom ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ ah        ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003906 ┆ R.Rice    ┆ Rashee    ┆ WR       ┆ … ┆ 0         ┆ 0         ┆ 4.4       ┆ 10.4      │
│ 7         ┆           ┆ Rice      ┆          ┆   ┆           ┆           ┆           ┆           │
│ null      ┆ null      ┆ null      ┆ null     ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [14]:
pbp_pandas

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,...,out_of_bounds,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe
0,1.0,2026_01_ARI_LAC,2026091308,LAC,ARI,REG,1,<NA>,<NA>,<NA>,...,0.0,0.0,-0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,39.0,2026_01_ARI_LAC,2026091308,LAC,ARI,REG,1,ARI,away,LAC,...,0.0,0.0,0.291195,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,62.0,2026_01_ARI_LAC,2026091308,LAC,ARI,REG,1,ARI,away,LAC,...,0.0,0.0,1.730269,0.402115,5.429666,3,1.0,1.0,0.453482,54.651752
3,87.0,2026_01_ARI_LAC,2026091308,LAC,ARI,REG,1,ARI,away,LAC,...,0.0,0.0,-0.288451,<NA>,<NA>,<NA>,<NA>,<NA>,0.4028,-40.280038
4,109.0,2026_01_ARI_LAC,2026091308,LAC,ARI,REG,1,ARI,away,LAC,...,0.0,0.0,-0.889568,0.361333,4.490768,2,1.0,0.998909,0.61677,38.322973
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5657,4349.0,2026_03_ATL_GB,2026092400,GB,ATL,REG,3,GB,home,ATL,...,0.0,0.0,-0.430551,0.691338,2.050938,2,0.997139,0.288964,0.922838,7.716155
5658,4372.0,2026_03_ATL_GB,2026092400,GB,ATL,REG,3,GB,home,ATL,...,0.0,0.0,-4.340258,0.969375,1.523088,2,0.994662,0.269076,0.94326,5.674016
5659,4399.0,2026_03_ATL_GB,2026092400,GB,ATL,REG,3,ATL,away,GB,...,0.0,0.0,-0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
5660,4421.0,2026_03_ATL_GB,2026092400,GB,ATL,REG,3,ATL,away,GB,...,0.0,0.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
5661,4448.0,2026_03_ATL_GB,2026092400,GB,ATL,REG,3,ATL,away,GB,...,0.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [17]:
col_list = pbp_pandas.columns

for _ in col_list:
    print(_)

play_id
game_id
old_game_id
home_team
away_team
season_type
week
posteam
posteam_type
defteam
side_of_field
yardline_100
game_date
quarter_seconds_remaining
half_seconds_remaining
game_seconds_remaining
game_half
quarter_end
drive
sp
qtr
down
goal_to_go
time
yrdln
ydstogo
ydsnet
desc
play_type
yards_gained
shotgun
no_huddle
qb_dropback
qb_kneel
qb_spike
qb_scramble
pass_length
pass_location
air_yards
yards_after_catch
run_location
run_gap
field_goal_result
kick_distance
extra_point_result
two_point_conv_result
home_timeouts_remaining
away_timeouts_remaining
timeout
timeout_team
td_team
td_player_name
td_player_id
posteam_timeouts_remaining
defteam_timeouts_remaining
total_home_score
total_away_score
posteam_score
defteam_score
score_differential
posteam_score_post
defteam_score_post
score_differential_post
no_score_prob
opp_fg_prob
opp_safety_prob
opp_td_prob
fg_prob
safety_prob
td_prob
extra_point_prob
two_point_conversion_prob
ep
epa
total_home_epa
total_away_epa
total_home_rush_epa
total_away_rush_epa
total_home_pass_epa
total_away_pass_epa
air_epa
yac_epa
comp_air_epa
comp_yac_epa
total_home_comp_air_epa
total_away_comp_air_epa
total_home_comp_yac_epa
total_away_comp_yac_epa
total_home_raw_air_epa
total_away_raw_air_epa
total_home_raw_yac_epa
total_away_raw_yac_epa
wp
def_wp
home_wp
away_wp
wpa
vegas_wpa
vegas_home_wpa
home_wp_post
away_wp_post
vegas_wp
vegas_home_wp
total_home_rush_wpa
total_away_rush_wpa
total_home_pass_wpa
total_away_pass_wpa
air_wpa
yac_wpa
comp_air_wpa
comp_yac_wpa
total_home_comp_air_wpa
total_away_comp_air_wpa
total_home_comp_yac_wpa
total_away_comp_yac_wpa
total_home_raw_air_wpa
total_away_raw_air_wpa
total_home_raw_yac_wpa
total_away_raw_yac_wpa
punt_blocked
first_down_rush
first_down_pass
first_down_penalty
third_down_converted
third_down_failed
fourth_down_converted
fourth_down_failed
incomplete_pass
touchback
interception
punt_inside_twenty
punt_in_endzone
punt_out_of_bounds
punt_downed
punt_fair_catch
kickoff_inside_twenty
kickoff_in_endzone
kickoff_out_of_bounds
kickoff_downed
kickoff_fair_catch
fumble_forced
fumble_not_forced
fumble_out_of_bounds
solo_tackle
safety
penalty
tackled_for_loss
fumble_lost
own_kickoff_recovery
own_kickoff_recovery_td
qb_hit
rush_attempt
pass_attempt
sack
touchdown
pass_touchdown
rush_touchdown
return_touchdown
extra_point_attempt
two_point_attempt
field_goal_attempt
kickoff_attempt
punt_attempt
fumble
complete_pass
assist_tackle
lateral_reception
lateral_rush
lateral_return
lateral_recovery
passer_player_id
passer_player_name
passing_yards
receiver_player_id
receiver_player_name
receiving_yards
rusher_player_id
rusher_player_name
rushing_yards
lateral_receiver_player_id
lateral_receiver_player_name
lateral_receiving_yards
lateral_rusher_player_id
lateral_rusher_player_name
lateral_rushing_yards
lateral_sack_player_id
lateral_sack_player_name
interception_player_id
interception_player_name
lateral_interception_player_id
lateral_interception_player_name
punt_returner_player_id
punt_returner_player_name
lateral_punt_returner_player_id
lateral_punt_returner_player_name
kickoff_returner_player_name
kickoff_returner_player_id
lateral_kickoff_returner_player_id
lateral_kickoff_returner_player_name
punter_player_id
punter_player_name
kicker_player_name
kicker_player_id
own_kickoff_recovery_player_id
own_kickoff_recovery_player_name
blocked_player_id
blocked_player_name
tackle_for_loss_1_player_id
tackle_for_loss_1_player_name
tackle_for_loss_2_player_id
tackle_for_loss_2_player_name
qb_hit_1_player_id
qb_hit_1_player_name
qb_hit_2_player_id
qb_hit_2_player_name
forced_fumble_player_1_team
forced_fumble_player_1_player_id
forced_fumble_player_1_player_name
forced_fumble_player_2_team
forced_fumble_player_2_player_id
forced_fumble_player_2_player_name
solo_tackle_1_team
solo_tackle_2_team
solo_tackle_1_player_id
solo_tackle_2_player_id
solo_tackle_1_player_name
solo_tackle_2_player_name
assist_tackle_1_player_id
assist_tackle_1_player_name
assist_tackle_1_team
assist_tackle_2_player_id
assist_tackle_2_player_name
assist_tackle_2_team
assist_tackle_3_player_id
assist_tackle_3_player_name
assist_tackle_3_team
assist_tackle_4_player_id
assist_tackle_4_player_name
assist_tackle_4_team
tackle_with_assist
tackle_with_assist_1_player_id
tackle_with_assist_1_player_name
tackle_with_assist_1_team
tackle_with_assist_2_player_id
tackle_with_assist_2_player_name
tackle_with_assist_2_team
pass_defense_1_player_id
pass_defense_1_player_name
pass_defense_2_player_id
pass_defense_2_player_name
fumbled_1_team
fumbled_1_player_id
fumbled_1_player_name
fumbled_2_player_id
fumbled_2_player_name
fumbled_2_team
fumble_recovery_1_team
fumble_recovery_1_yards
fumble_recovery_1_player_id
fumble_recovery_1_player_name
fumble_recovery_2_team
fumble_recovery_2_yards
fumble_recovery_2_player_id
fumble_recovery_2_player_name
sack_player_id
sack_player_name
half_sack_1_player_id
half_sack_1_player_name
half_sack_2_player_id
half_sack_2_player_name
return_team
return_yards
penalty_team
penalty_player_id
penalty_player_name
penalty_yards
replay_or_challenge
replay_or_challenge_result
penalty_type
defensive_two_point_attempt
defensive_two_point_conv
defensive_extra_point_attempt
defensive_extra_point_conv
safety_player_name
safety_player_id
season
cp
cpoe
series
series_success
series_result
order_sequence
start_time
time_of_day
stadium
weather
nfl_api_id
play_clock
play_deleted
play_type_nfl
special_teams_play
st_play_type
end_clock_time
end_yard_line
fixed_drive
fixed_drive_result
drive_real_start_time
drive_play_count
drive_time_of_possession
drive_first_downs
drive_inside20
drive_ended_with_score
drive_quarter_start
drive_quarter_end
drive_yards_penalized
drive_start_transition
drive_end_transition
drive_game_clock_start
drive_game_clock_end
drive_start_yard_line
drive_end_yard_line
drive_play_id_started
drive_play_id_ended
away_score
home_score
location
result
total
spread_line
total_line
div_game
roof
surface
temp
wind
home_coach
away_coach
stadium_id
game_stadium
aborted_play
success
passer
passer_jersey_number
rusher
rusher_jersey_number
receiver
receiver_jersey_number
pass
rush
first_down
special
play
passer_id
rusher_id
receiver_id
name
jersey_number
id
fantasy_player_name
fantasy_player_id
fantasy
fantasy_id
out_of_bounds
home_opening_kickoff
qb_epa
xyac_epa
xyac_mean_yardage
xyac_median_yardage
xyac_success
xyac_fd
xpass
pass_oe

# Explore Player Stats from NFLVerse

In [20]:
# convert to pandas
player_stats_df = player_stats.to_pandas(use_pyarrow_extension_array=True)

player_stats_df

,player_id,player_name,player_display_name,position,position_group,headshot_url,season,week,season_type,game_id,...,pt_out_of_bounds,pt_downed,pt_touchback,pt_fair_caught,pt_returned,pt_return_yards,pt_return_tds,pt_net_yards,fantasy_points,fantasy_points_ppr
0,00-0023459,A.Rodgers,Aaron Rodgers,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_BUF_NYJ,...,0,0,0,0,0,0,0,0,0.0,0.0
1,00-0023853,M.Prater,Matt Prater,K,SPEC,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_ARI_WAS,...,0,0,0,0,0,0,0,0,0.0,0.0
2,00-0025565,N.Folk,Nick Folk,K,SPEC,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_TEN_NO,...,0,0,0,0,0,0,0,0,0.0,0.0
3,00-0026190,C.Campbell,Calais Campbell,DE,DL,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_CAR_ATL,...,0,0,0,0,0,0,0,0,0.0,0.0
4,00-0026498,M.Stafford,Matthew Stafford,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2023,1,REG,2023_01_LA_SEA,...,0,0,0,0,0,0,0,0,14.46,14.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18638,00-0038643,B.Willis,Brayden Willis,TE,TE,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,...,0,0,0,0,0,0,0,0,0.0,0.0
18639,00-0038982,C.Conner,Chamarri Conner,DB,DB,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,...,0,0,0,0,0,0,0,0,0.0,0.0
18640,00-0039006,F.Anudike-Uzomah,Felix Anudike-Uzomah,DE,DL,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,...,0,0,0,0,0,0,0,0,0.0,0.0
18641,00-0039067,R.Rice,Rashee Rice,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2023,22,POST,2023_22_SF_KC,...,0,0,0,0,0,0,0,0,4.4,10.4
18642,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2023,22,POST,2023_22_SF_KC,...,0,0,0,0,0,0,0,0,0.0,0.0

In [22]:
player_stats_list = player_stats_df.columns

for _ in player_stats_list:
    print(_)

player_id
player_name
player_display_name
position
position_group
headshot_url
season
week
season_type
game_id
team
opponent_team
completions
attempts
passing_yards
passing_tds
passing_interceptions
sacks_suffered
sack_yards_lost
sack_fumbles
sack_fumbles_lost
passing_air_yards
passing_yards_after_catch
passing_first_downs
passing_epa
passing_cpoe
passing_2pt_conversions
pacr
passing_10
passing_16
passing_20
passing_40
carries
rushing_yards
rushing_tds
rushing_fumbles
rushing_fumbles_lost
rushing_first_downs
rushing_epa
rushing_2pt_conversions
rushing_10
rushing_12
rushing_20
rushing_40
receptions
targets
receiving_yards
receiving_tds
receiving_fumbles
receiving_fumbles_lost
receiving_air_yards
receiving_yards_after_catch
receiving_first_downs
receiving_epa
receiving_2pt_conversions
receiving_10
receiving_16
receiving_20
receiving_40
racr
target_share
air_yards_share
wopr
special_teams_tds
def_tackles_solo
def_tackles_with_assist
def_tackle_assists
def_tackles_for_loss
def_tackles_for_loss_yards
def_fumbles_forced
def_sacks
def_sack_yards
def_qb_hits
def_interceptions
def_interception_yards
def_pass_defended
def_tds
def_fumbles
def_safeties
def_punt_blocks
def_pat_blocks
def_fg_blocks
def_2pt_atts
def_2pt_made
misc_yards
fumble_recovery_own
fumble_recovery_yards_own
fumble_recovery_opp
fumble_recovery_yards_opp
fumble_recovery_tds
penalties
penalty_yards
fumbles_forced_by_opp
fumbles_not_forced
fumbles_out_of_bounds
fumbles_total
fumbles_lost_total
punt_returns
punt_return_yards
kickoff_returns
kickoff_return_yards
fg_made
fg_att
fg_missed
fg_blocked
fg_long
fg_pct
fg_made_0_19
fg_made_20_29
fg_made_30_39
fg_made_40_49
fg_made_50_59
fg_made_60_
fg_missed_0_19
fg_missed_20_29
fg_missed_30_39
fg_missed_40_49
fg_missed_50_59
fg_missed_60_
fg_made_list
fg_missed_list
fg_blocked_list
fg_made_distance
fg_missed_distance
fg_blocked_distance
pat_made
pat_att
pat_missed
pat_blocked
pat_pct
gwfg_made
gwfg_att
gwfg_missed
gwfg_blocked
gwfg_distance
pt_att
pt_blocked
pt_long
pt_yards
pt_inside_20
pt_out_of_bounds
pt_downed
pt_touchback
pt_fair_caught
pt_returned
pt_return_yards
pt_return_tds
pt_net_yards
fantasy_points
fantasy_points_ppr

# Break into useful columns by position
QB <br>
RB <br>
WR/TE <br>
DEFENSE <br>