In [261]:
from dotenv import load_dotenv
import os
import requests
import json
import pandas as pd
import nflreadpy as nfl
import altair as alt

In [262]:
# adjust pandas display options to show all columns and rows
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)

alt.renderers.enable('html')

RendererRegistry.enable('html')

In [263]:
def client_cxn():
    """
    Establish a client connection to API-Sports
    """
    load_dotenv()
    api_key = os.getenv('api_key')

    hostname = 'https://v1.american-football.api-sports.io'

    # create expected headers
    headers = {
        'x-apisports-key': api_key
    }

In [264]:
# load the api secret
load_dotenv()
api_key = os.getenv('api_key')

hostname = 'https://v1.american-football.api-sports.io'

# create expected headers
headers = {
    'x-apisports-key': api_key
}

# Explore the NFL API

### Explore players endpoint
/players <br>
docs: https://api-sports.io/documentation/nfl/v1#tag/Players/operation/get-players

In [265]:
def get_players_data():
    """
    """
    pass

In [266]:
players_url = f'{hostname}/players'
player_params = {
    'id': 1
}

resp = requests.get(
    url=players_url,
    headers=headers,
    params=player_params
)

In [267]:
resp.json()

{'get': 'players',
 'parameters': {'id': '1'},
 'errors': [],
 'results': 1,
 'response': [{'id': 1,
   'name': 'Derek Carr',
   'age': 33,
   'height': '6\' 3"',
   'weight': '215 lbs',
   'college': 'Fresno State',
   'group': 'Offense',
   'position': 'QB',
   'number': 4,
   'salary': None,
   'experience': 11,
   'image': 'https://media.api-sports.io/american-football/players/1.png'}]}

### Explore the statistics API
/players/statistics <br>
docs: https://api-sports.io/documentation/nfl/v1#tag/Players/operation/get-players

In [268]:
players_stats_url = f'{hostname}/players/statistics'
player_stats_params = {
    'id': 1,
    'season':'2024'
}

resp = requests.get(
    url=players_stats_url,
    headers=headers,
    params=player_stats_params
)

In [269]:
resp.json()

{'get': 'players/statistics',
 'parameters': {'id': '1', 'season': '2024'},
 'errors': [],
 'results': 1,
 'response': [{'player': {'id': 1,
    'name': 'Derek Carr',
    'image': 'https://media.api-sports.io/american-football/players/1.png'},
   'teams': [{'team': {'id': 1,
      'name': 'Las Vegas Raiders',
      'logo': 'https://media.api-sports.io/american-football/teams/1.png'},
     'groups': [{'name': 'Passing',
       'statistics': [{'name': 'passing attempts', 'value': '502'},
        {'name': 'completions', 'value': '305'},
        {'name': 'completion pct', 'value': '60.8'},
        {'name': 'yards', 'value': '3,522'},
        {'name': 'yards per pass avg', 'value': '7.0'},
        {'name': 'yards per game', 'value': '234.8'},
        {'name': 'longest pass', 'value': '60'},
        {'name': 'passing touchdowns', 'value': '24'},
        {'name': 'passing touchdowns pct', 'value': None},
        {'name': 'interceptions', 'value': '14'},
        {'name': 'interceptions pct', 'value': None},
        {'name': 'sacks', 'value': '27'},
        {'name': 'sacked yards lost', 'value': '191'},
        {'name': 'quaterback rating', 'value': '86.3'}]},
      {'name': 'Rushing',
       'statistics': [{'name': 'rushing attempts', 'value': '24'},
        {'name': 'yards', 'value': '102'},
        {'name': 'yards per rush avg', 'value': '4.3'},
        {'name': 'longest rush', 'value': '20'},
        {'name': 'over 20 yards', 'value': '1'},
        {'name': 'rushing touchdowns', 'value': '0'},
        {'name': 'yards per game', 'value': '6.8'},
        {'name': 'fumbles', 'value': '1'},
        {'name': 'fumbles lost', 'value': '0'},
        {'name': 'rushing first downs', 'value': '10'}]}]},
    {'team': {'id': 27,
      'name': 'New Orleans Saints',
      'logo': 'https://media.api-sports.io/american-football/teams/27.png'},
     'groups': [{'name': 'Passing',
       'statistics': [{'name': 'passing attempts', 'value': '279'},
        {'name': 'completions', 'value': '189'},
        {'name': 'completion pct', 'value': '67.7'},
        {'name': 'yards', 'value': '2,145'},
        {'name': 'yards per pass avg', 'value': '7.7'},
        {'name': 'yards per game', 'value': '214.5'},
        {'name': 'longest pass', 'value': '71'},
        {'name': 'passing touchdowns', 'value': '15'},
        {'name': 'passing touchdowns pct', 'value': None},
        {'name': 'interceptions', 'value': '5'},
        {'name': 'interceptions pct', 'value': None},
        {'name': 'sacks', 'value': '8'},
        {'name': 'sacked yards lost', 'value': '48'},
        {'name': 'quaterback rating', 'value': '101.0'}]},
      {'name': 'Rushing',
       'statistics': [{'name': 'rushing attempts', 'value': '17'},
        {'name': 'yards', 'value': '71'},
        {'name': 'yards per rush avg', 'value': '4.2'},
        {'name': 'longest rush', 'value': '13'},
        {'name': 'over 20 yards', 'value': '0'},
        {'name': 'rushing touchdowns', 'value': '1'},
        {'name': 'yards per game', 'value': '7.1'},
        {'name': 'fumbles', 'value': '1'},
        {'name': 'fumbles lost', 'value': '0'},
        {'name': 'rushing first downs', 'value': '4'}]},
      {'name': 'Scoring',
       'statistics': [{'name': 'rushing touchdowns', 'value': '1'},
        {'name': 'receiving touchdowns', 'value': '0'},
        {'name': 'return touchdowns', 'value': '0'},
        {'name': 'total touchdowns', 'value': '1'},
        {'name': 'field goals', 'value': '0'},
        {'name': 'extra points', 'value': '0'},
        {'name': 'two point conversions', 'value': '0'},
        {'name': 'total points', 'value': '6'},
        {'name': 'total points per game', 'value': '0.6'}]}]}]}]}

In [270]:
# get length of player statistics output for estimation
player_stats_data = resp.json()

groups = player_stats_data['response'][0]['teams'][0]['groups']

passing_stats = groups[0]['statistics']
rushing_stats = groups[1]['statistics']

len(passing_stats), len(rushing_stats)

(14, 10)

# Explore Sleeper API for Fantasy Football Points

### Fetch all Players
/players/nfl<br>
params: position <br>
docs: https://docs.sleeper.com/#fetch-all-players

In [271]:
sleeper_hostname = 'https://api.sleeper.app/v1/'
routes = 'players/nfl'

# players url
players_url = f'{sleeper_hostname}{routes}'

params = {
    'position': 'QB'
}

players_responses = requests.get(
    url=players_url,
    params=params
)

In [272]:
# players_responses.json()

In [273]:
players = players_responses.json()

for player_id, player in players.items():
    # look for Derek Carr
    if player['first_name']=='Derek' and player['last_name']=='Carr':
        print(json.dumps(player, indent=4))

{
    "last_name": "Carr",
    "birth_country": null,
    "sport": "nfl",
    "pandascore_id": null,
    "practice_description": null,
    "rotowire_id": 9317,
    "high_school": "Bakersfield Christian (CA)",
    "search_first_name": "derek",
    "search_full_name": "derekcarr",
    "injury_notes": null,
    "active": true,
    "team_changed_at": null,
    "years_exp": 11,
    "number": 4,
    "depth_chart_order": null,
    "status": "Active",
    "kalshi_id": null,
    "player_id": "2028",
    "full_name": "Derek Carr",
    "birth_city": null,
    "fantasy_positions": [
        "QB"
    ],
    "birth_date": "1991-03-28",
    "search_last_name": "carr",
    "injury_body_part": "Personal",
    "stats_id": 496083,
    "depth_chart_position": null,
    "swish_id": 496083,
    "fantasy_data_id": 16311,
    "search_rank": 201,
    "competitions": [],
    "injury_start_date": null,
    "birth_state": null,
    "weight": "215",
    "practice_participation": null,
    "team_abbr": null,
    "metadata": {
        "channel_id": "1113708686318006272",
        "injury_override_regular_2024_6": "Out",
        "rookie_year": "2014"
    },
    "gsis_id": "00-0031280",
    "age": 34,
    "position": "QB",
    "opta_id": null,
    "first_name": "Derek",
    "espn_id": 16757,
    "rotoworld_id": 9349,
    "injury_status": "NA",
    "news_updated": 1786466440581,
    "player_shard": "4",
    "oddsjam_id": "C12F49D17453",
    "sportradar_id": "9f026fc0-4449-4dc5-a226-2e2830619381",
    "yahoo_id": 27564,
    "team": null,
    "height": "75",
    "hashtag": "#derekcarr-NFL-FA-4",
    "college": "Fresno State"
}

In [274]:
### Derek Carr Output:
"""
{
    "opta_id": null,
    "rotoworld_id": 9349,
    "birth_country": null,
    "espn_id": 16757,
    "gsis_id": "00-0031280",
    "injury_body_part": "Personal",
    "search_rank": 201,
    "kalshi_id": null,
    "metadata": {
        "channel_id": "1113708686318006272",
        "injury_override_regular_2024_6": "Out",
        "rookie_year": "2014"
    },
    "fantasy_positions": [
        "QB"
    ],
    "active": true,
    "oddsjam_id": "C12F49D17453",
    "news_updated": 1786466440581,
    "hashtag": "#derekcarr-NFL-FA-4",
    "fantasy_data_id": 16311,
    "weight": "215",
    "sport": "nfl",
    "injury_notes": null,
    "competitions": [],
    "practice_participation": null,
    "last_name": "Carr",
    "injury_status": "NA",
    "status": "Active",
    "team": null,
    "first_name": "Derek",
    "college": "Fresno State",
    "years_exp": 11,
    "pandascore_id": null,
    "team_abbr": null,
    "injury_start_date": null,
    "search_full_name": "derekcarr",
    "age": 34,
    "depth_chart_position": null,
    "high_school": "Bakersfield Christian (CA)",
    "sportradar_id": "9f026fc0-4449-4dc5-a226-2e2830619381",
    "birth_city": null,
    "number": 4,
    "player_id": "2028",
    "team_changed_at": null,
    "rotowire_id": 9317,
    "search_last_name": "carr",
    "player_shard": "4",
    "birth_date": "1991-03-28",
    "stats_id": 496083,
    "depth_chart_order": null,
    "birth_state": null,
    "full_name": "Derek Carr",
    "search_first_name": "derek",
    "position": "QB",
    "practice_description": null,
    "height": "75",
    "swish_id": 496083,
    "yahoo_id": 27564
}

"""

'\n{\n    "opta_id": null,\n    "rotoworld_id": 9349,\n    "birth_country": null,\n    "espn_id": 16757,\n    "gsis_id": "00-0031280",\n    "injury_body_part": "Personal",\n    "search_rank": 201,\n    "kalshi_id": null,\n    "metadata": {\n        "channel_id": "1113708686318006272",\n        "injury_override_regular_2024_6": "Out",\n        "rookie_year": "2014"\n    },\n    "fantasy_positions": [\n        "QB"\n    ],\n    "active": true,\n    "oddsjam_id": "C12F49D17453",\n    "news_updated": 1786466440581,\n    "hashtag": "#derekcarr-NFL-FA-4",\n    "fantasy_data_id": 16311,\n    "weight": "215",\n    "sport": "nfl",\n    "injury_notes": null,\n    "competitions": [],\n    "practice_participation": null,\n    "last_name": "Carr",\n    "injury_status": "NA",\n    "status": "Active",\n    "team": null,\n    "first_name": "Derek",\n    "college": "Fresno State",\n    "years_exp": 11,\n    "pandascore_id": null,\n    "team_abbr": null,\n    "injury_start_date": null,\n    "search_full_name": "derekcarr",\n    "age": 34,\n    "depth_chart_position": null,\n    "high_school": "Bakersfield Christian (CA)",\n    "sportradar_id": "9f026fc0-4449-4dc5-a226-2e2830619381",\n    "birth_city": null,\n    "number": 4,\n    "player_id": "2028",\n    "team_changed_at": null,\n    "rotowire_id": 9317,\n    "search_last_name": "carr",\n    "player_shard": "4",\n    "birth_date": "1991-03-28",\n    "stats_id": 496083,\n    "depth_chart_order": null,\n    "birth_state": null,\n    "full_name": "Derek Carr",\n    "search_first_name": "derek",\n    "position": "QB",\n    "practice_description": null,\n    "height": "75",\n    "swish_id": 496083,\n    "yahoo_id": 27564\n}\n\n'

# nflreadpy
docs: https://github.com/nflverse/nflreadpy <br>

In [275]:
GLOBAL_SEASONS_LIST = [2018,2019,2020,2021,2022,2023,2024,2025,2026]

In [277]:
import nflreadpy as nfl

# Load current season play-by-play data
pbp = nfl.load_pbp()

# Load player game-level stats for multiple seasons
player_stats = nfl.load_player_stats(GLOBAL_SEASONS_LIST)

# Load all available team level stats
team_stats = nfl.load_team_stats(seasons=True)

# nflreadpy uses Polars instead of pandas. Convert to pandas if needed:
pbp_pandas = pbp.to_pandas(use_pyarrow_extension_array=True)

In [278]:
player_stats

shape: (149_520, 150)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ player_id ┆ player_na ┆ player_di ┆ position ┆ … ┆ pt_return ┆ pt_net_ya ┆ fantasy_p ┆ fantasy_p │
│ ---       ┆ me        ┆ splay_nam ┆ ---      ┆   ┆ _tds      ┆ rds       ┆ oints     ┆ oints_ppr │
│ str       ┆ ---       ┆ e         ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ str       ┆ ---       ┆          ┆   ┆ i32       ┆ i32       ┆ f64       ┆ f64       │
│           ┆           ┆ str       ┆          ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 00-000409 ┆ P.Dawson  ┆ Phil      ┆ K        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 1         ┆           ┆ Dawson    ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-001691 ┆ A.Vinatie ┆ Adam      ┆ K        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 9         ┆ ri        ┆ Vinatieri ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-001959 ┆ T.Brady   ┆ Tom Brady ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 21.28     ┆ 21.28     │
│ 6         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-001964 ┆ S.Janikow ┆ Sebastian ┆ K        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 6         ┆ ski       ┆ Janikowsk ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ i         ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002053 ┆ D.Brees   ┆ Drew      ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 31.56     ┆ 31.56     │
│ 1         ┆           ┆ Brees     ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 00-004106 ┆ K.Daniels ┆ Kendal    ┆ LB       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 6         ┆           ┆ Daniels   ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-004111 ┆ H.Perkins ┆ Harold    ┆ LB       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 2         ┆           ┆ Perkins   ┆          ┆   ┆           ┆           ┆           ┆           │
│           ┆           ┆ Jr.       ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-004146 ┆ Av.Terrel ┆ Avieon    ┆ CB       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 9         ┆ l         ┆ Terrell   ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-004147 ┆ B.Cisse   ┆ Brandon   ┆ CB       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 0         ┆           ┆ Cisse     ┆          ┆   ┆           ┆           ┆           ┆           │
│ null      ┆ null      ┆ null      ┆ null     ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [279]:
pbp_pandas

,play_id,game_id,old_game_id,home_team,away_team,season_type,week,posteam,posteam_type,defteam,side_of_field,yardline_100,game_date,quarter_seconds_remaining,half_seconds_remaining,game_seconds_remaining,game_half,quarter_end,drive,sp,qtr,down,goal_to_go,time,yrdln,ydstogo,ydsnet,desc,play_type,yards_gained,shotgun,no_huddle,qb_dropback,qb_kneel,qb_spike,qb_scramble,pass_length,pass_location,air_yards,yards_after_catch,run_location,run_gap,field_goal_result,kick_distance,extra_point_result,two_point_conv_result,home_timeouts_remaining,away_timeouts_remaining,timeout,timeout_team,td_team,td_player_name,td_player_id,posteam_timeouts_remaining,defteam_timeouts_remaining,total_home_score,total_away_score,posteam_score,defteam_score,score_differential,posteam_score_post,defteam_score_post,score_differential_post,no_score_prob,opp_fg_prob,opp_safety_prob,opp_td_prob,fg_prob,safety_prob,td_prob,extra_point_prob,two_point_conversion_prob,ep,epa,total_home_epa,total_away_epa,total_home_rush_epa,total_away_rush_epa,total_home_pass_epa,total_away_pass_epa,air_epa,yac_epa,comp_air_epa,comp_yac_epa,total_home_comp_air_epa,total_away_comp_air_epa,total_home_comp_yac_epa,total_away_comp_yac_epa,total_home_raw_air_epa,total_away_raw_air_epa,total_home_raw_yac_epa,total_away_raw_yac_epa,wp,def_wp,home_wp,away_wp,wpa,vegas_wpa,vegas_home_wpa,home_wp_post,away_wp_post,vegas_wp,vegas_home_wp,total_home_rush_wpa,total_away_rush_wpa,total_home_pass_wpa,total_away_pass_wpa,air_wpa,yac_wpa,comp_air_wpa,comp_yac_wpa,total_home_comp_air_wpa,total_away_comp_air_wpa,total_home_comp_yac_wpa,total_away_comp_yac_wpa,total_home_raw_air_wpa,total_away_raw_air_wpa,total_home_raw_yac_wpa,total_away_raw_yac_wpa,punt_blocked,first_down_rush,first_down_pass,first_down_penalty,third_down_converted,third_down_failed,fourth_down_converted,fourth_down_failed,incomplete_pass,touchback,interception,punt_inside_twenty,punt_in_endzone,punt_out_of_bounds,punt_downed,punt_fair_catch,kickoff_inside_twenty,kickoff_in_endzone,kickoff_out_of_bounds,kickoff_downed,kickoff_fair_catch,fumble_forced,fumble_not_forced,fumble_out_of_bounds,solo_tackle,safety,penalty,tackled_for_loss,fumble_lost,own_kickoff_recovery,own_kickoff_recovery_td,qb_hit,rush_attempt,pass_attempt,sack,touchdown,pass_touchdown,rush_touchdown,return_touchdown,extra_point_attempt,two_point_attempt,field_goal_attempt,kickoff_attempt,punt_attempt,fumble,complete_pass,assist_tackle,lateral_reception,lateral_rush,lateral_return,lateral_recovery,passer_player_id,passer_player_name,passing_yards,receiver_player_id,receiver_player_name,receiving_yards,rusher_player_id,rusher_player_name,rushing_yards,lateral_receiver_player_id,lateral_receiver_player_name,lateral_receiving_yards,lateral_rusher_player_id,lateral_rusher_player_name,lateral_rushing_yards,lateral_sack_player_id,lateral_sack_player_name,interception_player_id,interception_player_name,lateral_interception_player_id,lateral_interception_player_name,punt_returner_player_id,punt_returner_player_name,lateral_punt_returner_player_id,lateral_punt_returner_player_name,kickoff_returner_player_name,kickoff_returner_player_id,lateral_kickoff_returner_player_id,lateral_kickoff_returner_player_name,punter_player_id,punter_player_name,kicker_player_name,kicker_player_id,own_kickoff_recovery_player_id,own_kickoff_recovery_player_name,blocked_player_id,blocked_player_name,tackle_for_loss_1_player_id,tackle_for_loss_1_player_name,tackle_for_loss_2_player_id,tackle_for_loss_2_player_name,qb_hit_1_player_id,qb_hit_1_player_name,qb_hit_2_player_id,qb_hit_2_player_name,forced_fumble_player_1_team,forced_fumble_player_1_player_id,forced_fumble_player_1_player_name,forced_fumble_player_2_team,forced_fumble_player_2_player_id,forced_fumble_player_2_player_name,solo_tackle_1_team,solo_tackle_2_team,solo_tackle_1_player_id,solo_tackle_2_player_id,solo_tackle_1_player_name,solo_tackle_2_player_name,assist_tackle_1_player_id,assist_tackle_1_player_name,assist_tackle_1_team,assist_tackle_2_player_id,assist_tackle_2_player_name,assist_tackle_2_team,assist_tackle_3_player_id,assist_tackle_3_player_name,assist_tackle_3_team,assist_tackle_4_player_id,assist_tackle_4_player_name,assist_tackle_4_team,tackle_with_assist,tackle_with_assist_1_player_id,tackle_with_assist_1_player_name,tackle_with_assist_1_team,tackle_with_assist_2_player_id,tackle_with_assist_2_player_name,tackle_with_assist_2_team,pass_defense_1_player_id,pass_defense_1_player_name,pass_defense_2_player_id,pass_defense_2_player_name,fumbled_1_team,fumbled_1_player_id,fumbled_1_player_name,fumbled_2_player_id,fumbled_2_player_name,fumbled_2_team,fumble_recovery_1_team,fumble_recovery_1_yards,fumble_recovery_1_player_id,fumble_recovery_1_player_name,fumble_recovery_2_team,fumble_recovery_2_yards,fumble_recovery_2_player_id,fumble_recovery_2_player_name,sack_player_id,sack_player_name,half_sack_1_player_id,half_sack_1_player_name,half_sack_2_player_id,half_sack_2_player_name,return_team,return_yards,penalty_team,penalty_player_id,penalty_player_name,penalty_yards,replay_or_challenge,replay_or_challenge_result,penalty_type,defensive_two_point_attempt,defensive_two_point_conv,defensive_extra_point_attempt,defensive_extra_point_conv,safety_player_name,safety_player_id,season,cp,cpoe,series,series_success,series_result,order_sequence,start_time,time_of_day,stadium,weather,nfl_api_id,play_clock,play_deleted,play_type_nfl,special_teams_play,st_play_type,end_clock_time,end_yard_line,fixed_drive,fixed_drive_result,drive_real_start_time,drive_play_count,drive_time_of_possession,drive_first_downs,drive_inside20,drive_ended_with_score,drive_quarter_start,drive_quarter_end,drive_yards_penalized,drive_start_transition,drive_end_transition,drive_game_clock_start,drive_game_clock_end,drive_start_yard_line,drive_end_yard_line,drive_play_id_started,drive_play_id_ended,away_score,home_score,location,result,total,spread_line,total_line,div_game,roof,surface,temp,wind,home_coach,away_coach,stadium_id,game_stadium,aborted_play,success,passer,passer_jersey_number,rusher,rusher_jersey_number,receiver,receiver_jersey_number,pass,rush,first_down,special,play,passer_id,rusher_id,receiver_id,name,jersey_number,id,fantasy_player_name,fantasy_player_id,fantasy,fantasy_id,out_of_bounds,home_opening_kickoff,qb_epa,xyac_epa,xyac_mean_yardage,xyac_median_yardage,xyac_success,xyac_fd,xpass,pass_oe
0,1.0,2026_01_ARI_LAC,2026091308,LAC,ARI,REG,1,<NA>,<NA>,<NA>,<NA>,<NA>,2026-09-13,900.0,1800.0,3600.0,Half1,0.0,<NA>,0.0,1.0,<NA>,0.0,15:00,LAC 35,0.0,<NA>,GAME,<NA>,<NA>,0.0,0.0,<NA>,0.0,0.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.0,3.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.008251,-0.0,0.0,0.0,0.0,0.0,0.0,0.0,<NA>,<NA>,<NA>,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.433208,0.566792,0.566792,0.433208,-0.0,-0.0,0.0,<NA>,<NA>,0.230197,0.769803,0.0,0.0,0.0,0.0,<NA>,<NA>,<NA>,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2026,<NA>,<NA>,1.0,1.0,First down,1.0,"9/13/26, 16:25:43",<NA>,SoFi Stadium,"Sunny Temp: 78° F, Humidity: 70%, Wind: SW 6 mph",a9a87603-4feb-11f1-abca-2c54536568a9,0,0.0,GAME_START,0.0,<NA>,<NA>,<NA>,1.0,Touchdown,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,26,14,Home,-12,40,8.5,47.5,0,dome,matrixturf,<NA>,<NA>,Jim Harbaugh,Jonathan Gannon,LAX01,SoFi Stadium,0.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,0.0,<NA>,0.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,0.0,-0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,39.0,2026_01_ARI_LAC,2026091308,LAC,ARI,REG,1,ARI,away,LAC,LAC,35.0,2026-09-13,900.0,1800.0,3600.0,Half1,0.0,1.0,0.0,1.0,<NA>,0.0,15:00,LAC 35,0.0,70.0,11-C.Dicker kicks 60 yards from LAC 35 to ARI ...,kickoff,0.0,0.0,0.0,0.0,0.0,0.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,60.0,<NA>,<NA>,3.0,3.0,0.0,<NA>,<NA>,<NA>,<NA>,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.003473,0.128879,0.00227,0.272088,0.208195,0.00324,0.381854,0.0,0.0,1.008251,0.291195,-0.291195,0.291195,0.0,0.0,0.0,0.0,<NA>,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.433208,0.566792,0.566792,0.433208,0.000338,-0.008101,0.008101,0.566454,0.433546,0.230197,0.769803,0.0,0.0,0.0,0.0,<NA>,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,D.Duvernay,00-0036331,<NA>,<NA>,<NA>,<NA>,C.Dicker,00-0037224,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,LAC,<NA>,00-0032146,<NA>,B.Dupree,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,ARI,25.0,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,0.0,0.0,0.0,0.0,<NA>,<NA>,2026,<NA>,<NA>,1.0,1.0,First down,39.0,"9/13/26, 16:25:43",2026-09-13T20:25:43.600Z,SoFi Stadium,"Sunny Temp: 78° F, Humidity: 70%, Wind: SW 6 mph",a9a87603-4feb-11f1-abca-2c54536568a9,0,0.0,KICK_OFF,1.0,<NA>,2026-09-13T20:25:51.047Z,<NA>,1.0,Touchdown,2026-09-13T20:25:43.600Z,11.0,6:11,5.0,1.0,1.0,1.0,1.0,0.0,KICKOFF,TOUCHDOWN,15:00,08:49,ARI 30,LAC 5,39.0,319.0,26,14,Home,-12,40,8.5,47.5,0,dome,matrixturf,<NA>,<NA>,Jim Harbaugh,Jonathan Gannon,LAX01,SoFi Stadium,0.0,1.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,0.0,0.0,1.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,0.0,0.291195,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,62.0,2026_01_ARI_LAC,2026091308,LAC,ARI,REG,1,ARI,away,LAC,ARI,70.0,2026-09-13,896.0,1796.0,3596.0,Half1,0.0,1.0,0.0,1.0,1.0,0.0,14:56,ARI 30,10.0,70.0,(14:56) 7-J.Brissett pass deep right to 85-T.M...,pass,27.0,0.0,0.0,1.0,0.0,0.0,0.0,deep,right,22.0,5.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.0,3.0,0.0,<NA>,<NA>,<NA>,<NA>,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00343,0.12719,0.002265,0.251641,0.211198,0.0033,0.400977,0.0,0.0,1.299446,1.730269,-2.021464,2.021464,0.0,0.0,-1.730269,1.730269,1.463163,0.267106,1.463163,0.267106,-1.463163,1.463163,-0.267106,0.267106,-1.463163,1.463163,-0.267106,0.267106,0.433546,0.566454,0.566454,0.433546,0.046572,0.01106,-0.01106,0.519882,0.480118,0.222096,0.777904,0.0,0.0,-0.046572,0.046572,0.0,0.046572,0.0,0.046572,0.0,0.0,-0.046572,0.046572,0.0,0.0,-0.046572,0.046572,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,00-0033119,J.Brissett,27.0,00-0037744,T.McBride,27.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,LAC,<NA>,00-0036992,<NA>,E.Molden,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,0.0,0.0,0.0,0.0,<NA>,<NA>,2026,0.521105,47.889549,1.0,1.0,First down,62.0,"9/13/26, 16:25:43",2026-09-13T20:26:27.237Z,SoFi Stadium,"Sunny Temp: 78° F, Humidity: 70%, Wind: SW 6 mph",a9a87603-4feb-11f1-abca-2c54536568a9,0,0.0,PASS,0.0,<NA>,2026-09-13T20:26:32.260Z,<NA>,1.0,Touchdown,2026-09-13T20:25:43.600Z,11.0,6:11,5.0,1.0,1.0,1.0,1.0,0.0,KICKOFF,TOUCHDOWN,15:00,08:49,ARI 30,LAC 5,39.0,319.0,26,14,Home,-12,40,8.5,47.5,0,dome,matrixturf,<NA>,<NA>,Jim Harbaugh,Jonathan Gannon,LAX01,SoFi Stadium,0.0,1.0,J.Brissett,7,<NA>,<NA>,T.McBride,85,1.0,0.0,1.0,0.0,1.0,00-0033119,<NA>,00-0037744,J.Brissett,7,00-0033119,T.McBride,00-0037744,T.McBride,00-0037744,0.0,0.0,1.730269,0.402115,5.429666,3,1.0,1.0,0.453482,54.651752
3,87.0,2026_01_ARI_LAC,2026091308,LAC,ARI,REG,1,ARI,away,LAC,LAC,43.0,2026-09-13,858.0,1758.0,3558.0,Half1,0.0,1.0,0.0,1.0,1.0,0.0,14:18,LAC 43,10.0,70.0,(14:18) (Shotgun) 22-T.Allgeier right guard to...,run,2.0,1.0,0.0,0.0,0.0,0.0,0.0,<NA>,<NA>,<NA>,<NA>,right,guard,<NA>,<NA>,<NA>,<NA>,3.0,3.0,0.0,<NA>,<NA>,<NA>,<NA>,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.003483,0.07119,0.001261,0.143111,0.299676,0.004079,0.4772,0.0,0.0,3.029715,-0.288451,-1.733012,1.733012,0.288451,-0.288451,-1.730269,1.730269,<NA>,<NA>,0.0,0.0,-1.463163,1.463163,-0.267106,0.267106,-1.463163,1.463163,-0.267106,0.267106,0.480118,0.519882,0.519882,0.480118,0.002435,0.018647,-0.018647,0.517447,0.482553,0.233157,0.766843,-0.002435,0.002435,-0.046572,0.046572,<NA>,<NA>,0.0,0.0,0.0,0.0,-0.046572,0.046572,0.0,0.0,-0.046572,0.046572,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,00-0037263,T.Allgeier,2.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,00-0033546,D.Tomlinson,LAC,00-0039111,T.Tuipulotu,LAC,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,0.0,0.0,0.0,0.0,<NA>,<NA>,2026,<NA>,<NA>,2.0,1.0,First down,87.0,"9/13/26, 16:25:43",2026-09-13T20:27:05.477Z,SoFi Stadium,"Sunny Temp: 78° F, Humidity: 70%, Wind: SW 6 mph",a9a87603-4feb-11f1-abca-2c54536568a9,0,0.0,RUSH,0.0,<NA>,2026-09-13T20:27:08.697Z,<NA>,1.0,Touchdown,2026-09-13T20:25:43.600Z,11.0,6:11,5.0,1.0,1.0,1.0,1.0,0.0,KICKOFF,TOUCHDOWN,15:00,08:49,ARI 30,LAC 5,39.0,319.0,26,14,Home,-12,40,8.5,47.5,0,dome,matrixturf,<NA>,<NA>,Jim Harbaugh,Jonathan Gannon,LAX01,SoFi Stadium,0.0,0.0,<NA>,<NA>,T.Allgeier,22,<NA>,<NA>,0.0,1.0,0.0,0.0,1.0,<NA>,00-0037263,<NA>,T.Allgeier,22,00-0037263,T.Allgeier,00-0037263,T.Allgeier,00-0037263,0.0,0.0,-0.288451,<NA>,<NA>,<NA>,<NA>,<NA>,0.4028,-40.280038
4,109.0,2026_01_ARI_LAC,2026091308,LAC,ARI,REG,1,ARI,away,LAC,LAC,41.0,2026-09-13,814.0,1714.0,3514.0,Half1,0.0,1.0,0.0,1.0,2.0,0.0,13:34,LAC 41,8.0,70.0,(13:34) (Shotgun) 7-J.Brissett pass incomplete...,pass,0.0,1.0,0.0,1.0,0.0,0.0,0.0,short,middle,11.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.0,3.0,0.0,<NA>,<NA>,<NA>,<NA>,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.003721,0.078867,0.001353,0.153728,0.314241,0.004537,0.443552,0.0,0.0,2.741264,-0.889568,-0.843445,0.843445,0.288451,-0.288451,-0.840701,0.840701,1.364321,-2.253888,0.0,0.0,-1.463163,1.463163,-0.267106,0.267106,-2.827483,2.827483,1.986783,-1.986783,0.482553,0.517447,0.517447,0.482553,-0.03252,-0.015568,0.015568,0.549967,0.450033,0.251804,0.748196,-0.002435,0.002435,-0.014052,0.014052,0.0,-0.03252,0.0,0.0,0.0,0.0,-0.046572,0.046572,0.0,0.0,-0.014052,0.014052,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,00-0033119,J.Brissett,<NA>,00-0039849,M.Harrison,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,0.0,0.0,0.0,0.0,<NA>,<NA>,2026,0.737044,-73.704445,2.0,1.0,First down,109.0,"9/13/26, 16:25:43",2026-09-13T20:27:49.310Z,SoFi Stadium,"Sunny Temp: 78° F, Humidity: 70%, Wind: SW 6 mph",a9a87603-4feb-11f1-abca-2c54536568a9,0,0.0,PASS,0.0,<NA>,2026-09-13T20:27:52.907Z,<NA>,1.0,Touchdown,2026-09-13T20:25:43.600Z,11.0,6:11,5.0,1.0,1.0,1.0,1.0,0.0,KICKOFF,TOUCHDOWN,15:00,08:49,ARI 30,LAC 5,39.0,319.0,26,14,Home,-12,40,8.5,47.5,0,dome,matrixturf,<NA>,<NA>,Jim Harbaugh,Jonathan Gannon,LAX01,SoFi Stadium,0.0,0.0,J.Brissett,7,<NA>,<NA>,M.Harrison,18,1.0,0.0,0.0,0.0,1.0,00-0033119,<NA>,00-0039849,J.Brissett,7,00-0033119,M.Harrison,00-0039849,M.Harrison,00-0039849,0.0,0.0,-0.889568,0.361333,4.490768,2,1.0,0.998909,0.61677,38.322973
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...

In [280]:
col_list = pbp_pandas.columns

for _ in col_list:
    print(_)

play_id
game_id
old_game_id
home_team
away_team
season_type
week
posteam
posteam_type
defteam
side_of_field
yardline_100
game_date
quarter_seconds_remaining
half_seconds_remaining
game_seconds_remaining
game_half
quarter_end
drive
sp
qtr
down
goal_to_go
time
yrdln
ydstogo
ydsnet
desc
play_type
yards_gained
shotgun
no_huddle
qb_dropback
qb_kneel
qb_spike
qb_scramble
pass_length
pass_location
air_yards
yards_after_catch
run_location
run_gap
field_goal_result
kick_distance
extra_point_result
two_point_conv_result
home_timeouts_remaining
away_timeouts_remaining
timeout
timeout_team
td_team
td_player_name
td_player_id
posteam_timeouts_remaining
defteam_timeouts_remaining
total_home_score
total_away_score
posteam_score
defteam_score
score_differential
posteam_score_post
defteam_score_post
score_differential_post
no_score_prob
opp_fg_prob
opp_safety_prob
opp_td_prob
fg_prob
safety_prob
td_prob
extra_point_prob
two_point_conversion_prob
ep
epa
total_home_epa
total_away_epa
total_home_rush_epa
total_away_rush_epa
total_home_pass_epa
total_away_pass_epa
air_epa
yac_epa
comp_air_epa
comp_yac_epa
total_home_comp_air_epa
total_away_comp_air_epa
total_home_comp_yac_epa
total_away_comp_yac_epa
total_home_raw_air_epa
total_away_raw_air_epa
total_home_raw_yac_epa
total_away_raw_yac_epa
wp
def_wp
home_wp
away_wp
wpa
vegas_wpa
vegas_home_wpa
home_wp_post
away_wp_post
vegas_wp
vegas_home_wp
total_home_rush_wpa
total_away_rush_wpa
total_home_pass_wpa
total_away_pass_wpa
air_wpa
yac_wpa
comp_air_wpa
comp_yac_wpa
total_home_comp_air_wpa
total_away_comp_air_wpa
total_home_comp_yac_wpa
total_away_comp_yac_wpa
total_home_raw_air_wpa
total_away_raw_air_wpa
total_home_raw_yac_wpa
total_away_raw_yac_wpa
punt_blocked
first_down_rush
first_down_pass
first_down_penalty
third_down_converted
third_down_failed
fourth_down_converted
fourth_down_failed
incomplete_pass
touchback
interception
punt_inside_twenty
punt_in_endzone
punt_out_of_bounds
punt_downed
punt_fair_catch
kickoff_inside_twenty
kickoff_in_endzone
kickoff_out_of_bounds
kickoff_downed
kickoff_fair_catch
fumble_forced
fumble_not_forced
fumble_out_of_bounds
solo_tackle
safety
penalty
tackled_for_loss
fumble_lost
own_kickoff_recovery
own_kickoff_recovery_td
qb_hit
rush_attempt
pass_attempt
sack
touchdown
pass_touchdown
rush_touchdown
return_touchdown
extra_point_attempt
two_point_attempt
field_goal_attempt
kickoff_attempt
punt_attempt
fumble
complete_pass
assist_tackle
lateral_reception
lateral_rush
lateral_return
lateral_recovery
passer_player_id
passer_player_name
passing_yards
receiver_player_id
receiver_player_name
receiving_yards
rusher_player_id
rusher_player_name
rushing_yards
lateral_receiver_player_id
lateral_receiver_player_name
lateral_receiving_yards
lateral_rusher_player_id
lateral_rusher_player_name
lateral_rushing_yards
lateral_sack_player_id
lateral_sack_player_name
interception_player_id
interception_player_name
lateral_interception_player_id
lateral_interception_player_name
punt_returner_player_id
punt_returner_player_name
lateral_punt_returner_player_id
lateral_punt_returner_player_name
kickoff_returner_player_name
kickoff_returner_player_id
lateral_kickoff_returner_player_id
lateral_kickoff_returner_player_name
punter_player_id
punter_player_name
kicker_player_name
kicker_player_id
own_kickoff_recovery_player_id
own_kickoff_recovery_player_name
blocked_player_id
blocked_player_name
tackle_for_loss_1_player_id
tackle_for_loss_1_player_name
tackle_for_loss_2_player_id
tackle_for_loss_2_player_name
qb_hit_1_player_id
qb_hit_1_player_name
qb_hit_2_player_id
qb_hit_2_player_name
forced_fumble_player_1_team
forced_fumble_player_1_player_id
forced_fumble_player_1_player_name
forced_fumble_player_2_team
forced_fumble_player_2_player_id
forced_fumble_player_2_player_name
solo_tackle_1_team
solo_tackle_2_team
solo_tackle_1_player_id
solo_tackle_2_player_id
solo_tackle_1_player_name
solo_tackle_2_player_name
assist_tackle_1_player_id
assist_tackle_1_player_name
assist_tackle_1_team
assist_tackle_2_player_id
assist_tackle_2_player_name
assist_tackle_2_team
assist_tackle_3_player_id
assist_tackle_3_player_name
assist_tackle_3_team
assist_tackle_4_player_id
assist_tackle_4_player_name
assist_tackle_4_team
tackle_with_assist
tackle_with_assist_1_player_id
tackle_with_assist_1_player_name
tackle_with_assist_1_team
tackle_with_assist_2_player_id
tackle_with_assist_2_player_name
tackle_with_assist_2_team
pass_defense_1_player_id
pass_defense_1_player_name
pass_defense_2_player_id
pass_defense_2_player_name
fumbled_1_team
fumbled_1_player_id
fumbled_1_player_name
fumbled_2_player_id
fumbled_2_player_name
fumbled_2_team
fumble_recovery_1_team
fumble_recovery_1_yards
fumble_recovery_1_player_id
fumble_recovery_1_player_name
fumble_recovery_2_team
fumble_recovery_2_yards
fumble_recovery_2_player_id
fumble_recovery_2_player_name
sack_player_id
sack_player_name
half_sack_1_player_id
half_sack_1_player_name
half_sack_2_player_id
half_sack_2_player_name
return_team
return_yards
penalty_team
penalty_player_id
penalty_player_name
penalty_yards
replay_or_challenge
replay_or_challenge_result
penalty_type
defensive_two_point_attempt
defensive_two_point_conv
defensive_extra_point_attempt
defensive_extra_point_conv
safety_player_name
safety_player_id
season
cp
cpoe
series
series_success
series_result
order_sequence
start_time
time_of_day
stadium
weather
nfl_api_id
play_clock
play_deleted
play_type_nfl
special_teams_play
st_play_type
end_clock_time
end_yard_line
fixed_drive
fixed_drive_result
drive_real_start_time
drive_play_count
drive_time_of_possession
drive_first_downs
drive_inside20
drive_ended_with_score
drive_quarter_start
drive_quarter_end
drive_yards_penalized
drive_start_transition
drive_end_transition
drive_game_clock_start
drive_game_clock_end
drive_start_yard_line
drive_end_yard_line
drive_play_id_started
drive_play_id_ended
away_score
home_score
location
result
total
spread_line
total_line
div_game
roof
surface
temp
wind
home_coach
away_coach
stadium_id
game_stadium
aborted_play
success
passer
passer_jersey_number
rusher
rusher_jersey_number
receiver
receiver_jersey_number
pass
rush
first_down
special
play
passer_id
rusher_id
receiver_id
name
jersey_number
id
fantasy_player_name
fantasy_player_id
fantasy
fantasy_id
out_of_bounds
home_opening_kickoff
qb_epa
xyac_epa
xyac_mean_yardage
xyac_median_yardage
xyac_success
xyac_fd
xpass
pass_oe

# Explore Player Stats from nflreadpy

In [281]:
# convert to pandas
player_stats_df = player_stats.to_pandas(use_pyarrow_extension_array=True)

player_stats_df

,player_id,player_name,player_display_name,position,position_group,headshot_url,season,week,season_type,game_id,team,opponent_team,completions,attempts,passing_yards,passing_tds,passing_interceptions,sacks_suffered,sack_yards_lost,sack_fumbles,sack_fumbles_lost,passing_air_yards,passing_yards_after_catch,passing_first_downs,passing_epa,passing_cpoe,passing_2pt_conversions,pacr,passing_10,passing_16,passing_20,passing_40,carries,rushing_yards,rushing_tds,rushing_fumbles,rushing_fumbles_lost,rushing_first_downs,rushing_epa,rushing_2pt_conversions,rushing_10,rushing_12,rushing_20,rushing_40,receptions,targets,receiving_yards,receiving_tds,receiving_fumbles,receiving_fumbles_lost,receiving_air_yards,receiving_yards_after_catch,receiving_first_downs,receiving_epa,receiving_2pt_conversions,receiving_10,receiving_16,receiving_20,receiving_40,racr,target_share,air_yards_share,wopr,special_teams_tds,def_tackles_solo,def_tackles_with_assist,def_tackle_assists,def_tackles_for_loss,def_tackles_for_loss_yards,def_fumbles_forced,def_sacks,def_sack_yards,def_qb_hits,def_interceptions,def_interception_yards,def_pass_defended,def_tds,def_fumbles,def_safeties,def_punt_blocks,def_pat_blocks,def_fg_blocks,def_2pt_atts,def_2pt_made,misc_yards,fumble_recovery_own,fumble_recovery_yards_own,fumble_recovery_opp,fumble_recovery_yards_opp,fumble_recovery_tds,penalties,penalty_yards,fumbles_forced_by_opp,fumbles_not_forced,fumbles_out_of_bounds,fumbles_total,fumbles_lost_total,punt_returns,punt_return_yards,kickoff_returns,kickoff_return_yards,fg_made,fg_att,fg_missed,fg_blocked,fg_long,fg_pct,fg_made_0_19,fg_made_20_29,fg_made_30_39,fg_made_40_49,fg_made_50_59,fg_made_60_,fg_missed_0_19,fg_missed_20_29,fg_missed_30_39,fg_missed_40_49,fg_missed_50_59,fg_missed_60_,fg_made_list,fg_missed_list,fg_blocked_list,fg_made_distance,fg_missed_distance,fg_blocked_distance,pat_made,pat_att,pat_missed,pat_blocked,pat_pct,gwfg_made,gwfg_att,gwfg_missed,gwfg_blocked,gwfg_distance,pt_att,pt_blocked,pt_long,pt_yards,pt_inside_20,pt_out_of_bounds,pt_downed,pt_touchback,pt_fair_caught,pt_returned,pt_return_yards,pt_return_tds,pt_net_yards,fantasy_points,fantasy_points_ppr
0,00-0004091,P.Dawson,Phil Dawson,K,SPEC,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_WAS_ARI,ARI,WAS,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,<NA>,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,<NA>,0.0,0.0,0.0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0.0,0.0
1,00-0016919,A.Vinatieri,Adam Vinatieri,K,SPEC,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_CIN_IND,IND,CIN,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,<NA>,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,<NA>,0.0,0.0,0.0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,4,1,0,51,0.75,0,1,1,0,1,0,0,0,0,0,1,0,21;38;51,55,<NA>,110,55,0,2,2,0,0,1.0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0.0,0.0
2,00-0019596,T.Brady,Tom Brady,QB,QB,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_HOU_NE,NE,HOU,26,39,277,3,1,2,-10,0,0,320,93,16,8.182894,2.007506,0,0.865625,13,4,4,0,1,2,0,0,0,1,1.837627,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,<NA>,0.0,0.0,0.0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,21.28,21.28
3,00-0019646,S.Janikowski,Sebastian Janikowski,K,SPEC,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_SEA_DEN,SEA,DEN,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,<NA>,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,<NA>,0.0,0.0,0.0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2,1,0,35,0.5,0,0,1,0,0,0,0,0,0,1,0,0,35,46,<NA>,35,46,0,3,3,0,0,1.0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0.0,0.0
4,00-0020531,D.Brees,Drew Brees,QB,QB,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_TB_NO,NO,TB,37,45,439,3,0,1,-7,0,0,348,167,19,23.326556,13.136177,1,1.261494,17,9,6,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,<NA>,0.0,0.0,0.0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,31.56,31.56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149515,00-0041066,K.Daniels,Kendal Daniels,LB,LB,https://static.www.nfl.com/image/upload/f_auto...,2026,3,REG,2026_03_ATL_GB,ATL,GB,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,<NA>,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,<NA>,0.0,0.0,0.0,0,2,0,1,1,3,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0.0,0.0
149516,00-0041112,H.Perkins,Harold Perkins Jr.,LB,LB,https://static.www.nfl.com/image/upload/f_auto...,2026,3,REG,2026_03_ATL_GB,ATL,GB,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,<NA>,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,<NA>,0.0,0.0,0.0,0,2,0,2,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,15,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0.0,0.0
149517,00-0041469,Av.Terrell,Avieon Terrell,CB,DB,https://static.www.nfl.com/image/upload/f_auto...,2026,3,REG,2026_03_ATL_GB,ATL,GB,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,<NA>,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,<NA>,0.0,0.0,0.0,0,0,0,1,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0.0,0.0
149518,00-0041470,B.Cisse,Brandon Cisse,CB,DB,https://static.www.nfl.com/image/upload/f_auto...,2026,3,REG,2026_03_ATL_GB,GB,ATL,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,<NA>,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,<NA>,0.0,0.0,0.0,0,4,0,3,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,5,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0.0,0.0
149519,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2026,3,REG,2026_03_ATL_GB,ATL,GB,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,<NA>,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,<NA>,0.0,0.0,0.0,0,0,0,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,10,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,<NA>,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,0,0,0,0,0,0.0,0.0

In [282]:
player_stats_list = player_stats_df.columns

for _ in player_stats_list:
    print(_)

player_id
player_name
player_display_name
position
position_group
headshot_url
season
week
season_type
game_id
team
opponent_team
completions
attempts
passing_yards
passing_tds
passing_interceptions
sacks_suffered
sack_yards_lost
sack_fumbles
sack_fumbles_lost
passing_air_yards
passing_yards_after_catch
passing_first_downs
passing_epa
passing_cpoe
passing_2pt_conversions
pacr
passing_10
passing_16
passing_20
passing_40
carries
rushing_yards
rushing_tds
rushing_fumbles
rushing_fumbles_lost
rushing_first_downs
rushing_epa
rushing_2pt_conversions
rushing_10
rushing_12
rushing_20
rushing_40
receptions
targets
receiving_yards
receiving_tds
receiving_fumbles
receiving_fumbles_lost
receiving_air_yards
receiving_yards_after_catch
receiving_first_downs
receiving_epa
receiving_2pt_conversions
receiving_10
receiving_16
receiving_20
receiving_40
racr
target_share
air_yards_share
wopr
special_teams_tds
def_tackles_solo
def_tackles_with_assist
def_tackle_assists
def_tackles_for_loss
def_tackles_for_loss_yards
def_fumbles_forced
def_sacks
def_sack_yards
def_qb_hits
def_interceptions
def_interception_yards
def_pass_defended
def_tds
def_fumbles
def_safeties
def_punt_blocks
def_pat_blocks
def_fg_blocks
def_2pt_atts
def_2pt_made
misc_yards
fumble_recovery_own
fumble_recovery_yards_own
fumble_recovery_opp
fumble_recovery_yards_opp
fumble_recovery_tds
penalties
penalty_yards
fumbles_forced_by_opp
fumbles_not_forced
fumbles_out_of_bounds
fumbles_total
fumbles_lost_total
punt_returns
punt_return_yards
kickoff_returns
kickoff_return_yards
fg_made
fg_att
fg_missed
fg_blocked
fg_long
fg_pct
fg_made_0_19
fg_made_20_29
fg_made_30_39
fg_made_40_49
fg_made_50_59
fg_made_60_
fg_missed_0_19
fg_missed_20_29
fg_missed_30_39
fg_missed_40_49
fg_missed_50_59
fg_missed_60_
fg_made_list
fg_missed_list
fg_blocked_list
fg_made_distance
fg_missed_distance
fg_blocked_distance
pat_made
pat_att
pat_missed
pat_blocked
pat_pct
gwfg_made
gwfg_att
gwfg_missed
gwfg_blocked
gwfg_distance
pt_att
pt_blocked
pt_long
pt_yards
pt_inside_20
pt_out_of_bounds
pt_downed
pt_touchback
pt_fair_caught
pt_returned
pt_return_yards
pt_return_tds
pt_net_yards
fantasy_points
fantasy_points_ppr

# Break into useful columns by position
QB <br>
RB <br>
WR/TE <br>
DEFENSE <br>
<br>
### Useful for all positions: <br>
player_id
player_name
player_display_name
position
position_group
headshot_url
season
week
season_type
game_id
team
opponent_team
<br>

### Useful for QB <br>
completions
attempts
passing_yards
passing_tds
passing_interceptions
sacks_suffered
sack_yards_lost
sack_fumbles
sack_fumbles_lost
passing_air_yards
passing_yards_after_catch
passing_first_downs
passing_epa
passing_cpoe
passing_2pt_conversions
pacr
passing_10
passing_16
passing_20
passing_40
carries
rushing_yards
rushing_tds
rushing_fumbles
rushing_fumbles_lost
rushing_first_downs
rushing_epa
rushing_2pt_conversions
rushing_10
rushing_12
rushing_20
rushing_40
<br>

### Useful for RB: <br>
carries
rushing_yards
rushing_tds
rushing_fumbles
rushing_fumbles_lost
rushing_first_downs
rushing_epa
rushing_2pt_conversions
rushing_10
rushing_12
rushing_20
rushing_40
receptions
targets
receiving_yards
receiving_tds
receiving_fumbles
receiving_fumbles_lost
receiving_air_yards
receiving_yards_after_catch
receiving_first_downs
receiving_epa
receiving_2pt_conversions
receiving_10
receiving_16
receiving_20
receiving_40
racr
target_share
air_yards_share
<br>

### Useful for WR: <br>
receptions
targets
receiving_yards
receiving_tds
receiving_fumbles
receiving_fumbles_lost
receiving_air_yards
receiving_yards_after_catch
receiving_first_downs
receiving_epa
receiving_2pt_conversions
receiving_10
receiving_16
receiving_20
receiving_40
racr
target_share
air_yards_share
<br>

### Useful for Defense: <br>
def_tackles_solo
def_tackles_with_assist
def_tackle_assists
def_tackles_for_loss
def_tackles_for_loss_yards
def_fumbles_forced
def_sacks
def_sack_yards
def_qb_hits
def_interceptions
def_interception_yards
def_pass_defended
def_tds
def_fumbles
def_safeties
def_punt_blocks
def_pat_blocks
def_fg_blocks
def_2pt_atts
def_2pt_made
misc_yards
fumble_recovery_own
fumble_recovery_yards_own
fumble_recovery_opp
fumble_recovery_yards_opp
fumble_recovery_tds

In [283]:
# columns lists
all_positions_cols = [
    'player_id',
    'player_name',
    'player_display_name',
    'position',
    'position_group',
    'headshot_url',
    'season',
    'week',
    'season_type',
    'game_id',
    'team',
    'opponent_team',
]

qb_cols = [
    'completions',
    'attempts',
    'passing_yards',
    'passing_tds',
    'passing_interceptions',
    'sacks_suffered',
    'sack_yards_lost',
    'sack_fumbles',
    'sack_fumbles_lost',
    'passing_air_yards',
    'passing_yards_after_catch',
    'passing_first_downs',
    'passing_epa',
    'passing_cpoe',
    'passing_2pt_conversions',
    'pacr',
    'passing_10',
    'passing_16',
    'passing_20',
    'passing_40',
    'carries',
    'rushing_yards',
    'rushing_tds',
    'rushing_fumbles',
    'rushing_fumbles_lost',
    'rushing_first_downs',
    'rushing_epa',
    'rushing_2pt_conversions',
    'rushing_10',
    'rushing_12',
    'rushing_20',
    'rushing_40'
]

rb_cols = [
    'carries',
    'rushing_yards',
    'rushing_tds',
    'rushing_fumbles',
    'rushing_fumbles_lost',
    'rushing_first_downs',
    'rushing_epa',
    'rushing_2pt_conversions',
    'rushing_10',
    'rushing_12',
    'rushing_20',
    'rushing_40',
    'receptions',
    'targets',
    'receiving_yards',
    'receiving_tds',
    'receiving_fumbles',
    'receiving_fumbles_lost',
    'receiving_air_yards',
    'receiving_yards_after_catch',
    'receiving_first_downs',
    'receiving_epa',
    'receiving_2pt_conversions',
    'receiving_10',
    'receiving_16',
    'receiving_20',
    'receiving_40',
    'racr',
    'target_share',
    'air_yards_share'
]

wr_cols = [
    'receptions',
    'targets',
    'receiving_yards',
    'receiving_tds',
    'receiving_fumbles',
    'receiving_fumbles_lost',
    'receiving_air_yards',
    'receiving_yards_after_catch',
    'receiving_first_downs',
    'receiving_epa',
    'receiving_2pt_conversions',
    'receiving_10',
    'receiving_16',
    'receiving_20',
    'receiving_40',
    'racr',
    'target_share',
    'air_yards_share'
]

def_cols = [
    'def_tackles_solo',
    'def_tackles_with_assist',
    'def_tackle_assists',
    'def_tackles_for_loss',
    'def_tackles_for_loss_yards',
    'def_fumbles_forced',
    'def_sacks',
    'def_sack_yards',
    'def_qb_hits',
    'def_interceptions',
    'def_interception_yards',
    'def_pass_defended',
    'def_tds',
    'def_fumbles',
    'def_safeties',
    'def_punt_blocks',
    'def_pat_blocks',
    'def_fg_blocks',
    'def_2pt_atts',
    'def_2pt_made',
    'misc_yards',
    'fumble_recovery_own',
    'fumble_recovery_yards_own',
    'fumble_recovery_opp',
    'fumble_recovery_yards_opp',
    'fumble_recovery_tds'
]

In [284]:
# explore all position cols
player_stats_df[all_positions_cols]

,player_id,player_name,player_display_name,position,position_group,headshot_url,season,week,season_type,game_id,team,opponent_team
0,00-0004091,P.Dawson,Phil Dawson,K,SPEC,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_WAS_ARI,ARI,WAS
1,00-0016919,A.Vinatieri,Adam Vinatieri,K,SPEC,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_CIN_IND,IND,CIN
2,00-0019596,T.Brady,Tom Brady,QB,QB,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_HOU_NE,NE,HOU
3,00-0019646,S.Janikowski,Sebastian Janikowski,K,SPEC,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_SEA_DEN,SEA,DEN
4,00-0020531,D.Brees,Drew Brees,QB,QB,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_TB_NO,NO,TB
...,...,...,...,...,...,...,...,...,...,...,...,...
149515,00-0041066,K.Daniels,Kendal Daniels,LB,LB,https://static.www.nfl.com/image/upload/f_auto...,2026,3,REG,2026_03_ATL_GB,ATL,GB
149516,00-0041112,H.Perkins,Harold Perkins Jr.,LB,LB,https://static.www.nfl.com/image/upload/f_auto...,2026,3,REG,2026_03_ATL_GB,ATL,GB
149517,00-0041469,Av.Terrell,Avieon Terrell,CB,DB,https://static.www.nfl.com/image/upload/f_auto...,2026,3,REG,2026_03_ATL_GB,ATL,GB
149518,00-0041470,B.Cisse,Brandon Cisse,CB,DB,https://static.www.nfl.com/image/upload/f_auto...,2026,3,REG,2026_03_ATL_GB,GB,ATL
149519,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2026,3,REG,2026_03_ATL_GB,ATL,GB

# Break out into dataframes by position [QB, RB, WR/TW, DEFENSE]

In [285]:
# column lists for position mapping
wr_te_pos_list = ['WR', 'TE']
def_pos_list = ['DE', 'DT', 'LB', 'CB', 'S', 'FS', 'MLB', 'NT', 'ILB', 'DL', 'DB']
special_teams_pos_list = ['K', 'P', 'LS']

In [286]:
all_positions = player_stats_df[all_positions_cols]['position'].unique()


qb_df = player_stats_df[player_stats_df['position']=='QB'][all_positions_cols + qb_cols]
rb_df = player_stats_df[player_stats_df['position']=='RB'][all_positions_cols + rb_cols]
wr_df = player_stats_df[(player_stats_df['position'].isin(wr_te_pos_list))][all_positions_cols + wr_cols]
def_df = player_stats_df[player_stats_df['position'].isin(def_pos_list)][all_positions_cols + def_cols]

all_positions

<ArrowExtensionArray>
[  'K',  'QB',  'DE',  'TE', 'OLB',  'FS',   'P',  'WR',  'LS',  'LB',  'DB',
  'RB',  'DT',  'CB',  'NT',   'C', 'ILB',   'G',  'OT',   'S',  'FB',  'DL',
 'MLB', 'SAF',  <NA>,  'OL']
Length: 26, dtype: large_string[pyarrow]

# Explore QB DataFrame

In [287]:
qb_df

,player_id,player_name,player_display_name,position,position_group,headshot_url,season,week,season_type,game_id,team,opponent_team,completions,attempts,passing_yards,passing_tds,passing_interceptions,sacks_suffered,sack_yards_lost,sack_fumbles,sack_fumbles_lost,passing_air_yards,passing_yards_after_catch,passing_first_downs,passing_epa,passing_cpoe,passing_2pt_conversions,pacr,passing_10,passing_16,passing_20,passing_40,carries,rushing_yards,rushing_tds,rushing_fumbles,rushing_fumbles_lost,rushing_first_downs,rushing_epa,rushing_2pt_conversions,rushing_10,rushing_12,rushing_20,rushing_40
2,00-0019596,T.Brady,Tom Brady,QB,QB,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_HOU_NE,NE,HOU,26,39,277,3,1,2,-10,0,0,320,93,16,8.182894,2.007506,0,0.865625,13,4,4,0,1,2,0,0,0,1,1.837627,0,0,0,0,0
4,00-0020531,D.Brees,Drew Brees,QB,QB,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_TB_NO,NO,TB,37,45,439,3,0,1,-7,0,0,348,167,19,23.326556,13.136177,1,1.261494,17,9,6,0,0,0,0,0,0,0,<NA>,0,0,0,0,0
10,00-0022803,E.Manning,Eli Manning,QB,QB,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_JAX_NYG,NYG,JAX,23,37,224,0,1,2,-14,0,0,249,86,8,-11.798196,-4.550693,0,0.899598,12,6,2,0,1,2,0,0,0,0,-0.408166,0,0,0,0,0
13,00-0022924,B.Roethlisberger,Ben Roethlisberger,QB,QB,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_PIT_CLE,PIT,CLE,23,41,335,1,3,4,-22,2,2,382,213,17,-6.687471,-9.987982,0,0.876963,15,7,4,1,3,16,0,0,0,2,3.017745,0,1,1,0,0
14,00-0022942,P.Rivers,Philip Rivers,QB,QB,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_KC_LAC,LAC,KC,34,51,424,3,1,1,-6,0,0,483,249,23,16.117956,3.663464,1,0.877847,19,12,8,0,0,0,0,0,0,0,<NA>,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149288,00-0040691,J.Dart,Jaxson Dart,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2026,2,REG,2026_02_NYG_LA,NYG,LA,3,5,20,0,0,0,0,0,0,47,2,2,-1.115789,-5.341377,0,0.425532,1,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0
149310,00-0040743,T.Shough,Tyler Shough,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2026,2,REG,2026_02_NO_BAL,NO,BAL,27,34,252,1,0,3,-19,0,0,213,115,11,10.928983,14.051038,0,1.183099,11,5,5,0,9,23,1,1,0,3,1.659559,0,1,0,0,0
149386,00-0041194,J.Strand,Jack Strand,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2026,2,REG,2026_02_CAR_ATL,ATL,CAR,8,15,59,0,1,2,-13,1,1,53,52,4,-12.859613,-21.318088,0,1.113208,3,0,0,0,2,16,0,0,0,2,1.479441,0,0,0,0,0
149465,00-0036264,J.Love,Jordan Love,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2026,3,REG,2026_03_ATL_GB,GB,ATL,28,53,312,2,1,1,-1,0,0,392,134,15,3.571209,-8.510311,0,0.795918,13,4,4,1,1,0,0,1,0,0,-0.352746,0,0,0,0,0
149503,00-0039917,M.Penix,Michael Penix Jr.,QB,QB,https://static.www.nfl.com/image/upload/f_auto...,2026,3,REG,2026_03_ATL_GB,ATL,GB,18,25,256,1,1,0,0,0,0,149,167,8,9.511075,8.774337,1,1.718121,8,7,3,2,2,-2,0,0,0,0,0.0,0,0,0,0,0

In [288]:

qb_season_agg = qb_df.groupby(['player_id', 'player_name', 'position', 'season']).agg({
    'completions': 'sum',
    'attempts': 'sum',
    'passing_yards': 'sum',
    'passing_tds': 'sum',
    'passing_interceptions': 'sum',
    'sacks_suffered': 'sum',
    'sack_yards_lost': 'sum',
    'sack_fumbles': 'sum',
    'sack_fumbles_lost': 'sum',
    'passing_air_yards': 'sum',
    'passing_yards_after_catch': 'sum',
    'passing_first_downs': 'sum',
    'passing_epa': 'sum',
    'passing_cpoe': 'mean'
})

# games played per season
qb_season_agg['total_games_played'] = qb_df.groupby(['player_id', 'player_name', 'position', 'season']).size()

# calculate completion percentage
qb_season_agg['completion_percentage'] = qb_season_agg['completions'] / qb_season_agg['attempts'] * 100

# calculate passing yards per game
qb_season_agg['passing_yards_per_game'] = qb_season_agg['passing_yards'] / qb_season_agg['total_games_played']

qb_season_agg = qb_season_agg.reset_index()

qb_season_agg

,player_id,player_name,position,season,completions,attempts,passing_yards,passing_tds,passing_interceptions,sacks_suffered,sack_yards_lost,sack_fumbles,sack_fumbles_lost,passing_air_yards,passing_yards_after_catch,passing_first_downs,passing_epa,passing_cpoe,total_games_played,completion_percentage,passing_yards_per_game
0,00-0019596,T.Brady,QB,2018,460,695,5308,31,14,22,-156,5,2,5324,2615,255,115.462924,0.069497,19,66.18705,279.368421
1,00-0019596,T.Brady,QB,2019,393,650,4266,24,9,27,-185,2,1,4942,1997,204,28.486658,-2.665673,17,60.461538,250.941176
2,00-0019596,T.Brady,QB,2020,482,748,5694,50,15,27,-180,1,0,6903,2256,288,172.656932,2.726373,20,64.438503,284.7
3,00-0019596,T.Brady,QB,2021,544,810,5916,46,13,29,-193,4,3,6400,2851,297,139.038767,1.533633,19,67.160494,311.368421
4,00-0019596,T.Brady,QB,2022,525,799,5045,27,10,24,-177,3,2,5387,2484,257,56.645483,0.218037,18,65.707134,280.277778
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
676,00-0040691,J.Dart,QB,2026,26,34,250,3,0,2,-1,1,0,292,88,16,20.796663,4.02109,2,76.470588,125.0
677,00-0040704,D.Gabriel,QB,2025,110,185,937,7,2,19,-127,0,0,1078,500,45,-44.897842,-3.919477,10,59.459459,93.7
678,00-0040743,T.Shough,QB,2025,221,327,2384,10,6,31,-195,2,1,2708,1051,107,2.059939,-2.748456,11,67.584098,216.727273
679,00-0040743,T.Shough,QB,2026,62,90,662,4,2,8,-51,1,1,696,231,30,9.921663,6.422717,2,68.888889,331.0
680,00-0041194,J.Strand,QB,2026,8,15,59,0,1,2,-13,1,1,53,52,4,-12.859613,-21.318088,1,53.333333,59.0

In [298]:
describe_cols = ['total_games_played', 'completions', 'passing_yards', 'passing_tds', 'passing_interceptions', 'passing_yards_per_game']
qb_season_agg.describe()[describe_cols]

,total_games_played,completions,passing_yards,passing_tds,passing_interceptions,passing_yards_per_game
count,681.000000,681.0,681.0,681.0,681.0,681.0
mean,7.917768,144.390602,1596.268722,10.035242,5.052863,154.406034
std,6.108744,150.025783,1695.195903,12.056189,5.105663,95.391315
min,1.000000,0.0,-2.0,0.0,0.0,-1.0
25%,2.000000,18.0,185.0,1.0,1.0,66.0
50%,6.000000,73.0,754.0,4.0,3.0,177.0
75%,14.000000,262.0,2942.0,17.0,9.0,232.615385
max,21.000000,544.0,6074.0,53.0,30.0,371.2

In [313]:
res = qb_season_agg[qb_season_agg['season']==2024]

res

,player_id,player_name,position,season,completions,attempts,passing_yards,passing_tds,passing_interceptions,sacks_suffered,sack_yards_lost,sack_fumbles,sack_fumbles_lost,passing_air_yards,passing_yards_after_catch,passing_first_downs,passing_epa,passing_cpoe,total_games_played,completion_percentage,passing_yards_per_game
31,00-0023459,A.Rodgers,QB,2024,368,584,3897,28,11,40,-302,5,2,4022,2119,192,11.295307,-2.348851,17,63.013699,229.235294
53,00-0026158,J.Flacco,QB,2024,162,248,1761,12,7,18,-123,3,3,2215,651,87,2.052386,0.712482,7,65.322581,251.571429
62,00-0026300,J.Johnson,QB,2024,2,3,17,0,0,1,-5,0,0,53,2,1,-1.809736,37.297462,4,66.666667,4.25
70,00-0026498,M.Stafford,QB,2024,385,588,4295,24,8,35,-253,5,3,4511,1905,201,41.920346,-0.767807,18,65.47619,238.611111
108,00-0027973,A.Dalton,QB,2024,106,160,989,7,6,7,-37,0,0,1062,459,50,-19.042891,-12.341451,6,66.25,164.833333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
651,00-0039732,B.Nix,QB,2024,389,589,3919,30,12,26,-212,1,0,4376,2102,176,27.003512,0.318065,18,66.044143,217.722222
654,00-0039851,D.Maye,QB,2024,225,338,2276,15,10,34,-229,5,4,2473,1192,112,-26.453309,-5.642977,13,66.568047,175.076923
657,00-0039910,J.Daniels,QB,2024,406,594,4390,30,10,51,-265,2,0,4275,2212,213,91.113492,4.225335,20,68.350168,219.5
660,00-0039917,M.Penix,QB,2024,61,105,775,3,3,4,-14,2,0,1073,271,35,14.553117,3.507621,5,58.095238,155.0
663,00-0039918,C.Williams,QB,2024,351,562,3541,20,6,68,-466,6,3,4486,1866,171,-47.274843,0.055146,17,62.455516,208.294118

In [ ]:
def calculate_mean_passing_stats_by_year(df:pd.DataFrame, year:int)-> tuple[float, float, float, float, float, float]:
    """
    """
    # filter for specified year
    season_df = df[df['season']==year]

    # get stats 
    avg_total_games_played = season_df['total_games_played'].mean()
    avg_completions = season_df['completions'].mean()
    avg_passing_yards = season_df['passing_yards'].mean()
    avg_passing_tds = season_df['passing_tds'].mean()
    avg_passing_interceptions = season_df['passing_interceptions'].mean()
    avg_passing_yards_per_game = season_df['passing_yards_per_game'].mean()

    return (avg_total_games_played, avg_completions, avg_passing_yards, avg_passing_tds, avg_passing_interceptions, avg_passing_yards_per_game)

In [317]:
year = 2024

avg_total_games_played, avg_completions, avg_passing_yards, avg_passing_tds, avg_passing_interceptions, avg_passing_yards_per_game = calculate_mean_passing_stats_by_year(qb_season_agg, year)

avg_total_games_played

np.float64(8.822784810126583)

In [300]:
"""
Create additional useful statistics
- Descriptive statistics for games played, completions, passing yards, passing touchdowns, passing interceptions, passing yards per game
"""
describe_cols = ['total_games_played', 'completions', 'passing_yards', 'passing_tds', 'passing_interceptions', 'passing_yards_per_game']
qb_season_agg.describe()[describe_cols]

avg_total_games_played = qb_season_agg['total_games_played'].mean()
avg_completions = qb_season_agg['completions'].mean()
avg_passing_yards = qb_season_agg['passing_yards'].mean()
avg_passing_tds = qb_season_agg['passing_tds'].mean()
avg_passing_interceptions = qb_season_agg['passing_interceptions'].mean()
avg_passing_yards_per_game = qb_season_agg['passing_yards_per_game'].mean()

median_total_games_played = qb_season_agg['total_games_played'].median()
median_completions = qb_season_agg['completions'].median()
median_passing_yards = qb_season_agg['passing_yards'].median()
median_passing_tds = qb_season_agg['passing_tds'].median()
median_passing_interceptions = qb_season_agg['passing_interceptions'].median()
median_passing_yards_per_game = qb_season_agg['passing_yards_per_game'].median()

In [307]:
type(avg_total_games_played)

numpy.float64

# Visuals for QB Data<br>
TODO
- Place a limit on number of games minimum before including in stats to remove outliers
- Determine bin size for histogram
- Create histogram

In [289]:
# create lists for filters
season_list = GLOBAL_SEASONS_LIST
player_list = qb_season_agg['player_name'].unique().tolist()

In [ ]:
season_filter = alt.param(
    name = 'selected_season',
    value = 2023,
    bind = alt.binding_select(
        options = season_list,
        name = 'Season'
    )
)

bar_chart_passing_yards = (alt.Chart(qb_season_agg).mark_bar().encode(
    x=alt.X('player_name:N', title='Player Name'),
    y=alt.Y('passing_yards:Q', title='Passing Yards'),
    color=alt.Color('season:N', title='Season'),
    tooltip=['player_name', 
             'season', 
             'passing_yards', 
             'passing_tds', 
             'passing_interceptions', 
             'completion_percentage', 
             'passing_yards_per_game']
).add_params(season_filter)
.transform_filter(alt.datum.season == season_filter)
).properties(
    title='Passing Yards by Player and Season'
).interactive()

mean_passing_yards_line = (
    alt.Chart(qb_season_agg).transform_filter(alt.datum.season == season_filter)
    .transform_calculate(
        statistic="'Mean Passing Yards'"
    )
    .mark_rule(
        strokeWidth=2
    )
    .encode(
        y=alt.Y(
            'mean(passing_yards):Q',
            title='Mean Passing Yards'
        ),
    color=alt.Color(
        'statistic:N',
        scale=alt.Scale(
            domain = ['Mean Passing Yards'],
            range = ['red']
        )
    )
)
)

chart = (
    bar_chart_passing_yards + mean_passing_yards_line).resolve_scale(color='independent')

chart

alt.LayerChart(...)

In [348]:
# boxplot for passing yards by season
boxplot_passing_yards = (
    alt.Chart(qb_season_agg).mark_boxplot().encode(
        x=alt.X('season:N', title='Season'),
        y=alt.Y('passing_yards:Q', title='Passing Yards'),
        color=alt.Color('season:N', title='Season')
    )
    .properties(
        width = 750,
        height = 100,
        title = 'Passing Yards by Season'
    )
)

boxplot_passing_yards

alt.Chart(...)

# Explore Passing Performance Relationships <br>
- Passing Yards and Total Touchdowns
- Completions and Total Touchdowns

# Explore RB DataFrame

In [253]:
rb_df

,player_id,player_name,player_display_name,position,position_group,headshot_url,season,week,season_type,game_id,team,opponent_team,carries,rushing_yards,rushing_tds,rushing_fumbles,rushing_fumbles_lost,rushing_first_downs,rushing_epa,rushing_2pt_conversions,rushing_10,rushing_12,rushing_20,rushing_40,receptions,targets,receiving_yards,receiving_tds,receiving_fumbles,receiving_fumbles_lost,receiving_air_yards,receiving_yards_after_catch,receiving_first_downs,receiving_epa,receiving_2pt_conversions,receiving_10,receiving_16,receiving_20,receiving_40,racr,target_share,air_yards_share
25,00-0023500,F.Gore,Frank Gore,RB,RB,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_TEN_MIA,MIA,TEN,9,61,0,0,0,3,0.692005,0,2,1,1,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,<NA>,0.0,0.0
27,00-0023564,D.Sproles,Darren Sproles,RB,RB,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_ATL_PHI,PHI,ATL,5,10,0,0,0,1,-0.412701,0,0,0,0,0,4,7,22,0,0,0,-3,22,1,-0.568193,0,0,0,0,0,-7.333333,0.2,-0.010526
43,00-0025394,A.Peterson,Adrian Peterson,RB,RB,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_WAS_ARI,WAS,ARI,26,96,1,0,0,4,0.717597,0,3,3,0,0,2,3,70,0,1,1,2,70,1,-0.67494,0,2,2,1,1,35.0,0.103448,0.019802
45,00-0025399,M.Lynch,Marshawn Lynch,RB,RB,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_LA_OAK,LV,LA,11,41,1,0,0,4,0.880488,0,1,0,0,0,2,2,8,0,0,0,-2,10,0,-0.262743,0,0,0,0,0,-4.0,0.052632,-0.009569
60,00-0026153,J.Stewart,Jonathan Stewart,RB,RB,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_JAX_NYG,NYG,JAX,2,8,0,0,0,0,-0.230811,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,<NA>,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149481,00-0037746,Br.Robinson,Brian Robinson,RB,RB,https://static.www.nfl.com/image/upload/f_auto...,2026,3,REG,2026_03_ATL_GB,ATL,GB,10,50,1,0,0,4,3.348714,0,1,1,0,0,0,0,0,0,0,0,0,0,0,<NA>,0,0,0,0,0,<NA>,0.0,0.0
149488,00-0038542,Bi.Robinson,Bijan Robinson,RB,RB,https://static.www.nfl.com/image/upload/f_auto...,2026,3,REG,2026_03_ATL_GB,ATL,GB,29,194,2,0,0,11,8.700967,0,4,2,2,1,2,2,19,0,0,0,-10,29,1,1.268524,0,1,1,0,0,-1.9,0.086957,-0.067114
149489,00-0038685,C.Brooks,Chris Brooks,RB,RB,https://static.www.nfl.com/image/upload/f_auto...,2026,3,REG,2026_03_ATL_GB,GB,ATL,0,0,0,0,0,0,<NA>,0,0,0,0,0,1,1,4,0,0,0,-1,5,0,-0.119538,0,0,0,0,0,-4.0,0.019608,-0.002551
149495,00-0039811,M.Lloyd,MarShawn Lloyd,RB,RB,https://static.www.nfl.com/image/upload/f_auto...,2026,3,REG,2026_03_ATL_GB,GB,ATL,4,11,0,0,0,1,-0.602733,0,0,0,0,0,2,3,7,0,0,0,-12,17,0,-0.327275,0,1,0,0,0,-0.583333,0.058824,-0.030612
149505,00-0040142,K.Johnson,Kaleb Johnson,RB,RB,https://static.www.nfl.com/image/upload/f_auto...,2026,3,REG,2026_03_ATL_GB,GB,ATL,4,6,0,0,0,0,-1.756491,0,0,0,0,0,1,3,10,0,0,0,-1,10,1,-0.466297,0,1,0,0,0,-10.0,0.058824,-0.002551

# Explore WR/TE DataFrame

In [254]:
wr_df

,player_id,player_name,player_display_name,position,position_group,headshot_url,season,week,season_type,game_id,team,opponent_team,receptions,targets,receiving_yards,receiving_tds,receiving_fumbles,receiving_fumbles_lost,receiving_air_yards,receiving_yards_after_catch,receiving_first_downs,receiving_epa,receiving_2pt_conversions,receiving_10,receiving_16,receiving_20,receiving_40,racr,target_share,air_yards_share
7,00-0021547,A.Gates,Antonio Gates,TE,TE,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_KC_LAC,LAC,KC,2,3,16,0,0,0,27,5,1,1.958386,1,0,0,0,0,0.592593,0.06,0.055901
12,00-0022921,L.Fitzgerald,Larry Fitzgerald,WR,WR,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_WAS_ARI,ARI,WAS,7,10,76,0,0,0,90,21,3,2.103913,0,2,2,2,0,0.844444,0.294118,0.432692
15,00-0022943,B.Watson,Benjamin Watson,TE,TE,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_TB_NO,NO,TB,4,4,44,0,0,0,41,3,4,5.120501,0,2,1,1,0,1.073171,0.090909,0.117816
33,00-0024221,V.Davis,Vernon Davis,TE,TE,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_WAS_ARI,WAS,ARI,1,1,9,0,0,0,6,3,1,1.271547,0,0,0,0,0,1.5,0.034483,0.059406
37,00-0024334,B.Marshall,Brandon Marshall,WR,WR,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_SEA_DEN,SEA,DEN,3,6,46,1,0,0,83,1,3,2.754787,0,3,1,1,0,0.554217,0.181818,0.246291
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149485,00-0038124,C.Watson,Christian Watson,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2026,3,REG,2026_03_ATL_GB,GB,ATL,7,10,96,1,0,0,91,26,5,1.974622,0,4,2,2,0,1.054945,0.196078,0.232143
149491,00-0038996,T.Kraft,Tucker Kraft,TE,TE,https://static.www.nfl.com/image/upload/f_auto...,2026,3,REG,2026_03_ATL_GB,GB,ATL,4,8,26,0,0,0,36,18,1,-1.991541,0,0,0,0,0,0.722222,0.156863,0.091837
149508,00-0040667,M.Golden,Matthew Golden,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2026,3,REG,2026_03_ATL_GB,GB,ATL,5,12,100,1,0,0,199,30,4,4.615772,0,4,2,2,1,0.502513,0.235294,0.507653
149513,00-0040948,J.Sturdivant,J. Michael Sturdivant,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2026,3,REG,2026_03_ATL_GB,GB,ATL,3,3,22,0,0,0,22,0,2,3.189627,0,1,0,0,0,1.0,0.058824,0.056122
149514,00-0041044,Z.Branch,Zachariah Branch,WR,WR,https://static.www.nfl.com/image/upload/f_auto...,2026,3,REG,2026_03_ATL_GB,ATL,GB,1,2,7,0,0,0,13,11,0,-0.85834,0,0,0,0,0,0.538462,0.086957,0.087248

# Explore Defense DataFrame

In [255]:
def_df

,player_id,player_name,player_display_name,position,position_group,headshot_url,season,week,season_type,game_id,team,opponent_team,def_tackles_solo,def_tackles_with_assist,def_tackle_assists,def_tackles_for_loss,def_tackles_for_loss_yards,def_fumbles_forced,def_sacks,def_sack_yards,def_qb_hits,def_interceptions,def_interception_yards,def_pass_defended,def_tds,def_fumbles,def_safeties,def_punt_blocks,def_pat_blocks,def_fg_blocks,def_2pt_atts,def_2pt_made,misc_yards,fumble_recovery_own,fumble_recovery_yards_own,fumble_recovery_opp,fumble_recovery_yards_opp,fumble_recovery_tds
6,00-0021140,J.Peppers,Julius Peppers,DE,DL,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_DAL_CAR,CAR,DAL,0,0,1,0,0,0,0.0,0.0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,00-0022247,M.Adams,Mike Adams,FS,DB,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_DAL_CAR,CAR,DAL,2,0,3,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,00-0023368,C.Wake,Cameron Wake,LB,LB,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_TEN_MIA,MIA,TEN,1,1,2,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
21,00-0023441,A.Jones,Adam Jones,DB,DB,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_SEA_DEN,DEN,SEA,2,0,0,1,2,0,0.0,0.0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
22,00-0023449,D.Johnson,Derrick Johnson,LB,LB,https://static.www.nfl.com/image/private/f_aut...,2018,1,REG,2018_01_LA_OAK,LV,LA,3,2,0,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149510,00-0040877,D.Dennis-Sutton,Dani Dennis-Sutton,LB,LB,https://static.www.nfl.com/image/upload/f_auto...,2026,3,REG,2026_03_ATL_GB,GB,ATL,0,0,2,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
149515,00-0041066,K.Daniels,Kendal Daniels,LB,LB,https://static.www.nfl.com/image/upload/f_auto...,2026,3,REG,2026_03_ATL_GB,ATL,GB,2,0,1,1,3,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
149516,00-0041112,H.Perkins,Harold Perkins Jr.,LB,LB,https://static.www.nfl.com/image/upload/f_auto...,2026,3,REG,2026_03_ATL_GB,ATL,GB,2,0,2,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
149517,00-0041469,Av.Terrell,Avieon Terrell,CB,DB,https://static.www.nfl.com/image/upload/f_auto...,2026,3,REG,2026_03_ATL_GB,ATL,GB,0,0,1,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
149518,00-0041470,B.Cisse,Brandon Cisse,CB,DB,https://static.www.nfl.com/image/upload/f_auto...,2026,3,REG,2026_03_ATL_GB,GB,ATL,4,0,3,0,0,0,0.0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0